apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
type: Opaque
stringData:
  admin-password: ENC[AES256_GCM,data:zytsgsanXU4W7rqY,iv:s7mSJwfgL1FkDV0o9ISbxREM0SI71NYwTaKdzyIgXHU=,tag:akFjsKARLnAnb6IP3aG6KA==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMnh6MDhmQlRSN2dpbjMv
        cWV2OERFMXR5OTVzR1FybG5DcW1IRHlBR0g0CjYxYnNFeUcwRjBPdkxYUk94MjRq
        eDRlekYxRHkrSlpVUWNRYmFIWU91a0UKLS0tIE9zRmlUcTJJeHl1ZFU1cmpwT3Uv
        QmlCVUdUd3B2OXFIcUlnaDdGOGloL2sKt8n4/Fwv4bFTbjORgdDLQ57c/XzHEUds
        Yjjq0AlBPXmPp5uKkp4mj6kRTmYA7iYSlP5yaUOcHzky+mZUCOVrWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:46:36Z"
  mac: ENC[AES256_GCM,data:8jQYWbPvV0WhRIpFdIItynmdbKwLVD3qCqdn1OSc1S8BEVgmekZU0lKbz4DiXYfY2qt3bz+ZQRXB3fKzOx518a7EWmpV69lMJEHcCwlPMLzAgEwO8pkcOsOKUMOjjJBEUSmkbDnE5MPbr4KWJfUsFtkLCWzR58LQcEtBt2G9Zfk=,iv:86BA8xODK9mSbHd8pe7bgDpz4ilm7PO16YubR5+ja3M=,tag:2UX3aTzba9GA6G+AQ0zUtA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
