apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clickhouse-secret
  namespace: database # Make sure namespace is correct if required or implied by kustomization
spec:
  target:
    name: clickhouse-secret
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  data:
    - secretKey: admin-password
      remoteRef:
        key: clickhouse
        property: password
