apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clickhouse-secret
  namespace: database # Make sure namespace is correct if required or implied by kustomization
spec:
  refreshInterval: "1h0m0s"
  target:
    name: clickhouse-secret
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  data:
    - secretKey: admin-password
      remoteRef:
        key: 9d03ad48-2758-44ea-a203-444aa76f2b02
        property: password
