apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
spec:
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      engineVersion: v2
      data:
        redis.password: "{{ .redis_password }}"
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  data:
    - secretKey: redis_password
      remoteRef:
        key: redis
        property: password
