apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
spec:
  # Do not use target.name so it defaults to argocd-secret? Wait.
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      engineVersion: v2
      data:
        # Maps what the helm chart expected in configs.secret
        admin.password: "{{ .admin_password }}"
        admin.passwordMtime: "{{ .mtime }}"
        github.secret: "{{ .github_secret }}"
        redis.password: "{{ .redis_password }}"
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  data:
    - secretKey: admin_password
      remoteRef:
        key: argo-cd
        property: admin-password
    - secretKey: mtime
      remoteRef:
        key: argo-cd
        property: admin-passwordMtime
    - secretKey: github_secret
      remoteRef:
        key: argo-cd
        property: github-secret
    - secretKey: redis_password
      remoteRef:
        key: argo-cd
        property: redis-password
