apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  hostnames:
    - argo.aknuk.dev
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQT1pCb0d4dEN0cm9FM3k4
        MXorNFZkRi90OXg3VzREU2hLblMweWZ0RlI0ClNEU01pM0gwQlRmUHlFNE9hZ0xu
        Z1d3YWphVXdEVUIrR2FRZXIwWFQyTm8KLS0tIHdXOS9mdDFOMnR2UmxjMVU3akgx
        NzR0azFLUlVESHVUZXZSSzU1OG9BWjAKR7MHJ24UQtNq+jLHGhrLOS9TNl93CU9O
        sHLfTxed1JgmCetc8EXWb4+KVnFhAnIoasKMBhWUtbGITFS8Hc8agg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T07:32:34Z"
  mac: ENC[AES256_GCM,data:heQePj7+NO9ber9n313EOpT1AAPz7nl6WPiZ2BFU8gENb+k71FEYT3caYW0M4K7I/urPvDRVHWbiCOsYE+B6/pL8QLou32oB2SlPwK8c++Zrgp2TwqeQ6GRwbNeiQrcLeXacJBcEcqdjLqfHWFgCWYXGC1UiBufRVqDJyIpxFyg=,iv:FHA9oAwyqITteG3VHlsjROObt5CYUKb3b/OAxnOTL5M=,tag:YjuEs/7cbfiJ3HltaDOXzw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
