apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  hostnames:
    - argo.aknuk.dev
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NTIvQVUvYXVTMTN1MVBU
        cHZtMVg3ci9EMjFlZERGMVpnTHRmRmhkSTBRClBmWjJseEpLeDJnOXJOYUlQY3hF
        ekhSRldiMDVVOWhiNVJPU2dPV21oQTgKLS0tIGtTZWN1ZXVqak01ME50QmtybXhz
        RTVCOWk2Q29jall6MGRNOHoxZko1RGsK4f2iGtvAt0h9wn0B3ox8t5vGJNwYztKz
        JK4PQmMeMy+AfaSTT6JsCarTs4qr9nwdiqGvg8c+X0UqoH4kQ3pYTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T10:25:18Z"
  mac: ENC[AES256_GCM,data:7BDpwhz49KIetaLGUu5dxq5XyIXOX2TFoIKl+HE+aUpBlVKWP+6bGjOOh7n3u5GqW0qnU8xjufZZRvVOhLnI3kdH6ASotVAytr6aZSFJB1dLtgLbcqFHTov1pl5uyLGsI1Fn0fpb6sysaljG1joYe8pLcBgq9box1uvNODuWOHQ=,iv:Rf7TW8gUbnEIBOIjTxzPjcGZwJR0sPq8Njv894K++l0=,tag:vgIC+Y38NYWgF9xusJERCA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
