apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  hostnames:
    - argo.aknuk.dev
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNExGYnM1b1IvdTFEM21H
        bGJlaS9wUDlqY3BQSzFIbTMyR0w3eENBcUVrCmZVZ2g3Y3h6YVI3VVE4TEpMZDB3
        VzZISmhVZGtYM2hlb2l2dzkwUS9nS0EKLS0tIHBnNUhtam1VRVRBWlRYM0VCRHJM
        NEhPaFZZekVlKyt0WUZOUFM4cVN3S3MKY9MyD2i0ikRSiTBgDTNNY1TAkiyUQs39
        pTiE0v9mLRS6mx8cl3QDGy7R9J2yqff3/7FkoWAD/qYcS0kAGCJ86A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T11:25:36Z"
  mac: ENC[AES256_GCM,data:9uvtvB2ArpeZNNMk2EvrFP6pj/CXkoaFNs7rFbPHnM3g5+juWhQnOE+hTY+lzl3fhiwCta6r9/7PBEqDuiytuOfwF9sNzt2Ys4hOWtUHyYN5s/88ZJA58RPy+nXKIOvFyMWIPHTl9ZZX/pZdiFgxgWq849jiUeW8sQWQXvRHfo4=,iv:l1hXE/ZK48bSbYTksRseIUJO/dSbxJ8WQMqwvy7gCw4=,tag:U8ok0GF/gQwPKKO3YjDLRw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
