apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: headlamp-oidc-secret
spec:
  # The headlamp chart expects a secret named "oidc" by default if we override it, or we just configure it.
  target:
    name: oidc
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  data:
    - secretKey: client-secret # Standard key used by helm chart
      remoteRef:
        key: headlamp
        property: oidc-client-secret
