apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arc-auth-secret
spec:
  target:
    name: arc-auth-secret
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  data:
    - secretKey: github_token
      remoteRef:
        key: github
        property: token
