apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-auth-secret
spec:
  refreshInterval: "1h0m0s"
  target:
    name: arc-auth-secret
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  data:
    - secretKey: github_token
      remoteRef:
        key: 4b58f32a-f104-4434-a2b3-b64cd5ee8bc4
        property: password
