global:
  postgresql:
    auth:
      username: "admin"
      database: "admin"
      existingSecret: "postgresql-secret"
      secretKeys:
        adminPasswordKey: "postgres-password"
        userPasswordKey: "password"
architecture: standalone # Use replication for true HA if preferred
primary:
  persistence:
    enabled: true
    size: 20Gi
