---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amd-gpu-device-plugin
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/ajaykumar4/home-lab.git"
      path: kubernetes/apps/kube-system/amd-gpu-device-plugin
      targetRevision: main
      ref: repo
    - repoURL: https://radeonopencompute.github.io/k8s-device-plugin/
      chart: amd-gpu
      targetRevision: 0.14.0 # Using recent 0.14.0, adjust based on your ROCm version
      helm:
        releaseName: amd-gpu-device-plugin
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
