---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - amd-gpu-device-plugin.yaml
  - cilium.yaml
  - coredns.yaml
  - descheduler.yaml
  - headlamp.yaml
  - kyverno.yaml
  - metrics-server.yaml
  - reloader.yaml
