---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: truenas-nfs
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: kubernetes
  sources:
    - repoURL: ghcr.io/democratic-csi/charts
      chart: snapshot-controller
      targetRevision: 0.3.0
      helm:
        releaseName: snapshot-controller
  destination:
    name: in-cluster
    namespace: storage
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
