apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate-secret
spec:
  target:
    name: renovate-secret
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: github
        property: token
