---
# Add Nginx Ingress Controller Helm repository
    - name: Add Nginx Ingress Controller Helm repository
      helm:
        repository: kubernetes.github.io/ingress-nginx
        state: present
        update: true

    # Create Ingress namespace
    - name: Create Ingress namespace
      kubernetes:
        namespace: ingress-nginx
        state: present

    # Deploy Nginx Ingress Controller using Helm chart with values from file
    - name: Deploy Nginx Ingress Controller using Helm chart
      helm:
        chart: ingress-nginx/ingress-nginx
        namespace: ingress-nginx
        release: ingress-nginx
        values: nginx-values.yml

    # Check Ingress pods status
    - name: Check Ingress pods status
      kubernetes:
        state: present
        resource: pod
        namespace: ingress-nginx
        register: ingress_nginx_pods

    - name: Verify Ingress pods are running
      assert:
        that:
          - ingress_nginx_pods.pods | length > 0
          - ingress_nginx_pods.pods | map('state.phase') | count('Running') == ingress_nginx_pods.pods | length

    # Print Ingress pods information
    - name: Print Ingress pods information
      debug:
        msg: "{{ ingress_nginx_pods.pods }}"