apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aknuk-dev-production
spec:
  dnsNames:
    - aknuk.dev
    - '*.aknuk.dev'
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: aknuk-dev-production-tls
  usages:
    - digital signature
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ejE1eFRmNCtyeWIxWFc3
        cE9rcTdWTjZHRERodHg2NkFjQnZwZjZoeG5VCnFaQ1lIZGxUK2ErTk03OENVR2Ur
        Ti9ma2ZpYkFmdVZWZVRkaFJDQjFPRUUKLS0tIG9MUDdFNFVDZzVoS2lOYnJBOEdF
        VTZscnhzSXNiQWE3aWJFQ2Q3Qml1cjQK/D2MPhAjZAgw5BrSTba2wGYJ1T2Iu7Ba
        ux4URLQg48XihKbODmosyRmixLgqDUdu7Ivcr3x9qX1c9belCHstUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T09:57:49Z"
  mac: ENC[AES256_GCM,data:fq0BzSVX/4zA4fb4DuLh6L1fz9z5fJMCqUqcEPzH07ApbV0gQ7AinKtWK/tldKmu9JGBDa4G5uBLwnfQCQX3ksyMxChEND0VqdR0ImRmF1uKQYYDvlX4srWVPR4zUdz1UIHme7I6M+Lp4xhHdVfg6QT9PFypH/sHWk0RjOpvayY=,iv:gQBjqo3jiMCeYLiJzGUbAVh3R6ut9P6rjEW62Kc23Xg=,tag:mqL4x9ygg2Rk7it0XtG9Ww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
