apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aknuk-dev-production
spec:
  dnsNames:
    - aknuk.dev
    - '*.aknuk.dev'
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: aknuk-dev-production-tls
  usages:
    - digital signature
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUjZ3UUg4c1ZjODB6SlZp
        TlVmMlpHb2dod21ocjBKL0s3TXpQNkdqQWhvCnN5eDg1ZG1TaU1NUTZGSDl4SGE4
        czcvbmtSQVNKYmEyUmFJRUtRcWVIR3MKLS0tIHA3V3E2Zm5Yc0VuRk1QcnRuT1hv
        eVNTN0dwZEZBOUJxc1dZd1I4VGJvbk0K/IiTfXFIt1jCah4qXSQhlUpgwcLZo2SX
        PSUmOHmlsN3nusltronsXsCdOPTDwKudgFfbURItlCn6ut1dMGVF4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T10:25:18Z"
  mac: ENC[AES256_GCM,data:k2POUkGEivTEg19Y9TI+DizyHCEJ/De44f6ju/w4dXiW+meMM0JH3YOeIo2VfKaJ4drsIfxAlMOsE6WXNQtD6zwWjN/suwt/06EvMRe+bvaUuc2QYbukD2GcEWoLuUW22aF1mCbSaPYrMFMnKeZGoiBf79RZyizcdd9bSoL331Q=,iv:G03p+yLT7PuPkjCTItxOWJ+IiTdudI/aiXY8bMtwi7Q=,tag:vr+dd4RAaDKwnVZ4f07bJQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
