apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-domain-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: cloudflare-domain-config
    template:
      data:
        tunnel-id: "{{ .tunnelID }}"
        domain: "{{ .Domain }}"
  dataFrom:
    - extract:
        key: cloudflare

