apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-domain-config
spec:
  refreshInterval: "1h0m0s"
  target:
    name: cloudflare-domain-config
    template:
      engineVersion: v2
      type: Opaque
      data:
        domain: "{{ .domain }}"
        tunnel-id: "{{ .tunnelID }}"
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  data:
    - secretKey: domain
      remoteRef:
        key: 2663d32c-47b4-4e4c-917d-95cd4bae8fb8
        property: domain
    - secretKey: tunnelID
      remoteRef:
        key: 2663d32c-47b4-4e4c-917d-95cd4bae8fb8
        property: TunnelID
