apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy
spec:
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        container:
          imageRepository: mirror.gcr.io/envoyproxy/envoy
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 1Gi
      envoyService:
        externalTrafficPolicy: Cluster
  shutdown:
    drainTimeout: 180s
  telemetry:
    metrics:
      prometheus:
        compression:
          type: Zstd
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva2xPNm16QTRUMXo0R0Nx
        Z1ArTnFibGtLL3NsMG11dzRiRzBwZy9JcGdnCjB2UkxKSXJUc2pjS1FYWkhQa1RI
        YlUrM2QzSzBvZzlOVDZpMkZmS3RMK3MKLS0tIDZOTkJQQVhvK3pMQWtJSTNhR2dL
        Q01iMFgwL2diTUx1NTZwWHdvT29CSWcKSnv8DZ+kdEJxwJQGiZH3IP1b9GO4N3tA
        TCT9MojiaDJThpyvmmZ7/PcwBpNFEqf+ILParYn48uTl2a279EZP6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T12:25:18Z"
  mac: ENC[AES256_GCM,data:iAMuSf/52kDoGIQVBLb6GJLDrSRgIAlOXhpzdpTuh4iGQpXow69rBing2nH9LNcxVEhpIOYyse5IGC1mJcUZRmFmZ5O11nURBah+tFjtf9ksZ7snllIPSZZpOJ+3YwukwQeTSRzYhXl/gqhEVFQlh2FdQEGiXyMZ8dLVss8DJbs=,iv:4m8UOAC1Npk+vmSg5LZwJJifugPirXceqmzCZSofQu8=,tag:fw+K3bqnXzr+KN4C8kramA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: envoy
    namespace: network
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva2xPNm16QTRUMXo0R0Nx
        Z1ArTnFibGtLL3NsMG11dzRiRzBwZy9JcGdnCjB2UkxKSXJUc2pjS1FYWkhQa1RI
        YlUrM2QzSzBvZzlOVDZpMkZmS3RMK3MKLS0tIDZOTkJQQVhvK3pMQWtJSTNhR2dL
        Q01iMFgwL2diTUx1NTZwWHdvT29CSWcKSnv8DZ+kdEJxwJQGiZH3IP1b9GO4N3tA
        TCT9MojiaDJThpyvmmZ7/PcwBpNFEqf+ILParYn48uTl2a279EZP6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T12:25:18Z"
  mac: ENC[AES256_GCM,data:iAMuSf/52kDoGIQVBLb6GJLDrSRgIAlOXhpzdpTuh4iGQpXow69rBing2nH9LNcxVEhpIOYyse5IGC1mJcUZRmFmZ5O11nURBah+tFjtf9ksZ7snllIPSZZpOJ+3YwukwQeTSRzYhXl/gqhEVFQlh2FdQEGiXyMZ8dLVss8DJbs=,iv:4m8UOAC1Npk+vmSg5LZwJJifugPirXceqmzCZSofQu8=,tag:fw+K3bqnXzr+KN4C8kramA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-external
  annotations:
    external-dns.alpha.kubernetes.io/target: external.aknuk.dev
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: external.aknuk.dev
      lbipam.cilium.io/ips: 192.168.8.203
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: aknuk-dev-production-tls
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva2xPNm16QTRUMXo0R0Nx
        Z1ArTnFibGtLL3NsMG11dzRiRzBwZy9JcGdnCjB2UkxKSXJUc2pjS1FYWkhQa1RI
        YlUrM2QzSzBvZzlOVDZpMkZmS3RMK3MKLS0tIDZOTkJQQVhvK3pMQWtJSTNhR2dL
        Q01iMFgwL2diTUx1NTZwWHdvT29CSWcKSnv8DZ+kdEJxwJQGiZH3IP1b9GO4N3tA
        TCT9MojiaDJThpyvmmZ7/PcwBpNFEqf+ILParYn48uTl2a279EZP6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T12:25:18Z"
  mac: ENC[AES256_GCM,data:iAMuSf/52kDoGIQVBLb6GJLDrSRgIAlOXhpzdpTuh4iGQpXow69rBing2nH9LNcxVEhpIOYyse5IGC1mJcUZRmFmZ5O11nURBah+tFjtf9ksZ7snllIPSZZpOJ+3YwukwQeTSRzYhXl/gqhEVFQlh2FdQEGiXyMZ8dLVss8DJbs=,iv:4m8UOAC1Npk+vmSg5LZwJJifugPirXceqmzCZSofQu8=,tag:fw+K3bqnXzr+KN4C8kramA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-internal
  annotations:
    external-dns.alpha.kubernetes.io/target: internal.aknuk.dev
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: internal.aknuk.dev
      lbipam.cilium.io/ips: 192.168.8.202
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: aknuk-dev-production-tls
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva2xPNm16QTRUMXo0R0Nx
        Z1ArTnFibGtLL3NsMG11dzRiRzBwZy9JcGdnCjB2UkxKSXJUc2pjS1FYWkhQa1RI
        YlUrM2QzSzBvZzlOVDZpMkZmS3RMK3MKLS0tIDZOTkJQQVhvK3pMQWtJSTNhR2dL
        Q01iMFgwL2diTUx1NTZwWHdvT29CSWcKSnv8DZ+kdEJxwJQGiZH3IP1b9GO4N3tA
        TCT9MojiaDJThpyvmmZ7/PcwBpNFEqf+ILParYn48uTl2a279EZP6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T12:25:18Z"
  mac: ENC[AES256_GCM,data:iAMuSf/52kDoGIQVBLb6GJLDrSRgIAlOXhpzdpTuh4iGQpXow69rBing2nH9LNcxVEhpIOYyse5IGC1mJcUZRmFmZ5O11nURBah+tFjtf9ksZ7snllIPSZZpOJ+3YwukwQeTSRzYhXl/gqhEVFQlh2FdQEGiXyMZ8dLVss8DJbs=,iv:4m8UOAC1Npk+vmSg5LZwJJifugPirXceqmzCZSofQu8=,tag:fw+K3bqnXzr+KN4C8kramA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: envoy
spec:
  compressor:
    - type: Zstd
      zstd: {}
    - type: Brotli
      brotli: {}
    - type: Gzip
      gzip: {}
  retry:
    numRetries: 2
    retryOn:
      triggers:
        - reset
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  tcpKeepalive: {}
  timeout:
    http:
      requestTimeout: 0s
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva2xPNm16QTRUMXo0R0Nx
        Z1ArTnFibGtLL3NsMG11dzRiRzBwZy9JcGdnCjB2UkxKSXJUc2pjS1FYWkhQa1RI
        YlUrM2QzSzBvZzlOVDZpMkZmS3RMK3MKLS0tIDZOTkJQQVhvK3pMQWtJSTNhR2dL
        Q01iMFgwL2diTUx1NTZwWHdvT29CSWcKSnv8DZ+kdEJxwJQGiZH3IP1b9GO4N3tA
        TCT9MojiaDJThpyvmmZ7/PcwBpNFEqf+ILParYn48uTl2a279EZP6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T12:25:18Z"
  mac: ENC[AES256_GCM,data:iAMuSf/52kDoGIQVBLb6GJLDrSRgIAlOXhpzdpTuh4iGQpXow69rBing2nH9LNcxVEhpIOYyse5IGC1mJcUZRmFmZ5O11nURBah+tFjtf9ksZ7snllIPSZZpOJ+3YwukwQeTSRzYhXl/gqhEVFQlh2FdQEGiXyMZ8dLVss8DJbs=,iv:4m8UOAC1Npk+vmSg5LZwJJifugPirXceqmzCZSofQu8=,tag:fw+K3bqnXzr+KN4C8kramA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy
spec:
  clientIPDetection:
    xForwardedFor:
      trustedCIDRs:
        - 10.42.0.0/16
  http2:
    onInvalidMessage: TerminateStream
  http3: {}
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  tcpKeepalive: {}
  tls:
    minVersion: "1.2"
    alpnProtocols:
      - h2
      - http/1.1
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva2xPNm16QTRUMXo0R0Nx
        Z1ArTnFibGtLL3NsMG11dzRiRzBwZy9JcGdnCjB2UkxKSXJUc2pjS1FYWkhQa1RI
        YlUrM2QzSzBvZzlOVDZpMkZmS3RMK3MKLS0tIDZOTkJQQVhvK3pMQWtJSTNhR2dL
        Q01iMFgwL2diTUx1NTZwWHdvT29CSWcKSnv8DZ+kdEJxwJQGiZH3IP1b9GO4N3tA
        TCT9MojiaDJThpyvmmZ7/PcwBpNFEqf+ILParYn48uTl2a279EZP6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T12:25:18Z"
  mac: ENC[AES256_GCM,data:iAMuSf/52kDoGIQVBLb6GJLDrSRgIAlOXhpzdpTuh4iGQpXow69rBing2nH9LNcxVEhpIOYyse5IGC1mJcUZRmFmZ5O11nURBah+tFjtf9ksZ7snllIPSZZpOJ+3YwukwQeTSRzYhXl/gqhEVFQlh2FdQEGiXyMZ8dLVss8DJbs=,iv:4m8UOAC1Npk+vmSg5LZwJJifugPirXceqmzCZSofQu8=,tag:fw+K3bqnXzr+KN4C8kramA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  annotations:
    external-dns.alpha.kubernetes.io/controller: none
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: http
    - name: envoy-internal
      namespace: network
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva2xPNm16QTRUMXo0R0Nx
        Z1ArTnFibGtLL3NsMG11dzRiRzBwZy9JcGdnCjB2UkxKSXJUc2pjS1FYWkhQa1RI
        YlUrM2QzSzBvZzlOVDZpMkZmS3RMK3MKLS0tIDZOTkJQQVhvK3pMQWtJSTNhR2dL
        Q01iMFgwL2diTUx1NTZwWHdvT29CSWcKSnv8DZ+kdEJxwJQGiZH3IP1b9GO4N3tA
        TCT9MojiaDJThpyvmmZ7/PcwBpNFEqf+ILParYn48uTl2a279EZP6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T12:25:18Z"
  mac: ENC[AES256_GCM,data:iAMuSf/52kDoGIQVBLb6GJLDrSRgIAlOXhpzdpTuh4iGQpXow69rBing2nH9LNcxVEhpIOYyse5IGC1mJcUZRmFmZ5O11nURBah+tFjtf9ksZ7snllIPSZZpOJ+3YwukwQeTSRzYhXl/gqhEVFQlh2FdQEGiXyMZ8dLVss8DJbs=,iv:4m8UOAC1Npk+vmSg5LZwJJifugPirXceqmzCZSofQu8=,tag:fw+K3bqnXzr+KN4C8kramA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
