apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy
spec:
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        container:
          imageRepository: mirror.gcr.io/envoyproxy/envoy
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 1Gi
      envoyService:
        externalTrafficPolicy: Cluster
  shutdown:
    drainTimeout: 180s
  telemetry:
    metrics:
      prometheus:
        compression:
          type: Zstd
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VGtOVEIzUE81VGdUb2tF
        cHE1aFhSMFJNSG1kU0gwNWJCY1JqVmUvRm5rCk45UVMreW13a0g1U25TN3pqVEpQ
        WStxaUZqS2pBVFlVRk5ZT24vS0djVk0KLS0tIDd4Z096Qi82MmpUSFVpZ0l2M3g0
        bng2ZHBta3hHQkkxRWhkNlFjTXJGYTgK0Gw7WBF3X3X0MP4otfw1g3RyvMcLjQzl
        GtHb0BA/XgXgUDZ4Ib/KZPoBFV+BV8S0R3JFKjiJP/7PfD2tf722gA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T07:44:15Z"
  mac: ENC[AES256_GCM,data:lR2IAg+tIzzsfVA68XVeWX8ZO93goVy5hSGARh8hdsyFz40ty/vYEkiC2UD6Dkuf2USDwzvbmqYvFTFhKCY+iqwohTlaY5B8p3y7MlusJeYacpf6SdD3dIrdCjywLOZAz1Tq2dB7Kv7IHUpk9/oCyKAa8G5a9cttUXuD9O3pJ8c=,iv:Gp0lG76Mwx4xoz/UESrfo/DF5eoA1w0KkZ1zMcrtSbk=,tag:3l1cy0S4APQc1X4YNLV0aw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: envoy
    namespace: network
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VGtOVEIzUE81VGdUb2tF
        cHE1aFhSMFJNSG1kU0gwNWJCY1JqVmUvRm5rCk45UVMreW13a0g1U25TN3pqVEpQ
        WStxaUZqS2pBVFlVRk5ZT24vS0djVk0KLS0tIDd4Z096Qi82MmpUSFVpZ0l2M3g0
        bng2ZHBta3hHQkkxRWhkNlFjTXJGYTgK0Gw7WBF3X3X0MP4otfw1g3RyvMcLjQzl
        GtHb0BA/XgXgUDZ4Ib/KZPoBFV+BV8S0R3JFKjiJP/7PfD2tf722gA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T07:44:15Z"
  mac: ENC[AES256_GCM,data:lR2IAg+tIzzsfVA68XVeWX8ZO93goVy5hSGARh8hdsyFz40ty/vYEkiC2UD6Dkuf2USDwzvbmqYvFTFhKCY+iqwohTlaY5B8p3y7MlusJeYacpf6SdD3dIrdCjywLOZAz1Tq2dB7Kv7IHUpk9/oCyKAa8G5a9cttUXuD9O3pJ8c=,iv:Gp0lG76Mwx4xoz/UESrfo/DF5eoA1w0KkZ1zMcrtSbk=,tag:3l1cy0S4APQc1X4YNLV0aw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-external
  annotations:
    external-dns.alpha.kubernetes.io/target: external.aknuk.dev
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: external.aknuk.dev
      lbipam.cilium.io/ips: 192.168.8.203
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: aknuk-dev-production-tls
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VGtOVEIzUE81VGdUb2tF
        cHE1aFhSMFJNSG1kU0gwNWJCY1JqVmUvRm5rCk45UVMreW13a0g1U25TN3pqVEpQ
        WStxaUZqS2pBVFlVRk5ZT24vS0djVk0KLS0tIDd4Z096Qi82MmpUSFVpZ0l2M3g0
        bng2ZHBta3hHQkkxRWhkNlFjTXJGYTgK0Gw7WBF3X3X0MP4otfw1g3RyvMcLjQzl
        GtHb0BA/XgXgUDZ4Ib/KZPoBFV+BV8S0R3JFKjiJP/7PfD2tf722gA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T07:44:15Z"
  mac: ENC[AES256_GCM,data:lR2IAg+tIzzsfVA68XVeWX8ZO93goVy5hSGARh8hdsyFz40ty/vYEkiC2UD6Dkuf2USDwzvbmqYvFTFhKCY+iqwohTlaY5B8p3y7MlusJeYacpf6SdD3dIrdCjywLOZAz1Tq2dB7Kv7IHUpk9/oCyKAa8G5a9cttUXuD9O3pJ8c=,iv:Gp0lG76Mwx4xoz/UESrfo/DF5eoA1w0KkZ1zMcrtSbk=,tag:3l1cy0S4APQc1X4YNLV0aw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-internal
  annotations:
    external-dns.alpha.kubernetes.io/target: internal.aknuk.dev
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: internal.aknuk.dev
      lbipam.cilium.io/ips: 192.168.8.202
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: aknuk-dev-production-tls
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VGtOVEIzUE81VGdUb2tF
        cHE1aFhSMFJNSG1kU0gwNWJCY1JqVmUvRm5rCk45UVMreW13a0g1U25TN3pqVEpQ
        WStxaUZqS2pBVFlVRk5ZT24vS0djVk0KLS0tIDd4Z096Qi82MmpUSFVpZ0l2M3g0
        bng2ZHBta3hHQkkxRWhkNlFjTXJGYTgK0Gw7WBF3X3X0MP4otfw1g3RyvMcLjQzl
        GtHb0BA/XgXgUDZ4Ib/KZPoBFV+BV8S0R3JFKjiJP/7PfD2tf722gA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T07:44:15Z"
  mac: ENC[AES256_GCM,data:lR2IAg+tIzzsfVA68XVeWX8ZO93goVy5hSGARh8hdsyFz40ty/vYEkiC2UD6Dkuf2USDwzvbmqYvFTFhKCY+iqwohTlaY5B8p3y7MlusJeYacpf6SdD3dIrdCjywLOZAz1Tq2dB7Kv7IHUpk9/oCyKAa8G5a9cttUXuD9O3pJ8c=,iv:Gp0lG76Mwx4xoz/UESrfo/DF5eoA1w0KkZ1zMcrtSbk=,tag:3l1cy0S4APQc1X4YNLV0aw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: envoy
spec:
  compressor:
    - type: Zstd
      zstd: {}
    - type: Brotli
      brotli: {}
    - type: Gzip
      gzip: {}
  retry:
    numRetries: 2
    retryOn:
      triggers:
        - reset
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  tcpKeepalive: {}
  timeout:
    http:
      requestTimeout: 0s
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VGtOVEIzUE81VGdUb2tF
        cHE1aFhSMFJNSG1kU0gwNWJCY1JqVmUvRm5rCk45UVMreW13a0g1U25TN3pqVEpQ
        WStxaUZqS2pBVFlVRk5ZT24vS0djVk0KLS0tIDd4Z096Qi82MmpUSFVpZ0l2M3g0
        bng2ZHBta3hHQkkxRWhkNlFjTXJGYTgK0Gw7WBF3X3X0MP4otfw1g3RyvMcLjQzl
        GtHb0BA/XgXgUDZ4Ib/KZPoBFV+BV8S0R3JFKjiJP/7PfD2tf722gA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T07:44:15Z"
  mac: ENC[AES256_GCM,data:lR2IAg+tIzzsfVA68XVeWX8ZO93goVy5hSGARh8hdsyFz40ty/vYEkiC2UD6Dkuf2USDwzvbmqYvFTFhKCY+iqwohTlaY5B8p3y7MlusJeYacpf6SdD3dIrdCjywLOZAz1Tq2dB7Kv7IHUpk9/oCyKAa8G5a9cttUXuD9O3pJ8c=,iv:Gp0lG76Mwx4xoz/UESrfo/DF5eoA1w0KkZ1zMcrtSbk=,tag:3l1cy0S4APQc1X4YNLV0aw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy
spec:
  clientIPDetection:
    xForwardedFor:
      trustedCIDRs:
        - 10.42.0.0/16
  http2:
    onInvalidMessage: TerminateStream
  http3: {}
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  tcpKeepalive: {}
  tls:
    minVersion: "1.2"
    alpnProtocols:
      - h2
      - http/1.1
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VGtOVEIzUE81VGdUb2tF
        cHE1aFhSMFJNSG1kU0gwNWJCY1JqVmUvRm5rCk45UVMreW13a0g1U25TN3pqVEpQ
        WStxaUZqS2pBVFlVRk5ZT24vS0djVk0KLS0tIDd4Z096Qi82MmpUSFVpZ0l2M3g0
        bng2ZHBta3hHQkkxRWhkNlFjTXJGYTgK0Gw7WBF3X3X0MP4otfw1g3RyvMcLjQzl
        GtHb0BA/XgXgUDZ4Ib/KZPoBFV+BV8S0R3JFKjiJP/7PfD2tf722gA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T07:44:15Z"
  mac: ENC[AES256_GCM,data:lR2IAg+tIzzsfVA68XVeWX8ZO93goVy5hSGARh8hdsyFz40ty/vYEkiC2UD6Dkuf2USDwzvbmqYvFTFhKCY+iqwohTlaY5B8p3y7MlusJeYacpf6SdD3dIrdCjywLOZAz1Tq2dB7Kv7IHUpk9/oCyKAa8G5a9cttUXuD9O3pJ8c=,iv:Gp0lG76Mwx4xoz/UESrfo/DF5eoA1w0KkZ1zMcrtSbk=,tag:3l1cy0S4APQc1X4YNLV0aw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  annotations:
    external-dns.alpha.kubernetes.io/controller: none
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: http
    - name: envoy-internal
      namespace: network
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VGtOVEIzUE81VGdUb2tF
        cHE1aFhSMFJNSG1kU0gwNWJCY1JqVmUvRm5rCk45UVMreW13a0g1U25TN3pqVEpQ
        WStxaUZqS2pBVFlVRk5ZT24vS0djVk0KLS0tIDd4Z096Qi82MmpUSFVpZ0l2M3g0
        bng2ZHBta3hHQkkxRWhkNlFjTXJGYTgK0Gw7WBF3X3X0MP4otfw1g3RyvMcLjQzl
        GtHb0BA/XgXgUDZ4Ib/KZPoBFV+BV8S0R3JFKjiJP/7PfD2tf722gA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T07:44:15Z"
  mac: ENC[AES256_GCM,data:lR2IAg+tIzzsfVA68XVeWX8ZO93goVy5hSGARh8hdsyFz40ty/vYEkiC2UD6Dkuf2USDwzvbmqYvFTFhKCY+iqwohTlaY5B8p3y7MlusJeYacpf6SdD3dIrdCjywLOZAz1Tq2dB7Kv7IHUpk9/oCyKAa8G5a9cttUXuD9O3pJ8c=,iv:Gp0lG76Mwx4xoz/UESrfo/DF5eoA1w0KkZ1zMcrtSbk=,tag:3l1cy0S4APQc1X4YNLV0aw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
