[macbook]
IRMAC-FKB3NMD6M ip_host_octet=2

[pc]
home-lab ip_host_octet=3

[rpi]
rpi01 ip_host_octet=4
rpi02 ip_host_octet=5
rpi03 ip_host_octet=6

[jetson]
jetson01 ip_host_octet=7
jetson02 ip_host_octet=8

[control_plane:children]
pc

[nodes:children]
rpi
jetson

[storage:children]
pc

[cluster:children]
control_plane
nodes

[all:children]
macbook
pc
rpi
jetson