apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.eu/api
      identityURL: https://vault.bitwarden.eu/identity
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
      bitwardenServerSDKURL: https://bitwarden-sdk-server.kube-system.svc.cluster.local:9998
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        key: ca.crt
      organizationID: 64fadc13-26c2-4f78-a58c-b40d00df8bce
      projectID: 5d892e1f-36b6-4273-826c-b42600ee37c9
