apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-s3-creds
spec:
  refreshInterval: "1h0m0s"
  target:
    name: velero-s3-creds
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .username }}
          aws_secret_access_key={{ .password }}
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: 831a7e64-674e-429c-b912-8fe24a7bb44c
        property: username
    - secretKey: password
      remoteRef:
        key: 831a7e64-674e-429c-b912-8fe24a7bb44c
        property: password
