apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: grafana-admin-password-secret
    template:
      engineVersion: v2
      data:
        GF_SECURITY_ADMIN_USER: "{{ .username }}"
        GF_SECURITY_ADMIN_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: 45ce5f90-df9e-42c9-a410-b43b014f1839
