apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:d2Zk3o05mZmyXioMeSl+BjvWTPh53OOuwm6EWV9u8BwXbTaS,iv:k+wdS+ZmW5Pn7IwfaK4JCOzVx6B1ft7D6jUl4PIs7Dg=,tag:ZIkSR62Slhu7/pXQhZsEhw==,type:str]
    credentials.json: ENC[AES256_GCM,data:D1vb+GpemKoBxr9QjJljflP1mxip+ayHHWoDrmy1ZZ9Cbvt8BXCws6PHXe60z4VTF1pMtHzqzAAtOgf/TdMLiTy06it46FfKdLJ7WAEIZeDKXn25Mju2HCf6eRsvNwgDW1bn1Ns0k+M3ct1SeQISoyYvgMbKDAsmpXKey2YHL5xTESuVIX/aiW9JZjxdo1Olo/8hdNS0RDAiP7yVa4CzUF6Dycz3mhm6yd8vqwJOag==,iv:XwrEgWRhZIS03x+upK7VQ3lbfGY52dcB73OP02tPhG0=,tag:SvWrcJ0LOl08XzycKqFwJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh9qxg0nplvlncvld27lg3h4f3epdsr32vuxswtxn95fyhj04ufsuq9cl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdTdCd2xtblpLUXZRN1Ur
            Z1NGVVp3SU1qc2NvNG5zdmpWbS8zb3pIdFZZCjJzazA3TmVVcTlvbUZWeGFDeU1k
            NTlETVczd1BrTytteko0WVJXNkcxRjAKLS0tIC90KzBYVjI5YkJ2ZWJEUkNUUS9L
            OVdvZXRWZWxwY3V5RmxtdGU1Nld0a3MK2CDjvm8fH/l275fWRmFJb9dEeahPcaEe
            9tkVDmUji9Lw4svgjP0pFW7xvNqcKeGRf15wo5yA/RvQEjxiMp5Zow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T13:50:43Z"
    mac: ENC[AES256_GCM,data:UfTAovLEOxCmw1XaeC0Kkd/J49QZtFCsBRH7kgHpLqLyL39yd2lqZQ29cFoI6ckm2QB4T7SpVS/27w7ZRvk+Pe3gIlmqTgnEjmVg3i7V3b5f1oCxgzBET/5XzKP52CZgfgjxU3d9us+Qs5KRPf7LYD1tm/5uvOBQExt6ClZrIeg=,iv:r3mcegO+JRKkIsle8Cm1NXcqtTMg7x56S4fAf+JbTu0=,tag:96YWLn/n/NJJqKM7QuE+Ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
