apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:AGX1JfOQzSReEpJOImDG/uk5tLd0RLCRxc0ZvE6uUxiG98RBPluSeA==,iv:DlnixLlYPNdPDHMwT+x9WNRGjRCU61o60EsBR7ri1xo=,tag:tSgANgorBPu0XEdEg/xQHA==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMndiZGtYOHR6akZlaWcy
        UDhROGtmQnB2S0hIK3k3Rk9qbVdibEMrT3drClZrTzA5RVZhNklXcGpUUGMvcVBL
        MFR3NUN3MnJGaEM5US9BRjZtaE9xcGcKLS0tIGdjbVQzVTN2QUFGaXdXRWlyTWpV
        ekNzbCttZHh6c0x4WGc2dkFWcG0vLzgKc0h2nOwQ/YVtLrI5bfNKwMn9ozVPLMXB
        S2qbDk0jeDHJp326tr+Z/j7ik+IFydovoaIKcHPStQqhylYy08y5Eg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T10:06:43Z"
  mac: ENC[AES256_GCM,data:hmoE2PniNtRQiEOO8wiRi4Ne5dNrifcf4tvBH6cX6vLyjH0V4BUcwvucL1URM+qJLugCZC5o8qIQK04TKEYfv3OzMDak9KuMV/zAgEgWQIBIYpO28dl0VgVEBnvHXtdu6lAEflecG75l0cp5BPXSuYkS70i4/EhuZq3hGzIUwKk=,iv:sIZQuNIK2fW+uq2pVGUI2v4hc7w4rxROAPovFuLkPNM=,tag:OKI2fvSe7nmF4SIttw5sOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
