route:
    app:
        hostnames:
            - openclaw.aknuk.dev
        parentRefs:
            - name: envoy-external
              namespace: network
              sectionName: https
        rules:
            - backendRefs:
                - identifier: app
                  port: 18789
secrets:
    secret:
        enabled: true
        stringData:
            ANTHROPIC_API_KEY: ENC[AES256_GCM,data:Zahj31d9O3sQyQybBlkzRiQznidelPmXlzd0GD8RLolBoz36SO8s4FsEU24ix+4Mo6LB0rP4pSIn59id2OaV/ZZeQ4RYLCyc31fXwbr7tM0b1PiSYAPWg8/5+KqSGIHDOhzO3FQL4Z+ouYuq,iv:om9nFvmUjZGaCi+15beL72WD3Q1uLnyBwf9oDn0JuEk=,tag:JGRHYe8zHH4U3sq/6a/E/g==,type:str]
            OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:/W+d73H5bWgtfrAi,iv:TkfF4EQh7OJMHnUXEyF8ReGAg0Z8tp10pnoX0+oa1gg=,tag:xzfUdnRIQ7jjVpV3kk2l6A==,type:str]
            OPENAI_API_KEY: ENC[AES256_GCM,data:vgx2fBzuc8TiMVerM6GCWbFX4RR/9EvsiEPvfvsanAb9xfE9B6JK71vYyvcFOna12/IaUyP6Sd/OVaOm2ZhoRQrXHa2mHs1WfwvwPmLSkfPXxy1P/f3U85BfvD449HwFcVJ5e8BJKZusqqOVHk2Rmn0Ub6oYBeBUcvXJAE1Y3RjG31C3zuZlOaUwB02ytA63noYM4FJ9m0kwC4e3F7kI7HOPn90=,iv:EevVBDrGkU+KTsbX2ak6O43lrmyRjaXWvv36U/Tw+y0=,tag:UwesmwOIddEs0h7NRfe4Mw==,type:str]
            GEMINI_API_KEY: ENC[AES256_GCM,data:xuEaPo5u6DmU0zkmXj2w57bXQAgbChfjsPcHw8OUTeyHucrXQ1GM,iv:MEEIRuZqujSaDacXtfqWKPE7Og794M8RJYYK9IfqxDg=,tag:sUWv9kngYs59zNWG1U1mEQ==,type:str]
            OPENROUTER_API_KEY: ENC[AES256_GCM,data:WdV3NtGlIir8Ai0z17YLp4NqkOssU50a6Et979YWBVArKA1neVm14hT8KkMkisvQ16nIwUCHiH8f28b4jqs/A9qkG3Gr4t+nsA==,iv:UIB1mGbyvv/JSpPK8pJn6N/2GgBkqTVrx6AlYYspoVQ=,tag:oYVQNMrVWmWHJo/bpEwalw==,type:str]
configMaps:
    config:
        data:
            openclaw.json: ENC[AES256_GCM,data:LkxcfehCmtgZ/TYJaiFcWg9EArpzXLwenBFkNyi8EPLEXWd5EUi/0cXEovhD90sh0pJra7VV62422Lvg1z2FpYVY1GsMiJZrpVtEFDz0ZcKs46HLrHcWOYGxEiGeDQR67sZqS1ENzX9earIjhBLvGOUQQfSFAwoin0itJ+Qy//M3R5BlPaLBNkFJMTztsu7JGMNkwEMLC3BZlD2az93x8ytAM+SjIZ3mbysUlQ8GuiULX6eHoLOMtCruF1rcqjcz5HsyP9oy4wi8291cgoBrom+Jxbu4pfQBUq4KxDzdqLBehpO0xaRdlFUZ4ZR8g32qG15wN4SnXIHcxZumVuKoK5+ix9yDkhm8zQ9zidsKz7lUCQqMawUn0epbjD92ltWxmI9L8GZlqn/LwwNXvbcQSb3hsfnWWGBOtaKdb21ihVkIkha180PqXUnoXt9I1ooeKn3w74AbhMgyzHCrOPQ1ufPe2OsvemxxyxS2v14/Dh0nHYVWTyZrfwrxGW1jXmnlbVBBhmV7kLZ9/DhdBNL1rUHcoRBc4v+BOxsxCksluAVetVuAUrFCCTgR8019mfNThhkezCr93s0pEkYSmWoiO0PwJ3lkXBp43dyGbWunDts5RShwTMc1+9/4PEKUWyKY2iC6ggOepVipebVQhFAMFqdnHLP1O46Us3LM,iv:sweFLkanG+nFHgigwWw7+Iv3oi2VEOiFPKtmU9lQTQE=,tag:ehHOWLNnYKMFEI9+OUt/yQ==,type:str]
            AGENTS.md: ENC[AES256_GCM,data:GHhS6hGGNtMs2FZW01CzIc7VZlkMtUMGlBj2GlRIg6U/qYIry6jSr08CPZVgiC7PpAd1jJQTfd8LYYhYXlTa7BVv/hLisjI/1/M=,iv:0sxH0V9zYKTCeXZY+h7CulDV8SNvvZzSb9gHUx7kjtc=,tag:6yrxY4dy8kxkqWhfeID8pw==,type:str]
sops:
    age:
        - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL1dOcHUwOVk4blovdzR6
            bnpXMklqaVM2eGFOY3NxNkNSQVNRRmNzZXg4CjVkRnNSQjR0QWl1Ym1kaUtNcEdC
            NHl1akg5MkVhakFrYjh3YnhFOThlTFkKLS0tIFU3dlRhT3FXeVMvbDdKMVVydExK
            WTUwK3JFdDFJNk5KZWhyc0xUdHlwUEEKfFhUq/SoPJ4tIowXSyqi5sVTVJ5OiaYm
            sI1ijBW+/2NinNNi5gbMZT7dK8aiW9OlzMFJZW1b7fazHI9C9D0kjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T20:42:51Z"
    mac: ENC[AES256_GCM,data:0keI26JAqHZ19QQRw77kjqBNL+3LAJNVvt4e7vNAgxpCBZWC87SfXUNnqXX/30+GAo307RxMDE1biwi+sjwLjHbT34kGrizwhLSoTNtCsGi5pqzyjGxeo57d9k6IAHqbZTBak3jYxbw37g/gPOH++TECCcYmnBKbjQNXlrjuUIw=,iv:aWt2DciVMdwev+35SHhLF4UN2B9RnYA/NwaoJaYyAx4=,tag:VrHEgdvosoFsVWHPRyOpDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
