image:
    repository: ghcr.io/openclaw/openclaw
    tag: 2026.3.13-1
credentials:
    existingSecret: openclaw-secret
chromium:
    image:
        repository: zenika/alpine-chrome
        tag: 124
openclaw:
    configOverrides:
        gateway:
            controlUi:
                allowedOrigins:
                    - https://openclaw.aknuk.dev
persistence:
    enabled: true
    size: 20Gi
    storageClass: nfs-shared
    accessMode: ReadWriteOnce
resources:
    requests:
        cpu: 100m
        memory: 512Mi
    limits:
        cpu: 2000m
        memory: 12Gi
podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: Always
    runAsNonRoot: true
    seccompProfile:
        type: RuntimeDefault
sops:
    age:
        - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL1dOcHUwOVk4blovdzR6
            bnpXMklqaVM2eGFOY3NxNkNSQVNRRmNzZXg4CjVkRnNSQjR0QWl1Ym1kaUtNcEdC
            NHl1akg5MkVhakFrYjh3YnhFOThlTFkKLS0tIFU3dlRhT3FXeVMvbDdKMVVydExK
            WTUwK3JFdDFJNk5KZWhyc0xUdHlwUEEKfFhUq/SoPJ4tIowXSyqi5sVTVJ5OiaYm
            sI1ijBW+/2NinNNi5gbMZT7dK8aiW9OlzMFJZW1b7fazHI9C9D0kjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T10:17:12Z"
    mac: ENC[AES256_GCM,data:MarDemdQPkqKDwW+voiuU1GiBeNdauW0ljB/UHpSVUf4pjoBmoDSax7qnROBbz19Xgxpo9YwbdzucdCoYSWNy02p9djeLa9bsg4Romx4B4vN8stMDCAulNsCqyraqJb4+u1DJPp5mt+LklP7fDjrejdARhWxrHdDeT7bnYFjAzE=,iv:nxho6XRtTEkOv4ND470uYhnSG1nUvzz0RXB/b1f+5Yk=,tag:kAZGazz6u+ufT9FOhBVEGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
