app-template:
  defaultPodOptions:
    annotations:
      reloader.stakater.com/auto: "true"
  controllers:
    main:
      containers:
        main:
          envFrom:
            - secretRef:
                name: openclaw-secret
  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      storageClass: nfs-shared
      accessMode: ReadWriteOnce
      size: 20Gi
      advancedMounts:
        main:
          init-config:
            - path: /home/node/.openclaw
          init-skills:
            - path: /home/node/.openclaw
          main:
            - path: /home/node/.openclaw
  route:
    main:
        hostnames:
            - openclaw.aknuk.dev
        parentRefs:
            - name: envoy-external
              namespace: network
              sectionName: https
        rules:
            - backendRefs:
                - identifier: main
                  port: 18789
