image:
    repository: ghcr.io/openclaw/openclaw
    tag: 2026.3.13-1
credentials:
    existingSecret: openclaw-secret
chromium:
    image:
        repository: zenika/alpine-chrome
        tag: 124
persistence:
    enabled: false
    size: 20Gi
    storageClass: nfs-shared
    accessMode: ReadWriteOnce
resources:
    requests:
        cpu: 100m
        memory: 512Mi
    limits:
        cpu: 2000m
        memory: 12Gi
sops:
    age:
        - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL1dOcHUwOVk4blovdzR6
            bnpXMklqaVM2eGFOY3NxNkNSQVNRRmNzZXg4CjVkRnNSQjR0QWl1Ym1kaUtNcEdC
            NHl1akg5MkVhakFrYjh3YnhFOThlTFkKLS0tIFU3dlRhT3FXeVMvbDdKMVVydExK
            WTUwK3JFdDFJNk5KZWhyc0xUdHlwUEEKfFhUq/SoPJ4tIowXSyqi5sVTVJ5OiaYm
            sI1ijBW+/2NinNNi5gbMZT7dK8aiW9OlzMFJZW1b7fazHI9C9D0kjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T16:11:44Z"
    mac: ENC[AES256_GCM,data:n2F+e2VLM48WyuZ578xPchubcH8FJM6Qi1VIiFLl8J9Fyn7FcmODcWrj5q08CPp7zoxKhdxQvNm1oQHkD6HzvBTd60d4CJJCCLtb6li2u4TYJD5mOKkdG4Z0+m7Fso1ZrepnKbPttYIXVQAQDu7LSm4TzDin38wAOH5begMRPj4=,iv:ko19X4LT2sredNxhnz7PshQlQQVCrLYfsas/JLiTRk0=,tag:lFRBIyGBz/t2HR9FxEt53Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
