---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tuppr
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/ajaykumar4/home-lab.git"
      path: kubernetes/apps/system-upgrade/tuppr
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/home-operations/charts
      chart: tuppr
      targetRevision: 0.1.6
      helm:
        releaseName: tuppr
        valueFiles:
          - $repo/kubernetes/apps/system-upgrade/tuppr/values.yaml
  destination:
    name: in-cluster
    namespace: system-upgrade
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
