route:
  app:
    hostnames:
      - echo.aknuk.dev
    parentRefs:
      - name: envoy-external
        namespace: network
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 8080
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaU2xja3YvcWdFbEhQZ2F6
        UFNIdFNVSzZiSklyY3ZydERQTjE0YkJXMTFnCmo2TkxDdkVpQzhpdElqeUpRaWhG
        QzFFQ2dQZi9uK2VCU2VJZVMrSUVmdGMKLS0tIGFXcXNnWDhqeDhLajZUWE9paXo5
        SW9OQkVVMllSczd2UE85L0MvQS8zZDQKyr1Z0ZwnNosf+nhV022oWDePK4lYiC7r
        oFiApUpWO0PzI6RAu9Esayjg4T8isD0mztDxoh6qP1T5ocPSoSRBmQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T11:10:20Z"
  mac: ENC[AES256_GCM,data:ge8o1fsoDBogz/wef2dwZ287J3h67sZGLKMxQozEXogydaDpm9qmXEGAEZRx/EYYx8pT9eJgAlCzbrrh649JDJaEgGP81VKkbmvEigcS5UzIUsBtqx8EBXTvcuL0V/zagrJlyxSqjbjFPfpwoT/VnDOMgPqvgqbIGVtgMyqruj4=,iv:FWAwkGYxBoXslBEK3tlw/K7gy8MJFC2R0YhrkNUw9m4=,tag:eODwXvgcfT6RaNLml5SIcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
