controllers:
    echo:
        strategy: RollingUpdate
        containers:
            app:
                image:
                    repository: ghcr.io/mendhak/http-https-echo
                    tag: 39
                env:
                    HTTP_PORT: 80
                    LOG_WITHOUT_NEWLINE: true
                    LOG_IGNORE_PATH: /healthz
                    PROMETHEUS_ENABLED: true
                probes:
                    liveness:
                        enabled: true
                        type: TCP
                        spec:
                            tcpSocket:
                                port: 80
                            initialDelaySeconds: 60
                            periodSeconds: 30
                            timeoutSeconds: 10
                            failureThreshold: 3
                    readiness:
                        enabled: true
                        type: TCP
                        spec:
                            tcpSocket:
                                port: 80
                            initialDelaySeconds: 15
                            periodSeconds: 10
                            timeoutSeconds: 5
                            failureThreshold: 3
                securityContext:
                    allowPrivilegeEscalation: false
                    readOnlyRootFilesystem: true
                    capabilities:
                        drop:
                            - ALL
                resources:
                    requests:
                        cpu: 10m
                    limits:
                        memory: 64Mi
defaultPodOptions:
    securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
service:
    app:
        ports:
            http:
                port: 80
serviceMonitor:
    app:
        endpoints:
            - port: http
route:
    app:
        hostnames:
            - echo.aknuk.dev
        parentRefs:
            - name: envoy-external
              namespace: network
              sectionName: https
        rules:
            - backendRefs:
                - identifier: app
                  port: 80
sops:
    age:
        - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKK2ZuUXdpRTNONW1BYVNw
            U0prMlFmZThtM0VleCtPblcxSi9qV1BpNmk0Cm1tR3d0Mkd0a0EwaDVIYk5CR1Yw
            T2NQQms2VFByVE5BRWhmQ2syM1NZalEKLS0tIERYbXgveWxIZytDT2JsNURVWkV4
            MUFQWTMva1h3ZmFrUkpTQ0tWR0Rzd0kKzClvyUn+OWzuGj+CbhogJuplIqkxusVR
            GFFLOPQEHYeGtzxTC/tnTr21CmrIj5ciXSeUxO2OBxKBujx4mtSTnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T06:17:21Z"
    mac: ENC[AES256_GCM,data:LZfglgY3k0Su+uVueC3rnEPWGbjfVMadfy/7NWSbtYbquCb5TyXw8UaSZYalQRv1OOfDBa4Hn8Wz/K92bkuZfEskdeHpB5BZiJcjy3+wTMzbOYP+xibzU/DshfAvDFWPsVMGskR9WvOqk/E2C9HuBw/KvTNo3Wtk9O4T3YVuYNE=,iv:HWEIucvkJ8ktY2zLei1SImINiGoKwvzoHhKPYX74bQ4=,tag:3hJlXyn37tPOv7FflPiTWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
