apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ETs4/uOVO8Yd,iv:U1gCsSLAmh5FPJj6KtoEJq2V7B+WOFmNoBMGGWnoNpw=,tag:aYJqQWR9RYveWvVLI0T/gA==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMkJmZFZMYjlyM08vRERr
        REIxNnhMbkVQNDY2MHRrRGgzRktwR3BGa1ZRCjhsRUxJWDRueXpSMFI4NTRLT1pv
        UEpuU2p6dmVkTnBJdG9HNGQvVU9QUjgKLS0tIEFWQ29WM29yQVNwcmJORzQ1SlM5
        Vmd1VWx2YWdJZFZGRWlNM0cxdW1ncncKBMjEgGEPHuMtHHQFkWboy3o9t0/B4AjX
        NxHPzYQAvh30MQoJzHqEof6Zb2vO6KraKi6Xz+N3X9wioBVcnzbutg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T10:06:43Z"
  mac: ENC[AES256_GCM,data:avr6axT4QMV4GjVNMyZQ2ub4YGFQUCmiCYqNOzuJGTUToqsg2IG7Vjtbk2gS+4UGAysAQjMsUEFb49Bf2ypjzSfh74Uc1YbbnjgcyD3CChnY2hemPGL7FNN0fwr0Zbs90PqAIZJiLWxaKZ2VxN/iIec1MuyYxgu4spQ6XtZ1QAw=,iv:iAyjrESa/eR8gmUaLWvSi9EFwXWu+mI5ITouX+BTvJk=,tag:MPjo9TTdxRXxqGRNh4M+Xg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
