fullnameOverride: cloudflare-dns
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns-secret
        key: api-token
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --gateway-name=envoy-external
triggerLoopOnEvent: true
policy: sync
sources:
  - crd
  - gateway-httproute
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
  - aknuk.dev
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: cloudflare-dns-secret
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ajhKK0wwT3FJQk1hOVBu
        N1VleVJCeE4vN3h3N0ZHejZkb05JOC9zemc0CmsvamdOK2cyUUVGRzRUSVJCekRm
        LzdocmEzSGJ2a2ltTkJoM1hoY2ZjSzgKLS0tIGRLNG5nc3NTU2h0MU9aaUE0TlZ1
        NFRxQk5RZWU4L0Zyd1hZQzlLeE5yU28K/yFETsMTh1F8ePVu1KYbYHjEkNv7pm+R
        B/0OfJ1RUmfT4LUBgVKjqaSyqMF2o2cllkmpxE6Y7s03RVXnA634XA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T07:17:04Z"
  mac: ENC[AES256_GCM,data:mNSMrJZMv292LMbfzccTnCQKe96CnTUNs7fmFCNoFC2GKOhU184ZscGuKbcN2RYFvtswPsigg1SHvVUNAQ+//T05SjHjvdso0U9GAHA1XGAgMTQYn7m1yTPpcYuIVHpHVYzG/RzssChA7SzEM8nx4vcOgEzNfuYAN9fm4lfCgbI=,iv:ot2zjqCNesbTdjcEDRpv0o9I7qNBO4lHJFEm+AO0XDM=,tag:B/s9koPOVMJ5JVcNIYEJFw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
