fullnameOverride: ENC[AES256_GCM,data:4/fPyRbYg+rhnUY/xt4=,iv:tiz+LBvxDn5szmONdPgBdX59JzG+ndC88fO2dbydCWs=,tag:+MmvrPelWnSYMS2yK9davw==,type:str]
provider: ENC[AES256_GCM,data:+YV2dD81ZyCq9A==,iv:ngBOjK16Gw5YVUV9im1iztoVd1Xag4btqA9wm9wPo7Y=,tag:vzujE90/oXYSIcWf4eO02A==,type:str]
env:
  - name: ENC[AES256_GCM,data:ze4xkXmfpsmlOgak,iv:YYz3dBLadongLnELiUDxbGiYfbXooWLMkX5mOLCB5W8=,tag:9WetLKeqiRbNjn5VgX+NOg==,type:str]
    valueFrom:
      secretKeyRef:
        name: ENC[AES256_GCM,data:4ipasp2GhzPxw6ST0SAXVeliZ9Jc,iv:tTMWkDr/7VYbdhJ7xnIc3Whpjy2Deu1RTnTkRJQWKBs=,tag:xeGESea1DeRSiF1sdz3gOg==,type:str]
        key: ENC[AES256_GCM,data:QyLk2yMqdcTs,iv:nSgvuK3D9EyFeZ6Yv+uUlMcAzMJEey13j+lfs7ECyVA=,tag:fAht5//FFLP9W+gPp3jVHg==,type:str]
extraArgs:
  - ENC[AES256_GCM,data:YGxMZE7bSs3iG2DzRNr4Ag++4TIpe4zbbow18F7gv48VkAqM9m0=,iv:lAML4ilhlLb27R2CASD7MNqaOHCXb7FAotzrNyxnE3o=,tag:oQPdUmPSmlIsAFUUF7bkcg==,type:str]
  - ENC[AES256_GCM,data:fMj2qv3dYarsxNfAF/DNDjCtnFE=,iv:/i/KufqPh30OMhHYszZTtT1Xi6Ts4zDvefXHTXipOhs=,tag:pQbrtPsXH2XidK3aJj+NUA==,type:str]
  - ENC[AES256_GCM,data:q1Gh+GhTeLVmxbzRnkln960TiLNqd2LVCVPH/NkkCepdkcSCxRiKsjG/64iM2fu0rYa8,iv:t5KThg/CJT9JIQ8AN8z1iwEbM6uBHyzuUyM82ygLL98=,tag:+SD7HqHTH7sLP3WK2XI7dA==,type:str]
  - ENC[AES256_GCM,data:4zoi+Z2IlD6y+0k7bh7D84d7RG6zoxXY4+TlaCI=,iv:Gf/9krjCCgSN/DzttTPmm4mD7uFhliQna0r6obRudU8=,tag:VMRBUK1M/GM+wPjBo9RjUw==,type:str]
  - ENC[AES256_GCM,data:JP5r3m81+JWzw8IC8xEBRRY4zXbvdu20iBOTQiA=,iv:obag9BIVhznpqKV6Bo2lIXsj8g1/dDrLG+dTbUADTAo=,tag:INBNA2Mj3Up9GC4FujQJng==,type:str]
triggerLoopOnEvent: ENC[AES256_GCM,data:XWsqvA==,iv:OMZWiIEml0u54rs+yNkYb1a+gHl2CWa6m4ysDeTAwO0=,tag:OOf5a4esuGSltj1QvH6ACw==,type:bool]
policy: ENC[AES256_GCM,data:Fdzjug==,iv:eec9kWS0S9FuLykfdHffktz/8KpizhjGBh+ecE55CvI=,tag:Nwhch8iPxswYUa+E5uNuWA==,type:str]
sources:
  - ENC[AES256_GCM,data:ZUpH,iv:j6UgWKf17q2ADPo+dr/JKr6iLcVGC1eXMUAKxSO7Ch8=,tag:zFhaMO9TCKCqs8fxswSimw==,type:str]
  - ENC[AES256_GCM,data:R+B6BxL/RTQQmzF+IwIINyw=,iv:u85uAfKZV03E8eE1DPQy0dNkL7XG06txpK03KLQET5s=,tag:AJ0RVOoDoyqctvX4rIqQzQ==,type:str]
txtPrefix: ENC[AES256_GCM,data:y9DoOg==,iv:7o2voy1+7GoHc6cMnIzrhLIGlt0AR6nK2KlnbQV+sX0=,tag:lWRJeIOsMF4AbP1/Af1rjg==,type:str]
txtOwnerId: ENC[AES256_GCM,data:Stddy3Rw/g==,iv:thPcy0WnZPpwwm4sq/CEqspeXMhPorK/UYLNaT7KVIw=,tag:0B72SSCUbN8fpRwHz/FU1w==,type:str]
domainFilters:
  - ENC[AES256_GCM,data:kjjlbWMVH1J7,iv:x5G8uJxUvcN27sSR1Cw9TRu8sOJHBhAeJwSGMapgHsQ=,tag:7njoIZ/ooAaXZgTGHkZL7A==,type:str]
serviceMonitor:
  enabled: ENC[AES256_GCM,data:/OUV9H4=,iv:Zs1DbgmWCJk2l05+LcjJQhfY/znDBQGqxuJyhKUfzOk=,tag:6S5vPzecAKGoKDcwij/lzQ==,type:bool]
podAnnotations:
  secret.reloader.stakater.com/reload: ENC[AES256_GCM,data:fuTiCmELyvCbt6x4dI3viKdq6toL,iv:68M1aK6CQTCXOWSQS7N2ZuTy+gO/pquGfLPNAB/xX0E=,tag:dFsuNNukgx5aXAzHgUFnyg==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScllDenFjbktxcXBCcTZh
        bTNLSTN6L3F2b0RsTjRKTkFoVzR1YlgwU0VJClJ5L3ZLZldadVN3UGxHL1QxSTVH
        a0pLMzNLb0hwckt1dFd2S3hxWGhOUmsKLS0tIHU1aWNsQXg5N1Azbmpxb1h1V3A5
        Q2tQOXhoclNkdFRqcWxuK2pyb1Q1ZFkKLuc22GeOUzQBU8LDwqxJlPFI+ds4cryJ
        y1awd3XSNpuAhSVUeaXxg92sm/SMwDRxU1h1fONsxpWNXZ5QQ6J3bQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-01T18:23:21Z"
  mac: ENC[AES256_GCM,data:FNw8hItNL2K06fvuxaiot/ix8iMqEr3sCMcch1Macbm1QX8xoDczKD3z6MEJIreTY9xcuBez9QzNhLYQHb4gfTAdqym3XTk7W6vI9n+22nHiVSG52l+jXPfQ3gaf/aTT2TxKw28QSy5gJn0VJSEoBpFILwqevqM3CAdCnD3dPGI=,iv:+qNT7hPbZZCA7y9PyFlLRgX9IhZx1VSurY0NDSrLPmU=,tag:BpsVt7Ri6aHCIRCrvPg87w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
