fullnameOverride: cloudflare-dns
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns-secret
        key: api-token
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --gateway-name=envoy-external
triggerLoopOnEvent: true
policy: sync
sources:
  - crd
  - gateway-httproute
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
  - aknuk.dev
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: cloudflare-dns-secret
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNkk0TlVBZ1BhTGcxSWE5
        UnF5T2pnNVdhTDlZaGsxYnM2bm9EYUFFb0NrCk1IVEJKRlE5R1p2SFVjdFErWW9a
        Mjg2c1NXbnl5NzNqNkVHMGVWeFJmTXcKLS0tIGQ0UHZLTzJGY09jQU54ZDlNYjJC
        RDBzcFcwK2djT00zZlNpdUFPY09TU3cKNY4qpOPGC2S1mcW3kjpZiXH9O7n07oYL
        GKg5WH5bEyOA8mVWPBTCBiUa494NNl9ZWQb2dhtczprzWjrb2pfKcg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T11:02:57Z"
  mac: ENC[AES256_GCM,data:j0IIlwN+DnO9fesfE/VvBVJOC68gK3PjM+Hzg89Ak7nE0PbAqFTvG+rn8foqOqeNGWbHYM9mPcRy+MbowqQsELu5l0uVnT7b5adj3/lwgqjx0Ujk8rB/gNmQ/yvyGkaOSJmbb9haWEHIhxIWFooKcManyyn3S/whooBmTpyKuP8=,iv:HXQDMVGBdIxAdwqkFo9dwcGG9yN8ruzzn2XOXA9eMGM=,tag:waifgh9CHJEjaNDnlnSmpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
