apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: csi-s3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: csi-s3-secret
    template:
      data:
        accessKeyID: '{{ .aws_access_key_id }}'
        secretAccessKey: '{{ .aws_secret_access_key }}'
        endpoint: 'http://s3.aknuk.dev'
        region: 'eu-west-1'
  dataFrom:
    - extract:
        key: bc7ddb89-0509-4464-aa2c-b42801206116
