apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-s3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: rustfs-s3-secret
    template:
      data:
        key_id: '{{ .aws_access_key_id }}'
        access_key: '{{ .aws_secret_access_key }}'
  dataFrom:
    - extract:
        key: bc7ddb89-0509-4464-aa2c-b42801206116
