apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:y4iT73Y+h/o+la6x/IdlZXsBiAlRR37InHbNtHExvMU=,iv:xqG0tv+7abTUbVhP4BhtP+L2pzyDOgdv0AN1/MgTRD4=,tag:0p8XIoCanX/KLQeUF+bEQg==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTjRyclhsN3FnOHhYK3Fv
        bzBaSlVjR1pXS01rcTB2YURJVlpyQlFOaWtBCmEvUG1pQjA3SGVWSWt3djB4b3Q1
        RHdsQVN2ZW1xZDYvVUpsQ0paUnU1VW8KLS0tIDJ4UUlLZWx4QmIweEV3UFdKYWw3
        ck1NZko0dGlQTzRtTlVubGFLT25OWTgKl22TTEyUORRfylFg0po8oRhY+7IY/wfN
        sjKeW5zjif185haBKV/1IfNxHJJh3BThIFaXZBJFVeVYB4INW0+rNw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T10:06:43Z"
  mac: ENC[AES256_GCM,data:JZSTiJa8S63l6y05tej8VWbZrZd02+E/o4JE64fnlELRTFTKLHGnzV/PCcq2rZxhDbaXuH8bjWDZ0dILYJF/COizrLUL1vUJngU+G5sG40GaBVbNuMw/kXh4FFM44bPlbDB7FV99chJFVgEalqipzxZuFN0GkJ2X2z+HvL8UY1A=,iv:+7a0xA8JIjL+/asEvR4RM9XfRcB8Jg3yvYPM9LrslyY=,tag:hBNves7/0om8uCbDF4LgBA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
