apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: ENC[AES256_GCM,data:iUFB,iv:638Eetj+WIAb+5cESSHM0soZkcnfQWWAB0B2G5VTvk4=,tag:UwguuOnsYmdRSuAxNqIxqA==,type:str]
  url: ENC[AES256_GCM,data:+CFhNhFOzIR5cEtOeTpL4rUi5SODNfgXqbfBAnQ78xZME9+I5Ub/DVpZ,iv:DvcgYappZ8wXgRZvwYS/K1/DA7D42aW6icMY5/+qm/M=,tag:00CmCUw+tphWUjD5nJtVDg==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQWZycGdaeUFudFFjMXNa
        dXZ1KzZ5bWh4dzZoMkJaZTVZcEthVTFna0FFClFqQWlVakVVOWIrNklCdVlweFRv
        Wml0TFMvM2tTWURnM1A0RVlacG96dlUKLS0tIERsWXlqM3Q2OG5tL1ZORVk5Zi9v
        U3MrN3NNNEtuck0zbVVxYVNlVE9sRGMKwoVzKaWmYB2Juw43jKFIi18m0Y68ZMbq
        hqUkiRlVzJp5ptE8Y1bJgCnYWJsWw27BaRvgVkihqsFyBbBeIBFn0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T09:57:49Z"
  mac: ENC[AES256_GCM,data:CAk40VLex4DHrQgffXk+ElTiqYgh4HMYfCq9Mc7K1Xc/a9r/w4IgMUy0kk+oMPr0uHJPy2mK/NfukHuhrILVyNeWUwyEgDd4IG952HSplGqz9rCPsiba0dmvpubfcEXjwPHBKXiwQBpQM5ItZZhkpuAZeFdB+VjO5YX3Eey+6DU=,iv:pJOaNNfAkI1CqxF35/wSrp1R6Sbj7o+EvvUbr70KQbI=,tag:5CiEMR5Jto5JNkciLuFx+w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
