apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: ENC[AES256_GCM,data:/iKD,iv:f0yoKpBqt2HU2uDH3oB5P3I+O/9pDWjWg3GIatr130Y=,tag:UHgPrJ+kuAva/DZ5yhylmw==,type:str]
  url: ENC[AES256_GCM,data:FpRHKG272yqTP/cuCIRbmpY34vLfJFOtFb8cM6A3mFYpKe3CMARSa99f,iv:170A376kDxy73XmHgUs50bVBNjWAIOSCEZlJXbVAUNw=,tag:sX+LHiJdrQcXaeVY7LLB8g==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMGh0dVQvK2xxSDJwdGtx
        a3IwZnNzTHZYN1JvZkd5K1ZJNXk0djBIcVhNCldaSGthSFJvSTIyV3pnaUtYejdq
        NHlLelFZVSs2S1Z1MXp5YkNFVnRmVzAKLS0tIHhTTUJrYk1lTCtVWUUyTkNvVE5R
        N0JaV1RvMVN6Zjc0dVFGYzZlWjdnUm8KjjZsvLjdU0un+1h399OvVhRe8SpfQl+r
        se4dFH5otFwOtw9UEaqNHXMkvGKq+ieNnpLmfYbuUaDiZwgaBtsWMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T18:31:15Z"
  mac: ENC[AES256_GCM,data:QCTyrVuGcT04JgRlkDQMQn3GhK56Y5sj1PWr0r1a8r3NZGkxQBAUxVmwvevmVxZQuUIIhBvORoORf5/CXsrEGVVbj8wEKOcU/Eh8eJGPM/pNgzSNVxmivh9nbr4db1PAdyptkZzt3gHN1RuZQyf/oPx2iAMW/CTxpycFfRaOO0o=,iv:z3NJ28pfk3RnxJy6jeGFrYumB4JGJRn84WV7EXFlsnQ=,tag:+I206IsB+g15QsJtdzWVWg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
