apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: ENC[AES256_GCM,data:DTf9,iv:ccEwvzZt9mLNdKLpBzemrPxtMDf+CrUws1OZtmISBhY=,tag:63EmFKkE2TG7wWyylZczcQ==,type:str]
  url: ENC[AES256_GCM,data:pj5s/ct0RjR2LCXw3RmjyXFUyyuoBNuYd5OLLxhY6RGCqYADtDBIpcr5,iv:Ic7SzfUxCqipcBhgb3ypWML644d+mysnUviEKJSQNMM=,tag:4kjuoM6R/7JA3bykD3hl6Q==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSEVNWmVuWGVNMnBRUzlN
        VVk2cFpQUjNpLzBlOElmeWJOQmFwaWRXVmdzCm9ZUUwzVXQzZHYrbm16d0RReUUw
        YUlsRDVnYS92cEdUR3l1ZU1MT1B2NDgKLS0tIDUvMTl4UEF2LzAxRGF2OEpDSTZ3
        MG9GTlYvNEhYRHBnL09tMDVTa2duWTgKBicR6/ldUi8w38rKZ3SWhmO4yXwZ+Mrn
        nfZJhgrhypbtxy22hFphLTxJOh+IVV4Tc7OWlNz2ltRqKaXkiSmvuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T10:47:45Z"
  mac: ENC[AES256_GCM,data:MHExwfdQUXiIFKyt41KNgbbOlgPDV0yXUt0gWTHK73A9azypKjx1GR+d80d/ulyya2XPx3KOS3VMGU7q6JDxdQTVp1dwqDQyEXdaWoNx0O66n91+8otfwpZvm/X1mFZXgIHeDFlMhI8SFYU0xRuD1Ll5M4JSHix+geLMqrJQwFk=,iv:ZALRU7Kt/8eltr/t9xGL2f79titE92+LVJN4Lcfx5II=,tag:Ku8JDrczw31h9YMEv0LRWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
