---
- name: Deploy ArgoCD 
  hosts: control_plane
  gather_facts: false
  become: true

  vars_files:
    - ../../config.yml

  environment:
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    PATH: "~/go/bin:{{ ansible_env.PATH }}"

  tasks:
  - name: Add ArgoCD Helm repository
    kubernetes.core.helm_repository:
      name: argo
      repo_url: https://argoproj.github.io/argo-helm
      state: present

  - name: Deploy ArgoCD Helm chart
    kubernetes.core.helm:
      name: argocd
      chart_ref: argo/argo-cd
      release_namespace: argocd
      create_namespace: true
      update_repo_cache: true
      wait: yes
      timeout: "{{ helm_time_out }}"
      state: present
      values:
        configs:
          params:
            server.insecure: true
          cm:
            statusbadge.enabled: 'true'
            resource.customizations.health.argoproj.io_Application: |
              # Modify this section according to the supported YAML syntax or Helm template syntax
              # This conditional logic might require a different approach within Helm templates
            kustomize.buildOptions: --enable-helm
          secret:
            argocdServerAdminPassword: "{{ argocd_server_admin_password }}"
        server:
          service:
            type: LoadBalancer
            loadBalancerIP: "{{ argocd_load_balancer_ip }}"
            annotations:
              external-dns.alpha.kubernetes.io/hostname: "{{ argocd_dashboard_domain }}"
              external-dns.alpha.kubernetes.io/ttl: "120" #optional
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - "{{ argocd_dashboard_domain }}"
            tls:
              - secretName: argocd-tls
                hosts:
                  - "{{ argocd_dashboard_domain }}"
            paths:
              - /
            annotations:
              external-dns.alpha.kubernetes.io/hostname: "{{ argocd_dashboard_domain }}"
              external-dns.alpha.kubernetes.io/ttl: "120" #optional
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          ingressGrpc:
            enabled: true
            ingressClassName: "traefik"
            hosts:
              - "{{ argocd_dashboard_domain }}"
            tls:
              - secretName: argocd-tls
                hosts:
                  - "{{ argocd_dashboard_domain }}"

  - name: Issue Let's Encrypt certificate
    kubernetes.core.k8s:
      definition:
        apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: argocd-certificate
          namespace: argocd
        spec:
          secretName: argocd-tls
          dnsNames:
            - "{{ argocd_dashboard_domain }}"
          issuerRef:
            name: cloudflare-issuer
            kind: Issuer
            group: cert-manager.io
      state: present

