---
- name: Deploy cert-manager and Let's Encrypt for Cloudflare domain
  hosts: control_plane
  gather_facts: false
  become: true

  vars_files:
    - ../../config.yml

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    PATH: "~/go/bin:{{ ansible_env.PATH }}"

  tasks:
  - name: Add Jetstack Helm repository
    kubernetes.core.helm_repository:
      name: jetstack
      repo_url: https://charts.jetstack.io
      state: present

  - name: Deploy cert-manager Helm chart
    kubernetes.core.helm:
      name: cert-manager
      chart_ref: jetstack/cert-manager
      release_namespace: cert-manager
      create_namespace: true
      update_repo_cache: true
      wait: yes
      timeout: "{{ helm_time_out }}"
      state: present
      values:
        installCRDs: true
        replicaCount: 3
        extraArgs:
          - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
          - --dns01-recursive-nameservers-only
        podDnsPolicy: None
        podDnsConfig:
          nameservers:
            - 1.1.1.1
            - 9.9.9.9

  - name: Create secret with Cloudflare API token
    kubernetes.core.k8s:
      definition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: cloudflare-api-key-secret
          namespace: cert-manager
        data:
          api-key: "{{ cloudflare_api_key | b64encode }}"
      state: present
  
  - name: Install Cloudflare DNS cert-manager issuer
    kubernetes.core.k8s:
      definition:
        apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: letsencrypt-issuer
          namespace: cert-manager
        spec:
          acme:
            email: "{{ cloudflare_email }}"
            privateKeySecretRef:
              name: letsencrypt-issuer
            server: https://acme-v02.api.letsencrypt.org/directory
            # server: https://acme-staging-v02.api.letsencrypt.org/directory
            solvers:
              - dns01:
                  cloudflare:
                    email: "{{ cloudflare_email }}"
                    apiKeySecretRef:
                      name: cloudflare-api-key-secret
                      key: api-key
                selector:
                  dnsZones:
                    - "{{ cloudflare_domain }}"
      state: present

  # - name: Install letsencrypt issuer
  #   kubernetes.core.k8s:
  #     definition:
  #       apiVersion: cert-manager.io/v1
  #       kind: ClusterIssuer
  #       metadata:
  #         name: letsencrypt-issuer
  #         namespace: cert-manager
  #       spec:
  #         acme:
  #           email: "{{ cloudflare_email }}"
  #           privateKeySecretRef:
  #             name: letsencrypt-issuer
  #           # server: https://acme-v02.api.letsencrypt.org/directory
  #           server: https://acme-staging-v02.api.letsencrypt.org/directory
  #           solvers:
  #             - selector: {}
  #               http01:
  #                 ingress:
  #                   class: traefik
  #     state: present

  - name: Issue Let's Encrypt certificate
    kubernetes.core.k8s:
      definition:
        apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: cloudflare-certificate
          namespace: cert-manager
        spec:
          secretName: cloudflare-tls
          dnsNames:
            - "{{ cloudflare_domain }}"
            - "*.{{ cloudflare_domain }}"
          issuerRef:
            name: letsencrypt-issuer
            kind: ClusterIssuer
      state: present