---
- name: Install Traefik
  hosts: control_plane
  gather_facts: false
  become: true

  vars_files:
    - ../../../config.yml

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    PATH: "~/go/bin:{{ ansible_env.PATH }}"

  tasks:
  - name: Add Traefik Helm repository
    kubernetes.core.helm_repository:
      name: traefik
      repo_url: "https://traefik.github.io/charts"
      state: present
    
  - name: Deploy Traefik Helm chart
    kubernetes.core.helm:
      name: traefik
      chart_ref: traefik/traefik
      release_namespace: traefik
      create_namespace: true
      update_repo_cache: true
      wait: yes
      timeout: "{{ helm_time_out }}"
      state: present
      values:
        metrics:
          prometheus:
            service:
              enabled: true
        providers:
          # Enable cross namespace references
          kubernetesCRD:
            enabled: true
            allowCrossNamespace: true
          # Enable published service
          kubernetesIngress:
            publishedService:
              enabled: true
        service:
          enabled: true
          type: LoadBalancer
          spec:
            loadBalancerIP: 192.168.1.201 # this should be an IP in the MetalLB range

  # - name: Issue Let's Encrypt certificate
  #   kubernetes.core.k8s:
  #     definition:
  #       apiVersion: cert-manager.io/v1
  #       kind: Certificate
  #       metadata:
  #         name: traefik-certificate
  #         namespace: traefik
  #       spec:
  #         secretName: traefik-tls
  #         dnsNames:
  #           - "{{ traefik_dashboard_domain }}"
  #         issuerRef:
  #           name: letsencrypt-issuer
  #           kind: ClusterIssuer
  #     state: present

