---
- name: Install Traefik
  hosts: control_plane
  gather_facts: false
  become: true

  vars_files:
    - ../../config.yml

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    PATH: "~/go/bin:{{ ansible_env.PATH }}"

  tasks:
  - name: Add Traefik Helm repository
    kubernetes.core.helm_repository:
      name: traefik
      repo_url: "https://helm.traefik.io/traefik"
      state: present
    
  - name: Deploy Traefik Helm chart
    kubernetes.core.helm:
      name: traefik
      chart_ref: traefik/traefik
      release_namespace: traefik
      create_namespace: true
      update_repo_cache: true
      wait: yes
      timeout: "{{ helm_time_out }}"
      state: present
      values:
        service:
          spec:
            # Set load balancer external IP
            loadBalancerIP: 192.168.1.201
        providers:
          # Enable cross namespace references
          kubernetesCRD:
            enabled: true
            allowCrossNamespace: true
          # Enable published service
          kubernetesIngress:
            publishedService:
              enabled: true

  - name: Apply default header
    kubernetes.core.k8s:
      state: present
      definition: |
        apiVersion: traefik.containo.us/v1alpha1
        kind: Middleware
        metadata:
          name: default-headers
          namespace: default
        spec:
          headers:
            browserXssFilter: true
            contentTypeNosniff: true
            forceSTSHeader: true 
            stsIncludeSubdomains: true
            stsPreload: true
            stsSeconds: 15552000
            customFrameOptionsValue: SAMEORIGIN
            customRequestHeaders:
              X-Forwarded-Proto: https

  - name: Generate hashed password
    ansible.builtin.shell: htpasswd -nb {{ ansible_user }} {{ ansible_sudo_pass }} | openssl base64
    register: hashed_password_output

  - name: Set variable with base64-encoded password
    set_fact:
      traefik_dashboard_secert: "{{ hashed_password_output.stdout }}"

  - name: Apply dashboard secert
    kubernetes.core.k8s:
      state: present
      definition: |
        ---
        apiVersion: v1
        kind: Secret
        metadata:
          name: traefik-dashboard-auth
          namespace: traefik
        type: Opaque
        data:
          users: "{{ traefik_dashboard_secert }}"

  - name: Apply traefik Middleware
    kubernetes.core.k8s:
      state: present
      definition: |
        apiVersion: traefik.containo.us/v1alpha1
        kind: Middleware
        metadata:
          name: traefik-dashboard-basicauth
          namespace: traefik
          labels:
            app.kubernetes.io/managed-by: Helm
          annotations:
            meta.helm.sh/release-name: traefik
            meta.helm.sh/release-namespace: traefik
        spec:
          basicAuth:
            secret: traefik-dashboard-auth

  - name: Apply Ingress dashboard
    kubernetes.core.k8s:
      state: present
      definition: |
        apiVersion: traefik.io/v1alpha1
        kind: IngressRoute
        metadata:
          name: traefik-dashboard
          namespace: traefik
          annotations: 
            external-dns.alpha.kubernetes.io/hostname: "{{ traefik_dashboard_domain }}"
            external-dns.alpha.kubernetes.io/ttl: "120" #optional
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
            kubernetes.io/ingress.class: traefik
        spec:
          entryPoints:
            - websecure
          routes:
            - match: Host(`"{{ traefik_dashboard_domain }}"`)
              kind: Rule
              middlewares:
                - name: traefik-dashboard-basicauth
                  namespace: traefik
              services:
                - name: api@internal
                  kind: TraefikService

  - name: Issue Let's Encrypt certificate
    kubernetes.core.k8s:
      definition:
        apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: traefik-certificate
          namespace: traefik
        spec:
          secretName: traefik-tls
          dnsNames:
            - "{{ traefik_dashboard_domain }}"
          issuerRef:
            name: letsencrypt-issuer
            kind: ClusterIssuer
      state: present

