---
- name: Install Traefik
  hosts: control_plane
  gather_facts: false
  become: true

  vars_files:
    - ../../config.yml

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    PATH: "~/go/bin:{{ ansible_env.PATH }}"

  tasks:
  - name: Add Traefik Helm repository
    kubernetes.core.helm_repository:
      name: traefik
      repo_url: "https://helm.traefik.io/traefik"
      state: present
    
  - name: Deploy Traefik Helm chart
    kubernetes.core.helm:
      name: traefik
      chart_ref: traefik/traefik
      release_namespace: traefik
      create_namespace: true
      update_repo_cache: true
      wait: yes
      timeout: "{{ helm_time_out }}"
      state: present
      values:
        additionalArguments:
          - "--metrics.prometheus=true"
        metrics:
          prometheus:
            service:
              enabled: true
        service:
          spec:
            # Set load balancer external IP
            loadBalancerIP: "{{ traefik_load_balancer_ip }}"
        providers:
          # Enable cross namespace references
          kubernetesCRD:
            enabled: true
            allowCrossNamespace: true
          # Enable published service
          kubernetesIngress:
            publishedService:
              enabled: true
        dashboard:
          # Enable dashboard access
          enabled: true
          domain: "{{ traefik_dashboard_domain }}"
          auth:
            basic:
              username: "{{ ansible_user }}"
              password: "{{ ansible_sudo_pass }}"
          # Configure dashboard Ingress
          ingress:
            enabled: true
            tls:
              enabled: true
              secretName: traefik-secret
            host: "{{ traefik_dashboard_domain }}"
            path: /dashboard

  - name: Create Traefik IngressRoute
    kubernetes.core.k8s:
      definition:
        apiVersion: traefik.containo.us/v1alpha1
        kind: IngressRoute
        metadata:
          name: traefik-dashboard
          namespace: traefik
        spec:
          entryPoints:
            - websecure
          routes:
            - kind: Rule
              match: "Host(`{{ traefik_dashboard_domain }}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
              services:
                - kind: TraefikService
                  name: api@internal
          tls:
            secretName: cloudflare-tls
      state: present