apiVersion: v1
kind: Secret
metadata:
    name: renovate-oidc-secret
stringData:
    client-secret: ENC[AES256_GCM,data:Ns0AVM7sbN8V3uWYTIDmWnyzS6NnuG5Bxqs5/TVHXFCRB0XNWfWMobwMi3V7J2RPbKsclYUSUxfE9so9xPMfZ284sW54L1/+dF8j17TFTwVUphC6tfjs0m5lJMH9yBfBfJ9gT8K6VBVCoqb2u4kfGnBCXuP/zJkxoMr4o36vRjM=,iv:lxm0LizO9sSfYhNJ/s3QDK+PXItvOWqPjNyhrKtyCHk=,tag:eHerLalfS1NH0lTAstRSxg==,type:str]
sops:
    age:
        - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQ3NqNzZ0eUhibEFJSHNk
            RU5uTzUrV3RPQ3JNMk5SdDNodGs4MzBMUEVRCjhBMUhpOS9XeDl6WlpOd2tkNFg2
            emtwRm1TRHR0bW9EelZvaWFiaGJuazgKLS0tIHBicDRYWEQ4Z2tPUGN4QUZzeHBS
            SWxJRWtyakVrYy8zRkZEN2N5TEhZZ1EK2vg5i+MxDfAUZxwQAd2h/eGd1xOl37LQ
            FDB/CxiNHOw443w0SpM2ZiUeHvgVkHVeiqDQYnNZ6x7twLiMCp68zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T13:59:59Z"
    mac: ENC[AES256_GCM,data:Na/yGbpo0o4SLAZ4mQC+4gqad3gXHylDFkXeuEG09gzPDzsggknvAMg/MKaDueVVMjzBca9tiZkoXt7hDKkyVK2113mOwqDV+j47IpxekfOWM+vIoWWQlRGBAn5RuA+vBm9ohE8N2ch0Fxn3P3mUv2Vxv1TPjtxEEfB55BSwvv8=,iv:VjjFR82g/NAiLIH+kB5/MvrbUCGDKGBiCA8HcmP0ZZ0=,tag:pO3B2OBtAkqcKR7A3fIr9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
