---
- name: Download environment check script
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/longhorn/longhorn/{{ longhorn_version }}/scripts/environment_check.sh"
    dest: "/tmp/environment_check.sh"
    owner: root
    group: root
    mode: 0755

- name: Run environment check script
  command: bash /tmp/environment_check.sh
  register: environment_check_output

- name: Fail if environment check fails
  fail:
    msg: "Environment check failed: {{ environment_check_output.stderr }}"
  when: environment_check_output.rc != 0

- name: Delete environment check script
  ansible.builtin.file:
    path: /tmp/environment_check.sh
    state: absent
    
- name: Create manifests directory on first master
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']

- name: "Download to first master: manifest for longhorn-iscsi-installation"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/longhorn/longhorn/{{ longhorn_version }}/deploy/prerequisite/longhorn-iscsi-installation.yaml"  # noqa yaml[line-length]
    dest: "/var/lib/rancher/k3s/server/manifests/longhorn-iscsi-installation.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']

- name: "Download to first master: manifest for longhorn-nfs-installation"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/longhorn/longhorn/{{ longhorn_version }}/deploy/prerequisite/longhorn-nfs-installation.yaml"  # noqa yaml[line-length]
    dest: "/var/lib/rancher/k3s/server/manifests/longhorn-nfs-installation.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']


- name: "Download to first master: manifest for longhorn-{{ longhorn_version }}"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/longhorn/longhorn/{{ longhorn_version }}/deploy/longhorn.yaml"  # noqa yaml[line-length]
    dest: "/var/lib/rancher/k3s/server/manifests/longhorn.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']

- name: Generate Secret manifest to first master
  template:
    src: "longhorn-ingress-secret.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/longhorn-ingress-secret.yaml"
    owner: root
    group: root
    mode: 0644
  vars:
    username: "{{ ansible_user }}"
    password: "{{ ansible_sudo_pass }}"
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']

#- name: Apply the Secret
#  k8s:
#    state: present
#    src: "/var/lib/rancher/k3s/server/manifests/secret.yaml"
#    kubeconfig: ~/.kube/config

- name: Generate longhorn ingress manifest to first master
  template:
    src: "longhorn-ingress.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/longhorn-ingress.yaml"
    owner: root
    group: root
    mode: 0644
  vars:
    service_name: "{{ longhorn_service_name }}"
    service_port: "{{ longhorn_service_port }}"
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']

- name: Generate longhorn pvc manifest to first master
  template:
    src: "longhorn-pvc.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/longhorn-pvc.yaml"
    owner: root
    group: root
    mode: 0644
  vars:
    storage: "{{ longhorn_storage }}"
    hostname: "{{ longhorn_host_node }}"
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']
