podAnnotations:
  reloader.stakater.com/auto: "true"
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.14.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: kubernetes-backups
      default: true
      prefix: home-lab
      config:
        region: minio
        s3ForcePathStyle: true
        s3Url: https://s3.aknuk.dev
  uploaderType: kopia
  defaultBackupTTL: 720h
  defaultVolumesToFsBackup: true
credentials:
  useSecret: true
  name: velero-s3-creds
backupsEnabled: true
snapshotsEnabled: false
deployNodeAgent: true
metrics:
  serviceMonitor:
    enabled: true

schedules:
  cluster-backup:
    disabled: false
    schedule: "0 2 * * *"
    template:
      ttl: "720h"
      includedNamespaces:
        - '*'
