---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/ajaykumar4/home-lab.git"
      path: kubernetes/apps/actions-runner-system/app
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set-controller
      targetRevision: 0.14.0
      helm:
        releaseName: actions-runner-controller
        valueFiles:
          - $repo/kubernetes/apps/actions-runner-system/app/values.yaml
  destination:
    name: in-cluster
    namespace: actions-runner-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
