opencost:
  prometheus:
    internal:
      enabled: false
    external:
      enabled: true
      url: "http://mimir-nginx.observability.svc.cluster.local:80/prometheus"
  exporter:
    defaultClusterId: "home-lab"
    defaultBillingCurrency: "USD"
    replicas: 2

  ui:
    enabled: true

  exporter:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      storageClass: s3
      size: 10Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 9003
