apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opentelemetry-secret
spec:
  refreshInterval: "1h0m0s"
  target:
    name: opentelemetry-secret
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  data:
    - secretKey: clickhouse-password
      remoteRef:
        key: 9d03ad48-2758-44ea-a203-444aa76f2b02
        property: password
    - secretKey: clickhouse-username
      remoteRef:
        key: 9d03ad48-2758-44ea-a203-444aa76f2b02
        property: username
