apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opentelemetry-secret
spec:
  target:
    name: opentelemetry-secret
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  data:
    - secretKey: clickhouse-password
      remoteRef:
        key: clickhouse
        property: password
    - secretKey: clickhouse-username
      remoteRef:
        key: clickhouse
        property: username
