apiVersion: v1
kind: Secret
metadata:
  name: opentelemetry-secret
type: Opaque
stringData:
  clickhouse-username: ENC[AES256_GCM,data:FSGur54=,iv:WqObqnoVMGlu0XSKE05Dyz97mRmaMpGcmvNnPcQoe98=,tag:jNLHFSrsuXaNlztU5uVHLw==,type:str]
  clickhouse-password: ENC[AES256_GCM,data:+Uqlvto/0gG9BZRR,iv:64VQRxKhadzckKKy4bPvV9qMrduytxiNiPK5hC0spR0=,tag:tMgyGPZpEyUpZc1EBAUSCQ==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5b2F1NDlzb3RnZDQ1aDZn
        VU5JYVd5U3dHOU0raVRrT3RFVnJWUTJCMjBJCk5YWlZzVVowOGM3U2lxZEc0aTcw
        eHducWFVTDFkZFNOOFU5UXNURGVvSzgKLS0tIGpKTGdGclVKZGthMlhlTkI5WWpj
        ekdKTzJYRkluanlOMWJOeGdveGgrZVUKyqzA0UYyLbc2Gx6BKngqnjv42uRdRlAD
        7u0xU5+hASI06D43qMuxoAUkRm7aOeNJK2CVp/GwLqMwYj1Pce8Sog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-01T13:01:32Z"
  mac: ENC[AES256_GCM,data:CtL7/BQnPKcTUodPzdVPbhcIJKCzyhijtkHmkxT7Yt6z1oqoR/R+32MCaC6SssIpgwovujxEH6cH+EeSd7oj3g1NwXx1lLUMlfQAaYF1l1cytJDZOcouxiTr4j4+yqK+ArgauAUnPR26WIONhm4vnojA/n18KLnUnCBxEFtKSuk=,iv:nhyjBtnjmTGE31KKOU7gYgtWk8BimmstHeUD9ZIgqYE=,tag:ZvZWVtSS/cmJN+RGirg5lA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
