apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-production
    profile: shortlived
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - aknuk.dev
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHBRb3BETXls
        dXgvNU1ickxWMFc4cHVjMjdOVFRvb3E2NmhiRG1Ra0FRQll4WEVrT29ad1J4QWdD
        bU5EOWthOTAzODF6STgrMnROYlZ5VTJHcWJsdURMTDNKcmJlSGtNeHlIMlJZUC9O
        QlpCM2g3MmwwWVgyTEkwNC9CVzZHdWJhaHI5UHFVUDZianhJQXRWTDQ5bER0QmlQ
        N3dKb1A1U1FLN1J6NVpvWUpoRm5vWXlxcnZyQ3lEMWp1WnZSRU4xV05vanh1Z2JO
        dlFNUlRPeG14MDZFckdPbHEwTUw0R1g1aHlnOW9mTHRqVi80bXRMdWZRUklxY2Vh
        ZEQydk9CenRwQlYxZkN5VDBDK3Z4QmdvZ05RazBmcTZleWJybmxGa3NIQklDaHZi
        dzFvUXlzczVTci9wY0kvV3RsM3JXMmRURlB3Z25sL3Byc1VCZXpWUEtWazhCNHJo
        Szl2NklaV09lbTFPbXdLMVB4QXFZc0FpN1BsSGFZUUFQell1LzFqTzNjelY2TGVu
        dy96MU9RbjJPOHViQktuRlc4M0hyMy9uaDIxZk5GYkprRitQNFZJajVIQWZHNnRH
        L2tLS0VYaTRDZ1VybkV1SEF6bXBRbjZhRmlxTitUYkRoakpucE8zZnlQSnVqSmdm
        UlpRWFFTeGJDaHVQdkdCaUFKS0hZejZ2cnR5WTNFZ1BjQ1I2ZHBOTkJNc2lsdjY0
        YlRTQmxkOFhhdkk1a2dBVzJJRjVzYjRjd0YvNjc0V01OZDdybitacXFwSHJjR1JG
        Ri9SZTFtbFVrdENhWUh3dS95OFczeGtPU2Y1Zk9TWGN3QkpBT2YzcFlUbVEwQ2tT
        SW9WUmxxSVRpNzgvTXcra3JheFZHRnI5cHVISHE0SHdoeno5QmZFa3FPS296Q0Vw
        amxxRlVwZ2lOMlprMmg4enI1Zm1iL0RBR0tJU3dzaHZ1ZFJwakxzZjdqckNKK0hD
        NTlLNGMzRTNrTDE2Zk9IUmFTa01JcXc1cmJrMEc5UGZnTFpxQ0tGNCtDaUxCb0kx
        aitHK29oVDFrdHI4L0hUZVNSWjFDZjVHc0FwdnBsclgvU1JmWWprMGlDQWZ6L1BS
        b3R3ZW5GOStZenlGeDR3VXFMc29nUS9mOGNwQ0Q2MndkMDZ5NndaVGlSMzAwazll
        d1h3dVBYY0hJd1drMXJKTDFGUDlMQjVMNWJxTUZVdlJaR0hTNENJcmozM2F5WDRu
        K2xBQ01wY2oyOXFhcU93eU9Od0lseUNzbWdRUEo3am9Sdk1SNGdzNm1tUmFTN1Fi
        YXdHbHpwcVhNVVZLYjRlczVsVVAxQy9FeW9kVkE2cDJZZG5JSEZuV1FkWlMvdEUw
        dkM5aE9UZUFLY2d6Yzc0d2h4c3ZUd2lwZk5xNHRBekxBTmlRRlRTbVpMdjBmaTc5
        ZktSQlM3dWpaOUUyc3g4Q3FJd2t4eHJ5Qm5BaGNPNFY5TFdKdlJpV0Z1aXZkRXN4
        dHpHNjRYZnJjWG5HYWFyWmVKUUdzNUlEb2VDdEVKMmRvWlVWSnVEd2pWZkdWaWVn
        dENKZlRHY0oxWml1ZHRBRWRvWU14SlY3UDlMcHRRZnVoN0R0WGVGY1hGV3RMNW1j
        aEczLzc1Y29EUis0cEdRSE1ub1piUjdSRGRBb3dGdTBJQnNRYmlXOVVWQXZabDRI
        ZDBjSzM4aHNsWXd6N2lldnN0Y1lGc2VJbFE2UC90MWY5cTNUZVlOa0RBVUdFNE9J
        S2xwRVl4cWlDVE15Z1JPUjZ4Q1dOcnFUMzg5MHY0elM5eHJ6TFFpMjFFalkvS09T
        ZWVJOW5JcVhnbW9RNHczL2xxNXk4YWlMZW5BSEtFaDNBQ1RUa3lOb0tWQ0ZCckhk
        NHpTOGlNcFhlRTFmRWk1cDRSbGhsMk5zMmcrdDdhbjZka1IvVTgySGE3cXBXaVhH
        OFVEcU92aVpzR1NyMWpkUXdKNnhINGtpUDdCbUl5LzYzc2pYcGduLzBESW5lZwpC
        Z3JnRUs0ODVwUUlvRmlpUUl4aEdmc1JqaHBUOGxBVFEvOG92cEMySDQ4Ci0tLSAx
        N0pRN1NYTy92NGptR3lWdm1qODN0RkNRTkVzREhHVXhlTGQrc1pKZndFCimFHZqA
        fB/tLRG6HabNUwOjMlYD0M+hPeO1ECagfj1cJVYkLdtYWutgXA7TSQLMAGtG8RHn
        yilFWvzHg1PmfyQ=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1gt53jawqp8al0dmpzf39qxpmhux2g9sqdylryy0h2wqga3e0y4c4vd8f552gsnm6vpzskcpn37j4ma9vrpz2h3z926kxzynkxrysdgug5ykvx4pxvuvwm7zcgk43r3dtwnsj8demqf663j48tdx9qfa8vzd99nzcu2y8u7ej4amrw64qetj4hp776txdya5xgrfyywvp9dtun8rk3jn4y0zk5un4zjeewxegfd9vevx5cqxryxvm8dtg3ppdxgv5vfa0jwvk8l6z3h46f3w9z628sa739ddsuumkdwjg8s3c09wnl293hxz0dca9ttwztgtqhpjnj50sxu2sfxdcc3l6c7e5rw2uqjsq2dmgnmxf3v9y27edvafmgssckv6my0z9hkvzdcdafxv7pynel0xyjfan4ennwgd7j9yvg7x8ueahgjq5rh4eq5u4whzwknz0wgz4ccye2kstjazhttmqmnyezkr9t0mjlgskezy9836vrnxd8f47d228zvrqjf5swpxz7zc6dnp4zumn53w655gdyyg3u0pvtj4a4akvlkgey4x7wczjjhyuka5m7zy99w5r8vcknw5zswutypy35dnc4qz8y97dyqu4nw307xfv5hjpuyjc5wkfrtdy7ae7ws5awhwxyk4625594g8ak3eqztqcc0yyftdeq97ywq7va2zkx72733jvjvd84nmz2raxe389gx35autg0ucqnqjtjz6wmwaz6syf23gna8mtk7pptpc20pp3vef35qvrldhgzumccrs4a2vfaxawddtm6rdytgaxenzztdhr8jmufcduqk44ge9xslnqdpagh7477fv60p5hy5ayg4zum38qf8xz6ddmer7qrt42jwatzwqap6ndzhn5fxs2d4nttr5q57gy7dedlra55znsg9cez4zyy2vctda78n53dplp845re35kr305ua9dy2mngxzmhldz3nqg4jnslfnykd9ftc2pv77t9pm57y5cujdkfdc28dreg3pyyz4vpsp7au4q87efpuv25vkfxsrt57rq04su6smjpuvmypnqdrje6duzxkf0dvmgf45kfpsxqyvsvefd4ayydgxp6hn4huqa4rdmaqxw0a4n8ysp7uqp0e7m26v5ksxxjwantkm3krw4jh02j97yp3j0dv2y5qcgh4xpq7djs5ysgs5c25q56t2r6m2trxfuqmgdfz4jy8ydmpx8fmdpk6ynf97pswsdq6tzm8drjvlv308c30ej2wmk0pf92mf5qfqk348hg00wnx5grqygxjpzqe8j2ejvwvvdufhjqs2fyp4r8x0fqep0g6r7cfn0kpn8e9qyskjqdlhu2ugek0qd3d5vnwt94lv600jy4qhuz587pc4vzquqe66sy7ftwfzz6jnzpc267s6t8naz9cga8psee2gzc2zywjnm5rl489cfns9c59a29qzlkns8wujmg3zvdvkn5xfdlqaqe8qn28sf2x9d8t4xzsdzqk667qq4srf4kcattw5ddgl9n94rrk454y3efwzhsa5dyxsska9qpamj93z6rp7jfw8cgjgzws6a4jnyk8xp5t8ugjsxxquxxcz7pzyjx2u38dcjggqzqczuxrpfmju9ek0243pat2pquj0hmvv2smjgfkvr5mdzn2zvse5hrg3t8v992au2n8gypzdqa2s3p26kjkqjt23g4g525mttu7rgvuavd94rd8l4gu46egp0l3k5rgs467a3tl83gzf3pzn6ynru2jtjsvkt4ag3qqejqd7mfvpv3668w5rrnk5re8lqpd33fyg9ee4np93eql4thvx0kggyyfmvqy9fuckqj9lzgfdyzrgkmq6hvhj277j2qyqh7lrn8ya7v9stp8q65ujuffstktg3xnhah3g0fnqul8k5y9eckc540jc5fyr8k4r80vasq0x0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-08T19:17:10Z"
  mac: ENC[AES256_GCM,data:dq++npp4/KcODA82DJt2pQZykOVInCFjQkSqF/Rn2NGXiOh4Z8BqRHJETbfdHsOUGhEtQxUS55MJJ8o1tfXvPgaj81T4zZcp3OspnhSXSkC3OOJH/hOMhx4V/CEWmSWc5LUTimywGKvXjWC4DP7A86grSMW7mpd7LaJCg5YMae8=,iv:f05DoHsjlKwCltdydBqh7v8hLyHWpxfmTy7lkPoRWwk=,tag:R4nDPryO33tXVVYvEEnaXw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
