apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-production
    profile: shortlived
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - aknuk.dev
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWGFITUF1d2lveklvQmJZ
        MFQ2ZnVPZE1OcTlHakJ4cHNZRFhlV2NHRkRZCnBQSDJQUTNOdWl3QmI5cjZBaXpw
        ZnIrZXlWUXM4cWxnTDY4Tm9jaWdLZzAKLS0tIFkzamo4cTNpdDlDZzNUS0d6OE5r
        bE4vUWVZVFBCbnFCdU11UlcxZFhqWDgKoVY9blWx575kAbO1LImwE3T8sVg5PmEW
        zoV3/5ryk/D8Di3CVnTEaqV53VyDCsea0VbWnQwe19ti3yrj+mHuEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T11:36:32Z"
  mac: ENC[AES256_GCM,data:HZ0NyYdiTOARdc/yKMohFNoRQ5OVM4YSCbsGL3L8dxgY0YdX2KKqZkwh/8tvZJxzqqrHrd6oT0iW+50KXxUYaM/4WoSbWPMl8h9uVo9abIaTEqQMy9jBNrPlPJm8dzNDrwxnmUKl3OHMAyiuYBxq37iGggiKxuPsGAnHLOxQD+c=,iv:Wcq15ep2tVKrVDL75ags8mxx2U4Cdefgx2ante512l8=,tag:dx9M1hWt8g+Ur+lsQ6s02Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
