apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: cert-manager-secret
    template:
      data:
        api-token: "{{ .ApiToken }}"
  dataFrom:
    - extract:
        key: cloudflare
