apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:qp8Tcriq9n4shyAHbl0tkisYig8nY7Odk2e/OJbs5sSGO/LAgW2Yww==,iv:V4SfBOmcNNOEVwWRfLSSYa5qM7UWzTh9peYbBzxE2e8=,tag:bnS9nrTxfJrd9e1CEr5jRg==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZDNkYTBCZFBMWHQzUVFn
        dnJ1cEFIYm5jek9aVE5iT1ZUUjVlZlZZSWxRCjRubDlJRUJkQ0oyWEVJS3RXSW5u
        dXNvZnJvU2xVUFNwVlBLbU5wSlliNjAKLS0tIHFyRlU4cklRTHoxY2Q5WFJpVkFi
        U2lSM05iRllVSmVUb3p6YW9zVGJoVWMKhEt10X59f1d+QCebpZMnvbRVr0+3NwSj
        k5lpG13LBgy9xqThhU1HvP8VbsAdmb3iYopPyiryFRe9vyexDJ1l+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T07:23:53Z"
  mac: ENC[AES256_GCM,data:B8TN+IOUKXipeRMWHDqd0ei187xxNMN0tMeSE+J+RabQbNIaniQVl0UVrdm+E1n8M7x4Y3VNyJsILVBS67rvQx4isPlfXz/0koGZcml/IOBWHZ57gB0ChE3iy8BA3VkHaz1lPNe6FFFr6KJGT/GDXiYVSS7MMGwP6Mss6RuzacQ=,iv:5s9lcnqxuwzZSzM3IPkoLfpckYn2RBMq40llyXrfoaY=,tag:loKmXn3yyLQ7WuYmRWu5Zw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
