apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:o2nDl2bQJ9MqSKiFmJcvYkb6NG+PXxZ5+TDpazcWu1cFk3f/anc+WQ==,iv:DzrZtOlAMYi91/dhDrGk4YO9BE+zODydOrQVpy0/2rU=,tag:akFPxmswxySFoyLFSAkL7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh9qxg0nplvlncvld27lg3h4f3epdsr32vuxswtxn95fyhj04ufsuq9cl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaHZuVXBLWlZWaE1aQ1BR
            TE1Vdm1qRFBhUlRrbHNJWFNybElFcm9qTTBZCkJYZC9vNXJsTWRRclZqbWNxMnY3
            UHJwMk9JVC9ucURIbTZGN09ZMlhaYnMKLS0tIFJFaC9jUnhmU29UVUZPL0hubDA1
            Z0NXZVNJSUVDcC9tczFBOTFiMkttQ0EKbp2yno5CS36HMAveT7xqk26TSnb/dLCk
            g7aJ2AZKujXdg5H1Q5uGvyMqVPr0r/Z0u3uIWx8IgNt8uoM0FhC7uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T23:06:48Z"
    mac: ENC[AES256_GCM,data:imlBYQGVpxG6gk4Un2v6WP1FatTEFRWpPkY6negorcqj9OjnNho9kenDOAMZHomCA2qH4XVib/rMZ/kjrg0VA9OF3P+D8Zg0VP6LknyndXupnLr1xer1LREHjwYbeuxYZPeGWV1HRPfSXkbvt75TyjBnEuPZGkz5zv2SF9JR5/0=,iv:ojpH4pC1cb5b5PQJjS5BM2pEDzGlB1VOtabMDwPKNqs=,tag:0z90Vu6pLARmuWt2rdLuHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
