apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-secret
spec:
  refreshInterval: "1h0m0s"
  target:
    name: cert-manager-secret
    template:
      engineVersion: v2
      data:
        api-token: "{{ .ApiToken }}"
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        - remoteRef:
            key: 2663d32c-47b4-4e4c-917d-95cd4bae8fb8
            property: password
