apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:80mYgZzWPYWcQN7Tx3j+hN9AH61d8kcEHjn2EHI6gDVXaJ+C1bwUxQ==,iv:2AYboOyv7M9NI46IZTXL3LWIFHvY3xlcBNGuK0wX96Y=,tag:Nw5pJXtSiVoD+dQJaRhawg==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSkU0Um1kQkZSNXlIcGYw
        LzhpU21tVGpzVXJVSGNVWVhwT0RaRWU2enhBCmc2THFhNlhZbnJCQ2NsbVVtcjRP
        TDBCMUMvaU45YUZRcElVcEZZZ2FEdVEKLS0tIFVUZWxqeGhOTG96TnNIWDA1VFRU
        cms1ZU9COHcyTGxIM2pRQ09lWjdHL28KPejGGFqV+XO4zkQhyt0uK/CmXoyPMRzq
        B/aNOuzGNZAvS0iFkbwTMhGROGzyy6kcYxEPHck76T7GSJiZTNS+Tg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T07:44:15Z"
  mac: ENC[AES256_GCM,data:JtveGXIPSy0Dj35VqYmePgG+BJ3q7FYvHWN3J2oYaFCKum2PqARozYbGi5LezyeExZR3ljYLDacru3355k4NAWuJ8RqdyYNyeXmKhPeqS5iGl7CnRVTzbQkiN23PXI10oDyiqFjzyzRf72T1aH8iCCyWQEJLDlinA07XAZ1izyc=,iv:q8xl6ZjJbbMfF1QQ9dbRBtSc9ypDCW75bI5xD1RQSIM=,tag:ETxX2Q99G3tEAAuXR1w04Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
