apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-secret
  namespace: cert-manager
spec:
  target:
    name: cert-manager-secret
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  data:
    - secretKey: api-token
      remoteRef:
        key: cloudflare
        property: api-token
    - secretKey: domain
      remoteRef:
        key: cloudflare
        property: domain
