apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:DsZZTTKCtEp9t4FXM4czuHmRuj9lskrf9+bsp+ssIWn3SqquFYwKXA==,iv:RdpInsMrWsSls/UmWhIyHSiKXTE5sbTm4g9Qwv6aCNA=,tag:cgBKy+4gvm4jYonDWKq6Jg==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVmh4bVRyenFuUGQ1c0Nk
        bEMrMkgrNk94cjJNMVJYUWZKVTN6a0NPSmgwCkZEcnpLOFVtSVdwdUczUG9tNzVa
        NEVRcDA5TjlZYkVDVGRQMlFiSW82MXcKLS0tIG9RTTRwNzFNS3dKb1NaQnFvSG5K
        OUNhZ21JSnV1WDYzemtSS0E4c29aVDQKkfvbWYMDqXl1toZNhXJ8rrd6RfFEzOKb
        lHBsSc6qw1iMgtCeOtAFYfjSskqgQzQL9/1/vnfRDaXnpgcxTj1wMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T12:25:18Z"
  mac: ENC[AES256_GCM,data:NtL9DE8B54J/zDrpr4soQcLcWX5ONVO0uEHFQMD1MBpGAOvnaIULZbpenhpRVljrYUm9iydkB3JPFpWjy//N18oSUExnDpxYxdt4Vot4d61fQB0demWaFCXuLJTElyrf3U2VVC+a4FiY+ZuFNpJn7pZOxgm0X2yBs6yZhl53jRg=,iv:pwgygYBE7Z8On/7fBPyERkjuxN8Tz+YycYz9tD+mojw=,tag:evQZZn76/fonnEmL1410aA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
