---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gatus.yaml
  - k8s-monitoring.yaml
  - keda.yaml
  - kube-prometheus-stack.yaml
  - loki.yaml
  - mimir.yaml
  - opencost.yaml
  - tempo.yaml
