---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-logs
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '4'
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/ajaykumar4/home-lab.git"
      path: kubernetes/apps/observability/victoria-logs
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/victoriametrics/helm-charts
      chart: victoria-logs-single
      targetRevision: 0.12.4
      helm:
        releaseName: victoria-logs
        valueFiles:
          - $repo/kubernetes/apps/observability/victoria-logs/app/values.yaml
    - repoURL: ghcr.io/victoriametrics/helm-charts
      chart: victoria-logs-collector
      targetRevision: 0.3.3
      helm:
        releaseName: victoria-logs-collector
        valueFiles:
          - $repo/kubernetes/apps/observability/victoria-logs/collector/values.yaml
  destination:
    name: in-cluster
    namespace: observability
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
