fullnameOverride: victoria-metrics
vmselect:
  enabled: true
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 8481
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: longhorn

vminsert:
  enabled: true
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 8400
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: longhorn

vmstorage:
  enabled: true
  replicaCount: 2
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
  service:
    type: ClusterIP
    port: 8401
  persistence:
    enabled: true
    size: 50Gi
    storageClassName: s3

vmauth:
  enabled: false

alertmanager:
  enabled: false
