apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:N2R2eDQrJDV+oorzGSdGzCLRptvTy2TPCApPFWJIE9NIM/toCHoIbWpi/Y5nZYYBZZq+dgjynGcIjE0OSY7p5NbnD5pi0KbW/id3/nDAI1EToDJSi/LDYzfu35eX89nBb+hZQ6dWXnZy/Om/plYDIzcosXrLWn9O7BuN3y1cVFApf/WaE1xyXmaXZiXjKMGI/p4uQIq6uw9vyU3DF82Z7AU0nCxqY99P81+70Dcg47O3hCK/,iv:OPYRRZU0XPsA8nu4sVeSRHL4pBuFFUeUEw2u4NCg4SI=,tag:SCBfRifiRNUXYUXY9snpRQ==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPb1dqeS9TYmIvNitmRkEr
        eGQxaXpLUW9jZXhySHI0cDlxM1pjejRtOFdJCldaT0F1U242YXp0UmQ1MlJaZllo
        SGRscW9nOUxFMVJoRmFlSXVQNVpOUzQKLS0tIGUyQm1xeFVWaThTRGNJallyTjlm
        cGMxYTAyWEFnV2RhNFlXVXoxaE5ZUk0KK33Rg5B2SFGR8vElaTiRVvgOGNBQP9ff
        ndwRUw3V8t4owp9ZYACIYI8G7qv1ew5FyuPfrMIN9mNeOvf2a0vzEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T10:06:43Z"
  mac: ENC[AES256_GCM,data:gMXqQDXQimA1uez4jFGtd/r1AQxigmbeDOqVtK1s5g1F9oGPLddWoNm5HA09RrHJeHBGT6d+QqV5HNJkKM2WeAfblm2dNrkKzemeJkEXX/S0MlsGbIcUwX1jjejx8lf59ojXfxRktHrhRs0YLwAYXF3VF6ELY/7luSQdMUj4E0U=,iv:qIPC3PWQrvzc8UDfv+sITWPVO2OTV/hUqg8rPJl7kgA=,tag:up6H3avHDpopw/IgYDaqJQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
