alloy:
  configMap:
    content: |-
      discovery.kubernetes "pods" {
        role = "pod"
      }

      loki.source.kubernetes "pods" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [loki.write.default.receiver]
      }

      loki.write "default" {
        endpoint {
          url = "http://loki-gateway.observability.svc.cluster.local/loki/api/v1/push"
        }
      }

      prometheus.scrape "pods" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [prometheus.remote_write.default.receiver]
      }

      # Setup typical talos apid and kubelet metrics scraping
      prometheus.scrape "talos" {
        scheme  = "https"
        targets = [
          {"__address__" = "127.0.0.1:50000"},
        ]
        forward_to = [prometheus.remote_write.default.receiver]
        tls_config {
          insecure_skip_verify = true
        }
      }

      prometheus.remote_write "default" {
        endpoint {
          url = "http://mimir-gateway.observability.svc.cluster.local/api/v1/push"
        }
      }
