fullnameOverride: ENC[AES256_GCM,data:74O4I6at,iv:I4Wgozt9xbQRptkSTJOEoai9OuJAXn4X1UjCZ/M0qP0=,tag:hJXbky18Y8Mu6Uern+umpg==,type:str]
configs:
  secret:
    argocdServerAdminPassword: ENC[AES256_GCM,data:ls8ZurDaY/l8Izv6mqP76LSCAysJpKxVBB1kbT68SjPAiMTaNLOgz1ol5o2hRRViUsdpCvLr10zfma9B,iv:YZyw22ex2tsRIMDmYzRdUI1dZQgsIOQPXEbl4ZcXqq4=,tag:Virrp4uT+f+TrLUyQuH5+A==,type:str]
    argocdServerAdminPasswordMtime: ENC[AES256_GCM,data:lRsiStX3Z1YaUYmBAlLkD2gMkw==,iv:i245bZE0DeR3+ptWdLoKgbdBHpJBy8istzpSroQdc28=,tag:wRegzCpXI6OZgjqqowoX3A==,type:str]
    githubSecret: ENC[AES256_GCM,data:PtHsFDZzyk6Bq1H+MGXr+uBjaMeASjWHWAPfT5KhKHc=,iv:WDtBUDjRd5j0vHrjFcprkWt8jHVLJ7VfqVCrSiotukw=,tag:7f/CeXBXaTW/qWvYWSBswg==,type:str]
externalRedis:
  password: ENC[AES256_GCM,data:2X1/OBt/YuwEvDSN,iv:tMWl39EPtZUJIklVs27WFlbDst9kMrSkPE4OqQFa9sc=,tag:hRdeRq8W782KrT4wY+m0/A==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSXlBejJCU0dNeWRmWWF4
        ZWY0STJxRGM1NzJNVXJGSFpHaEJmeDhGWXhBCndrVHEyRVBNK0Q0aUk0MGsyb1JL
        anhnQ1BmQ2w1LzRVWlhwWjE4MmpFbG8KLS0tIEFvY3pHV3htajhKbThTQ2xGeTc3
        SWlPaHE2Y09XeCtrZ3d1MW1zV3o0Q3cK5MKQqCgD/Wvbnjr8AKpGRRjD8xiOrAY0
        K45x0JEmAKewNpc2fTD9U79tfRHaXMLoo2nfTuIJmooIkkemDd+4Rw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-01T18:00:33Z"
  mac: ENC[AES256_GCM,data:QbAQGuvJCdilj9nZGghV5PG5HWcYbz6+AsqXtnCORHhppnGjbmbnwUtj4S2vpJ29KCeq+NcU/iEUKDFyApmpZzWfdSKBmgXuAfZldqy7o8AegtjtdNb2K9zSbXMEiw569nj2LFzkW4T7ov9q+PJFoeqsXFiYGweQkw4ZFB4GvLg=,iv:q62EtAecUVGKPHiVpjvvyAfp3M4czATjYpKVuLTCGh0=,tag:MpCKd7PS9AZyVtPXBtXK3w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
