fullnameOverride: argocd
configs:
  secret:
    argocdServerAdminPassword: ""
    githubSecret: 9f2e6b632c2c44b7ab8db9728c9f89a4
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFRPc1grNE1E
        YWRzUjMrWGRUTWRVMWR0MlZpZUxCRFl2TEhSVEVFUHY4T1RsZzNlT1RsZ2k5bDlQ
        aFdJZjF0VkdpNlExbWJBK2kzeDBKSUlnMFl5RUVqdUV4QlpSTENxUEhhYjlJU1VR
        dnpmNUhyNjBsVnVIZ2o1bG93RTVhT0FYTW5od0kyclViV1BkMnBvL2d1RGJYZFZU
        bG81SnBzWlI3eUJUN3R0b2ZBdyt3SUh3NlRUNUFQcGZDcDRZRW5SS2liOWZGcE1L
        VEZSbFRVeE9mZTVlV3Y5TXJ1WFExWmppeCt5NC9kTnQwS1NjOXpmMGN2aHRZTEV4
        cUJGNzA4VXBGcVBYWEdRcFJQNXh0UVBxZzFnZ0tFdStINHBRNGNHb2I4WDMzbUFW
        Z2N3RlM1dVFleTNQK1IvS2R5dWNFWlU0WVpRRktiOXNlL1Bnc0c0NWRBaGwrYmxq
        K0g2ei94UXc5U09lN2QwdDIzd0cybWpzUDFKWkJlOE0xZHY3R3ArTTZSTFV5MUxS
        T25ra05lbm9keVFoV2J3OUNlZ094eUtaakxIWTZpUUJMc0NLaS9KYlJzK2dGbFBu
        U05VbDJPcyttcUl5aGcvOFBEbExKeU02U0ZzU1ZiOGZrTTVFNUtiMldlYVN1NVNM
        YzVqTXF2L3FSeVo1L1pqSXpHQkdSSHBHTTVCaGJhM3RSR05LN2g0WXkwb2RiTGVF
        YmJTQVo5RWdHZ2tacml1U0pZeSthQWRpc29QVHhVZVVKamt6akZ0TXZPOVJ4cVVM
        Uk1ROWtOZEZLRUlCSStVWnlZaC9EM0lMeXhPQm5ZYXZ4bGdrbFJRSG5vLzVFT0lK
        eS84ajF1ZFVOalFkZ1pRS1FQTS9sTXFrR2wzS2xFbDBKcVZ6WlcvckoxZUdQUEpX
        WU1hREE1TVVocXlVQnU3alFTWmtvK1AxYXBDSmpPcm0zbnNBMzBKN05NZjBnR2NY
        RlZZWEtEZUhrU1hScCtUSWorNGJKUTgwYU5jQ3BCVlhnNVlYMzZ0akJRSjRiRVNo
        ZVVTL1VBVmJ1TkprU05WRlc0UXlISXpJUHNURWNqYXc4cno0WGRDenZSeVBtVnZS
        d004c3AwZy80akRKbFc0alN2RUlhYTNpK0VLM3V1UEwycWdGYTgzeTJ2UG9tL2pv
        emdQb29ROHYvT0pKdGVlUEJlMjNaZnUvSGxUNUFSV255UEduZHUxQk11aklrc0VV
        U1FEWkl3RjFGN1JOQlZ1eE9ETHo1UUxMWHlwNlBReUhpRUYydmhEUXptV25zWUcx
        ZmcwZFZxczlTWDJuUkEySW1HK3hybzQvaVozbHUwVFN4Y3lsWm43Y2wxcmFKT1ZW
        WVU4MGtxdUtsb0hPNWlEck5GVXhjblB4VlVJRGVnUWt2OGQyMG5lcmVSeWRNWnhJ
        NFNFNmROYlZ6ZkRIaFpDMHp3eTh6U0s2VnVCM0U1Q09FSDZOaG9PU2tscWZFRUl3
        dVFlcXBjMjQrRWE1czFxckZ2SmlqYlJ3Ylg1VnYrZ1RSMEFaUGJ6Y0tCK2RmWGZj
        KzdIWjBPQW9qVWZYUWQ5czc1djhER1lJNVYrMWp2M3YwWHJXUWZ4d1dDS0Z0QURi
        MEZiaU5hYjB5VkljV0poaFJ1dGUweUpwUnFlN2VjSjRZSzB1WTdWandrenZ0NFNV
        MHZZeGtjRDJib2YwUXhMYTZkK2RqZGU0TzlaL0czd1hvckZDdmcxdUlMRHFzUE9w
        WDUzRmdWNlhqSndNMVEvbmN4Y3hzZG93S2hIekVrbGR0VFB3SVV3c3VVSDhVLytR
        c3Jac1pJcFFmNi9WQXgxNm51WHd4L080R0ZFZUdyUE1GRmhicnQwb3RXYTRYRURl
        NFpubU9XckpGQUd1a0loSWVSTjdzMURueWlPbkRiaFBiWnFkUFh1TXBVbzVJb0pP
        NEtHZ2NjZ2VTdVo0SU5vMkFlLzVoaGpPTzdYNWdxSzVtbVgxaTdnUTEyeGJSUQpu
        ZXI1R1VHNmE1SDIzZWRMTzczUWMxZ1grN1AvakprZWtkTnpUMVBycFNJCi0tLSBy
        Y0w2Q25rbjIvdHg4VEY2UzVTclZybXR3WSsweUpxb0JUVng0c3JSK05JCrSyKY1G
        Pz3tAKT1RyLsNRm3i5oWLKYzFIB8eTe1iCDoZ611cwFVZ45fEobFGr5b7hFYWiJp
        NdmbpN+2pQnLfPE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1gt53jawqp8al0dmpzf39qxpmhux2g9sqdylryy0h2wqga3e0y4c4vd8f552gsnm6vpzskcpn37j4ma9vrpz2h3z926kxzynkxrysdgug5ykvx4pxvuvwm7zcgk43r3dtwnsj8demqf663j48tdx9qfa8vzd99nzcu2y8u7ej4amrw64qetj4hp776txdya5xgrfyywvp9dtun8rk3jn4y0zk5un4zjeewxegfd9vevx5cqxryxvm8dtg3ppdxgv5vfa0jwvk8l6z3h46f3w9z628sa739ddsuumkdwjg8s3c09wnl293hxz0dca9ttwztgtqhpjnj50sxu2sfxdcc3l6c7e5rw2uqjsq2dmgnmxf3v9y27edvafmgssckv6my0z9hkvzdcdafxv7pynel0xyjfan4ennwgd7j9yvg7x8ueahgjq5rh4eq5u4whzwknz0wgz4ccye2kstjazhttmqmnyezkr9t0mjlgskezy9836vrnxd8f47d228zvrqjf5swpxz7zc6dnp4zumn53w655gdyyg3u0pvtj4a4akvlkgey4x7wczjjhyuka5m7zy99w5r8vcknw5zswutypy35dnc4qz8y97dyqu4nw307xfv5hjpuyjc5wkfrtdy7ae7ws5awhwxyk4625594g8ak3eqztqcc0yyftdeq97ywq7va2zkx72733jvjvd84nmz2raxe389gx35autg0ucqnqjtjz6wmwaz6syf23gna8mtk7pptpc20pp3vef35qvrldhgzumccrs4a2vfaxawddtm6rdytgaxenzztdhr8jmufcduqk44ge9xslnqdpagh7477fv60p5hy5ayg4zum38qf8xz6ddmer7qrt42jwatzwqap6ndzhn5fxs2d4nttr5q57gy7dedlra55znsg9cez4zyy2vctda78n53dplp845re35kr305ua9dy2mngxzmhldz3nqg4jnslfnykd9ftc2pv77t9pm57y5cujdkfdc28dreg3pyyz4vpsp7au4q87efpuv25vkfxsrt57rq04su6smjpuvmypnqdrje6duzxkf0dvmgf45kfpsxqyvsvefd4ayydgxp6hn4huqa4rdmaqxw0a4n8ysp7uqp0e7m26v5ksxxjwantkm3krw4jh02j97yp3j0dv2y5qcgh4xpq7djs5ysgs5c25q56t2r6m2trxfuqmgdfz4jy8ydmpx8fmdpk6ynf97pswsdq6tzm8drjvlv308c30ej2wmk0pf92mf5qfqk348hg00wnx5grqygxjpzqe8j2ejvwvvdufhjqs2fyp4r8x0fqep0g6r7cfn0kpn8e9qyskjqdlhu2ugek0qd3d5vnwt94lv600jy4qhuz587pc4vzquqe66sy7ftwfzz6jnzpc267s6t8naz9cga8psee2gzc2zywjnm5rl489cfns9c59a29qzlkns8wujmg3zvdvkn5xfdlqaqe8qn28sf2x9d8t4xzsdzqk667qq4srf4kcattw5ddgl9n94rrk454y3efwzhsa5dyxsska9qpamj93z6rp7jfw8cgjgzws6a4jnyk8xp5t8ugjsxxquxxcz7pzyjx2u38dcjggqzqczuxrpfmju9ek0243pat2pquj0hmvv2smjgfkvr5mdzn2zvse5hrg3t8v992au2n8gypzdqa2s3p26kjkqjt23g4g525mttu7rgvuavd94rd8l4gu46egp0l3k5rgs467a3tl83gzf3pzn6ynru2jtjsvkt4ag3qqejqd7mfvpv3668w5rrnk5re8lqpd33fyg9ee4np93eql4thvx0kggyyfmvqy9fuckqj9lzgfdyzrgkmq6hvhj277j2qyqh7lrn8ya7v9stp8q65ujuffstktg3xnhah3g0fnqul8k5y9eckc540jc5fyr8k4r80vasq0x0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-07T21:02:12Z"
  mac: ENC[AES256_GCM,data:k2dCqoQM22IadQpFflvqsEenP/GQoqVTxwryOnkuBIsusx9cZFhLjHF0tIS5MNpkkVqwAX7WXxqdiq4A7egz3ZBH+2unONlbC3IwdaPs105zsU7xCbzdzZLey2orMfCV2r57ICMtrt96TLG1BLU9UjBeO+AAzq89bstAkgK6EYs=,iv:kSZru7RzH5N6a2lBwcLIYDj4QWcrf8oqRc3gSprktEw=,tag:AitFftcvazJFk03AW+863w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
