---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actions-runner-system
  - argo-system
  - cert-manager
  - default
  - external-secrets
  - kube-system
  - network
  - observability
  - renovate
  - storage
  - system-upgrade
