controllers:
  cloudflare-tunnel:
    strategy: RollingUpdate
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: docker.io/cloudflare/cloudflared
          tag: 2026.3.0
        env:
          NO_AUTOUPDATE: true
          TUNNEL_METRICS: 0.0.0.0:8080
          TUNNEL_POST_QUANTUM: true # disable when using http2
          TUNNEL_TRANSPORT_PROTOCOL: quic # or http2
        envFrom:
          - secretRef:
              name: cloudflare-tunnel-secret
        args:
          - tunnel
          - run
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ready
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ready
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 256Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
service:
  app:
    ports:
      http:
        port: 8080
serviceMonitor:
  app:
    endpoints:
      - port: http
configMaps:
  config:
    data:
      config.yaml: ENC[AES256_GCM,data:GCz4k0YpOcUDQ06cSesBNzUDdJ8I20EUs0mjpbukBf+07uWEsMWwo5Pe5ZpXsoI7r69625l/HnRM5HUOMM6hC46oDvJxbRj9N9Tt9WCg6se+3w6gyrb6D+nMtPZ5ZiyOC+PssVJDONGOiyiRQu6a3c5H++aAYZB/frDe51pubMq6ZFyIPhHTHjKFbrnHU2Lcx52/eeQReOIbEu9aTRorvtt3egtmRqyHpabzYbdFAE16tacetQjS3houHolm5nT6h5IzTEMq2C4xBLln4ZvPdJ77r5iXY5HyNy5D,iv:zld/bznUmogBdmbDBCvg8jFK9kMqbDxL5e2VKq1KQSU=,tag:pzo4AHhgV8+jUiyou/5bjQ==,type:str]
persistence:
  config-file:
    type: configMap
    identifier: config
    globalMounts:
      - path: /etc/cloudflared/config.yaml
        subPath: config.yaml
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGFZTUdPNVVZ
        RFZzbzloMzFEaEhOYTBISHN3d2JxaU5FY25aTEpkY2lvYUVKNmw1TW9iVC8rSEkz
        MDhqZHNGOGt6QW0wWGxLOHRUTFcvdnVzdkdRcHpEa2c0b3dJZC93VUVaS1Fqdnlo
        cDVuN08ybzhBcVI5M0ZCdkJLMWJOMUpTZWtpdjlqdXZqaU9sRG9hVDZORWYzOEEz
        aFM3YkpyOUR4bWhGeGIrS3VJdTV2OHZxOVhKQ2l4bVBSY2VuWC9ncmtmbDAwdnNs
        a0VBMXYwdlljb2N2Ylorb3YvQVVTUjlDcGR5Zkc5V1NTUVowTGJmZzcvbk80TTdp
        MzVJdDN1K0JPK2lKWHlOMFliVVRSTEkzRUY4bjliYWJmQUVVa3Vma2RPY05BM295
        cTIvNFhUclI0STZPM0txcDZWZ3lzcWp5MUpxMmFZTEcwWXlsckc0RkVORFlqRm1C
        NHRycWIxMW1PN2Q0elZJek5QbzdyN1M4YWNsN0Y1Mk9iYkJ6VFZHeFo0dUlBc2Uv
        bkMzTjNaaDdNejFUUVdzSTNxVTVKUnFuTjh5WTJROTZLcnRLZkU2OGwyVWNhaS8z
        QXB2ZksxNm82bnlRdHRBa0dvbkpiQUloV0F5dEwrc2psK2F0OWhjYk1lalh3Vy9n
        eHpSeDl5c0ZBMEt5NHdpNE5Dd0hSd1dlemlNQTIzYURZYldwb3lXS2g3STBaRmRJ
        VjV5NHJXVDlDL3FiajRXZkhZMm5IdzhMZ1M4WWVSZ2xXZE9LWm5VbkZGZk10WHdo
        M2RLb0NwaXMrZkhVWmYwTThrWHFHR2RMcWRXUVlqNkxHVTI0YVpUMm9NVU16QWJI
        WGZzMUJCT0ZxUkdWR3pKWDF6cHowM2tPaWRPYW5aemQ0NlZwaG8ySzlHbmhUaU8y
        dWpmQUFnM21pemZBMjFvSUZDNVUxUEFJSlBTcmJvRGl2Ty94eHNxcFBVUGpFQllm
        OS9Jby95VXVsVkh0M2VlVDY5K1pmaFVQa1VUMHJORFZXTVBVdUJIM0xVSmlZd3Fp
        MHRiZ21iRkNmbHVzblN1czZieDlYKzNzSWp4ZjFMQk9CRk4yUjAvam9pY2NXUDds
        VHhxeUxYMC9aczc1czc5UE1yR050Vkc1ZVVGQmlha3VKUUdTVDB4ZVpRVUZvRHph
        MGJyTThpeUEwZHhjZk9nNjI2N2FFNzRiOHBCeHlJeXRFT05KdDdNTkdCcndPbmdT
        eitxZlREZ0gxNGlxYmdzazJQaGEwS3JkanpKYk44N1hZanFlN3JySGxpcVVBUXFE
        UU1jUzF1NUREamdCWUkrVlVtenNTVm5ORmdzVTZSQjUreXRwQWJ3SGpyQW5ZeDZ1
        NS9UalhqZ1NCM21lOW5KMHYzN0pWcDJna2tBQnZwakxvdjRiaHVUbmtTbnhRTkcz
        NGRNaHFOUjJGZ1pMcmpjSGlINWdUSmZpRlpxeXprY1BOYlAxRGdsMkZiTWZkSDVs
        Q3I3anYxakNGRHpDVncrVHhXR3VicDRFWGhWZVpiUnlLTGxXQkcvMjNUYnZFVkdq
        akFMbzZWd1JIRVdzTFJCeTgwcWtmNEcxbFNDYXZ4Ni92R0g1QUMxQitIWlZ0eEFD
        VnArVW5waWs3a3A1VmdpMGNNMVdZYW1iR0FPOWtwSEYzaDJzdElibkpjT3dSQkJE
        U3F4RWNqbGdzeHZ1aXRVTEpaNUNpV2tJUHJ5S3RhYmdBMzQ5N0RLUTEwSjJqVktZ
        VEFoWnIwdGtTcFA3TXFVYnc4RHo0eGxMRGRVUmZRdUJZZnB0a1lUVm45L294cUR6
        ZHpvbmE1L1NYWm5HUDF0T2l2WjVTbXVla2prcjZZeEVzSGpwa0czWFp4ZU9ZN0Nt
        c0VlSHp6V2pPS2ZYLy9FR2I4ZDlodUxMeExTa0N3OURUS2M3bTl5REZHZVBGempN
        RTRyaFNyem10eWxlME5FZWhUd0RoalZoby9VMThad2t0ZW1XV3p6ei9tcElSQQpD
        d2lLMVNqb3BaZ3FyQTZLdW0wN0dSQnVnUk5tcU1mcVZLMkhwYkhoNHgwCi0tLSB5
        ZEFvNmtNY21HUFJZOExsKzVOWDc4VWN1SjJpNkdEY3lQL3gyaTREdjFJCvwQuFNe
        TFhLCms9lLSN+ga+5q51hHUGjSBPATfDZxbRSR72s5GyoQ5y160LLWFvvnD5C3Mn
        snKx6KujHUvYQ8Y=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1gt53jawqp8al0dmpzf39qxpmhux2g9sqdylryy0h2wqga3e0y4c4vd8f552gsnm6vpzskcpn37j4ma9vrpz2h3z926kxzynkxrysdgug5ykvx4pxvuvwm7zcgk43r3dtwnsj8demqf663j48tdx9qfa8vzd99nzcu2y8u7ej4amrw64qetj4hp776txdya5xgrfyywvp9dtun8rk3jn4y0zk5un4zjeewxegfd9vevx5cqxryxvm8dtg3ppdxgv5vfa0jwvk8l6z3h46f3w9z628sa739ddsuumkdwjg8s3c09wnl293hxz0dca9ttwztgtqhpjnj50sxu2sfxdcc3l6c7e5rw2uqjsq2dmgnmxf3v9y27edvafmgssckv6my0z9hkvzdcdafxv7pynel0xyjfan4ennwgd7j9yvg7x8ueahgjq5rh4eq5u4whzwknz0wgz4ccye2kstjazhttmqmnyezkr9t0mjlgskezy9836vrnxd8f47d228zvrqjf5swpxz7zc6dnp4zumn53w655gdyyg3u0pvtj4a4akvlkgey4x7wczjjhyuka5m7zy99w5r8vcknw5zswutypy35dnc4qz8y97dyqu4nw307xfv5hjpuyjc5wkfrtdy7ae7ws5awhwxyk4625594g8ak3eqztqcc0yyftdeq97ywq7va2zkx72733jvjvd84nmz2raxe389gx35autg0ucqnqjtjz6wmwaz6syf23gna8mtk7pptpc20pp3vef35qvrldhgzumccrs4a2vfaxawddtm6rdytgaxenzztdhr8jmufcduqk44ge9xslnqdpagh7477fv60p5hy5ayg4zum38qf8xz6ddmer7qrt42jwatzwqap6ndzhn5fxs2d4nttr5q57gy7dedlra55znsg9cez4zyy2vctda78n53dplp845re35kr305ua9dy2mngxzmhldz3nqg4jnslfnykd9ftc2pv77t9pm57y5cujdkfdc28dreg3pyyz4vpsp7au4q87efpuv25vkfxsrt57rq04su6smjpuvmypnqdrje6duzxkf0dvmgf45kfpsxqyvsvefd4ayydgxp6hn4huqa4rdmaqxw0a4n8ysp7uqp0e7m26v5ksxxjwantkm3krw4jh02j97yp3j0dv2y5qcgh4xpq7djs5ysgs5c25q56t2r6m2trxfuqmgdfz4jy8ydmpx8fmdpk6ynf97pswsdq6tzm8drjvlv308c30ej2wmk0pf92mf5qfqk348hg00wnx5grqygxjpzqe8j2ejvwvvdufhjqs2fyp4r8x0fqep0g6r7cfn0kpn8e9qyskjqdlhu2ugek0qd3d5vnwt94lv600jy4qhuz587pc4vzquqe66sy7ftwfzz6jnzpc267s6t8naz9cga8psee2gzc2zywjnm5rl489cfns9c59a29qzlkns8wujmg3zvdvkn5xfdlqaqe8qn28sf2x9d8t4xzsdzqk667qq4srf4kcattw5ddgl9n94rrk454y3efwzhsa5dyxsska9qpamj93z6rp7jfw8cgjgzws6a4jnyk8xp5t8ugjsxxquxxcz7pzyjx2u38dcjggqzqczuxrpfmju9ek0243pat2pquj0hmvv2smjgfkvr5mdzn2zvse5hrg3t8v992au2n8gypzdqa2s3p26kjkqjt23g4g525mttu7rgvuavd94rd8l4gu46egp0l3k5rgs467a3tl83gzf3pzn6ynru2jtjsvkt4ag3qqejqd7mfvpv3668w5rrnk5re8lqpd33fyg9ee4np93eql4thvx0kggyyfmvqy9fuckqj9lzgfdyzrgkmq6hvhj277j2qyqh7lrn8ya7v9stp8q65ujuffstktg3xnhah3g0fnqul8k5y9eckc540jc5fyr8k4r80vasq0x0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-08T20:18:57Z"
  mac: ENC[AES256_GCM,data:9tGznOAjpGIBsCkFNcAlLbA/+2TbbkHbQ0vzJe+jN8Pq8z6c3G580MrlomJcAhMLQpzEecrLYADzXv2FnioxK0ixhGds0BhdaQrKTgQhtXNbFbcQo7C1DqtQraLNIzhG8++OY9o9UwMrHZ6DuzPQ+6LFIqw/jee1DHT/4v9jZLw=,iv:Ij5zkl/Af9AVm8Wd0hJRgFl1+fUTlFIBEQOrj7Ee1NM=,tag:Jh9iaqp1dAqjEyGnHwMohw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
