---
    # Download Tailscale installation script
    - name: Download Tailscale installation script
      get_url:
        url: https://tailscale.com/install.sh
        dest: /tmp/tailscale.sh
        mode: 0755

    # Install Tailscale
    - name: Install Tailscale
      shell: /tmp/tailscale.sh

    # Set custom Tailscale IP address
    - name: Set custom Tailscale IP address
      shell: "tailscale up --authkey {{ tailscale_authkey }} --hostname {{ inventory_hostname }} --advertise-routes={{ network.eth0.ipv4_subnet_prefix }}.0/24,{{ network.wlan0.ipv4_subnet_prefix }}.0/24 --accept-dns=false"

    # Delete Tailscale installation script
    - name: Delete Tailscale installation script
      file:
        path: /tmp/tailscale.sh
        state: absent