fullnameOverride: signoz
global:
  storageClass: nfs-shared
clusterName: home-lab
clickhouse:
  user: admin
signoz:
  ingress:
    enabled: false
  persistence:
    enabled: true
    size: 1Gi
otelCollector:
  service:
    type: ClusterIP
