global:
  image:
    registry: quay.io
dashboards:
  enabled: true
  grafanaOperator:
    enabled: true
server:
  fullnameOverride: victoria-logs
  persistentVolume:
    enabled: true
    storageClassName: longhorn
    size: 50Gi
  retentionPeriod: 90d
  route:
    enabled: true
    hostnames:
      - vlogs.aknuk.dev
    parentRefs:
      - name: envoy-internal
        namespace: network
  serviceMonitor:
    enabled: true
