apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
stringData:
  postgres-password: ENC[AES256_GCM,data:1W8/q0D6Rbbfz654,iv:aDACiBye/p+AjBA+WUCAiQ1SGOLz0z/SoceCNyP9IoQ=,tag:7MGxyoFb2gduuhwg4auToQ==,type:str]
  password: ENC[AES256_GCM,data:88LnGLSnzQauDDOt,iv:gbJQxw/UrdsnDeGCZmyb//TlYRYosBe35CtWk8SyexY=,tag:Czgq1Co1gXQy+vSWYiMdNQ==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdXBxU0xyQmRkaCt4VUlX
        ekVBdngya0tMMmsrWlZLR0RDM1RMOHJMYUI4CmxHMUZjUjVkWktsbk5nR1F0b0FP
        MFdQVlpTUTJBWCtKcS9IeXArenJLM2MKLS0tIDdQZVJ4N3JpTWtKdkdpQStseFV4
        M2lETnNsMDE4RjNkZnY4ZlRJRzRHalUKA93LifCQhow6SL5Jgx+esf7vc4xlo+xe
        ZEcwyRomto1OD4BG36rMVH2T5WC1Egy9svJQ+eM3S9tQIzXrFhtzBA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:45:21Z"
  mac: ENC[AES256_GCM,data:ONYkdU6R0K9fba+a8XlncFlZKv9pOVcLETWvfw7/mo6sNA5rc1Njv6mlUQBWAvx4mnwr8ck2aqOtjkuHd+yCwqoX3Yl3BhwmiyzHSGT/O6TpR170NAdlbaSr2uZUDEMbdmH4fFS2pMhMkLsA1iCLfUtBFukRySKbMZzfNcRZOK4=,iv:op+VJg+gzGWdC/uiY8+inkvmewbPeGNZLSxBXpmp0Y8=,tag:MVyU+oEA9jBUdXcHWBDK7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
