apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: truenas-iscsi-driver-config
  namespace: storage
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  target:
    name: truenas-iscsi-driver-config
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: freenas-api-iscsi
          httpConnection:
            allowInsecure: true
            apiKey: {{ .apiKey }}
            host: 192.168.8.3
            port: 80
            protocol: http
          instance_id: null
          iscsi:
            targetPortal: "192.168.8.2:3260"
            targetPortals: []
            interface:
            namePrefix: csi-
            nameSuffix: "-cluster"
            targetGroups:
              - targetGroupPortalGroup: 1
                targetGroupInitiatorGroup: 1
                targetGroupAuthType: None
                targetGroupAuthGroup:
            extentCommentTemplate: '"{{ "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}" }}"'
            extentInsecureTpc: true
            extentXenCompat: false
            extentRpm: "SSD"
            extentBlocksize: 512
            extentAvailThreshold: 0
          zfs:
            datasetParentName: home-lab/iscsi/kubernetes/volumes
            detachedSnapshotsDatasetParentName: home-lab/iscsi/kubernetes/snapshots
            zvolCompression:
            zvolDedup:
            zvolEnableReservation: false
            zvolBlocksize:
            datasetProperties:
              "org.freenas:description": '"{{ "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}" }}"'
  data:
    - secretKey: apiKey
      remoteRef:
        key: a8000117-2f76-465e-b7db-8a9c2993686c
        property: api_key
