apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: openclaw
spec:
    parentRefs:
        - name: envoy-external
          namespace: network
          sectionName: https
    hostnames:
        - openclaw.aknuk.dev
    rules:
        - backendRefs:
            - name: openclaw
              port: 18793
sops:
    age:
        - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYWx5TVpOa2NDV1NpNlMx
            SCt3eUZhZ3lTOXMvK2FCMklPZlNEbkxlajJJCjdYRno1ZmRLeXFsbTQ0NHpaeHpK
            YkhVcFVKdnV5SGhXU01VY3o3U29IRjAKLS0tIHBoWUVBSXZFUEVjNEw1NG4yOHpF
            MTJJTmtxT08vMXY5b1UxVTVKUWtMMGcKhaPDCOxufws0+8hyJFIx/06VKwJu63za
            0Iz0mODnEYacz8+WpDEZe3a/jYDZCjMelJfeI+brfXF2YIumKldpog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T15:59:25Z"
    mac: ENC[AES256_GCM,data:mbDNWuMCwcedo1i42h0a2kxQ8pdTFSoVFge2gFALoV8vuQ4V4dof3qjkaGW9AJqKdKMO11UjPyzSJ26tSy7TeWesh5hSl7q62uf+gNyzlovrsh9/6Iju37W955nmbEFCHM6EGkylbgDOknORX5ZhJAxrd8CuE0bShae9c++JOpQ=,iv:VZBwQbdt0PUeJVCE6yDBt8XGjtpDP2V1eb/5x/AuaUU=,tag:zC2JWlCf5HvTQyRpvq3Tkg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
