apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secret
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:gnW6tpg0s9nQNlJD1dtpgVgK6ZZ4CfSeP5YWvOMCfGyxeO6u1waJu5wmztAf4CsmRmbjDgObLF05MBu9YG4tIdMrd27pHikcX4EIz3OZZ436djzmNjE/k4RcOjNAwpu0RiQXFnS9dVNynl0r,iv:mDzFyRIo6Hai3o4tZGX55SpLPO9yREODHmRkqmcbxDE=,tag:PhxZmEqGgemMutoWMePiGQ==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:qBvxz9dREoh84/++,iv:15IAgmcT2XZaemPjy+hC0/2ZE/h5zIDzzt5i+wQLUHY=,tag:yeImSobST1qw61YExSgLgA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:/HuBMWSv8nasGDjFzdSEHBqUvKDDPQUKC0L2OpiGcVnkN9pP9tzoPsbI8u/6rieaYlIpvl4k1Iz9DyMAeYl4W5Ekd58CsKZyTf9hFlJcZ55AhMYyVbtHOwMgWkkz+/CtFbdJwuyrLtPzJFXUnfzz7v8noZuziorEZ7IRU4uqQ+Pl4idI/ouPmvlWuLxJNhUnGRr8QGC3bh3DiuXzOdCTjrjQfeE=,iv:WUgvklXaSnI65l9CerU41mD75YurcAg5Ouhb7Sz4fRc=,tag:M2iloSEfM8nLm3Uc5lCFGA==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:HXDWfCupiRW/7vtl/nOSkamWCSp+WLWSVPRmgIX3OjBOCuk9xwI1,iv:ALlMn2T7mQ1Od1DJIYiKroeLytWIAQuhbIIiiQhkZog=,tag:U4aqdGi6xOAThVjenJdJTA==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:4O2dCRUN5dHfU6Q5bhwGGatO37GwU1iVBlB0tuDrFSsERH+Yh0flhsJVFqdSe5D7+UFZ+j0dZbn2JGPlQa2iSShZxERaB1YiVw==,iv:nc3mydpoRRajLv+WNL716O13Q4hNKIn7luRGSVN7eCw=,tag:LvMLd8WHp5JP5N/Nu0rCsQ==,type:str]
sops:
    age:
        - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbUVMb1R5WkNJQTBWb2hR
            bms3Nlh3TE45bkMrTHhxa0dtaDY5bGdVekFFCm1INVlBbVIxaDV4MDVPUkNIOFdN
            L0h5bWFyS1NuZDFKUHNQY3hUeDcxb3MKLS0tIHp2TkVMeFNJZU1DckxqV24yenBh
            dms0S29HMUJNb2xXQWVubjVoMG9XbzAKF/c/5c/n8dODdQ9a9Sw0xqvgij4X2Ij1
            iNKR0UfpZ0LfCVyKKufZlctbgPXBumooPD0qg+I2voftoQLQRgdSiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T23:13:46Z"
    mac: ENC[AES256_GCM,data:RMM0lbGiNvmurvqZstOz1MhgOuPgccCv0GPsFldhTIZzv/0FSp98ph1s+cT0hMOAwR/Gd/gZrkLYt8Xe4E9kpJc7hNk5p/mF8BdQJ8JYEhOebrEssMBY36Kd7w+hXQsXrmmp0SrSBFXX4BIye9DKVORzGMAhlGAK3tdoaNFbVHY=,iv:ouZgfBmWhTAkK+L07E52cbwemHncoRhjiDd9n4SyGvw=,tag:WAD7wEW8StsCHF9achMCpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
