apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-access-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:aLqhqxE3gZcAuZcPDdM6hlkfhevId7c9wLEHHSCu2GPTMoozRWXp6dpIVV2iO/I5/hZy9H7IAU0kAD0lq8O5dukgLCJBK2dV/H7liBZf7zRcXY6a3Osd/G8L5Z4Sgw==,iv:Gv6aoylyS58iBA/8+njVNU6DicsI45I9+QwVB4FZ55s=,tag:rPxNg8igK+WtW6is93izLg==,type:str]
sops:
    age:
        - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSmYrdS8wYndiWklBNmtL
            OWlwZzczZHp2d255VE5lZVp4VTJ2WHBWWGhvCmtKSTN0bWtJQzAzR0EzRE5NV21t
            OE5vRjdKZFFMT25jMFdXdEljeW54aXMKLS0tIGd4M3VBV0d3ZHhTNG1CWmZTVDlK
            WmFpcGdjUnJzUjFDTlZZS3dINzhLcHcK+G+EqHsw6lhw0ndgH2QtZT3VdOQVuC6c
            KkPXmq1Ly/Ao7RVQupnSXv6yo/o1eadRnueTOdeF+I4phziBLT0/nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T20:11:00Z"
    mac: ENC[AES256_GCM,data:rLkhqlViXZW5YhCJzhWjwIR2lj/BkompWkVZj/V0yJYpdK/AYbM5G2s1+EMkTwDL7PSqZoH6U+mUfYyNvcg0uKd466JKUMy1+Ig/a3jt5j6jxGJL4txuYc4yD6XPIzuKh2i+Wp7xJPgLDFHLlEOmNSM+pUPb5MGyBTEVK90xR7A=,iv:P8yCFB3HE0FBaK1bkzGhzmtkdgO41Iebo5k9QTFNaj4=,tag:bbgAl+RXQTZRqOHPZ+PqdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
