apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:9BQ8d8YINS5pkkoIaqMxRXZB6myAEF+HtuSHXe80+mwQlc0DPoIiMSD2IyepfTHIKBy7p0mDy/tJWt+yx74HLIIrU7jclT/X5ZB1,iv:8a/WGEI3qFWCnlLkGPRZ4u7tkgEDQkstbAzvcbou8YU=,tag:afPMeBHeC9FkqlaXhObg4w==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTXFGSVJ3Wnp4TEdwSWhI
        TlpEM0RCNkpJdFhIWUZCUm1YOXZkZmtYK0dZCnBwUjEzRGNCcEZ1VjJnbDJleVIv
        TXZpNlRjcllpa0JOUjV4WlhTTW5jRFUKLS0tIGxGTC80dk15MlJiWVZKVEpRUkFn
        alcvYUFaTGQvSWtYbGJibCtMT0lpOTgKJclFik+XlRcgEUri5Cin61d6A0FMRvwH
        x1vj04h0IixaSrz8Kw+dBUoT3k3byA/Z46HZyxYlmzeNPvcU8EwJPQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T07:12:18Z"
  mac: ENC[AES256_GCM,data:OCiP+g1x0Wy0XXn7Oaa53nKL4aV+vxuj+/8yqEx2JioiZHW8IEXjyLgiWEVn2LtNaG9hBBtJNNlR9gaD8lVcrH8lGnl0fvRCO2I82wkbscapywa82RT7zc2RMM72AF0o4r9wfJpL0k959S9tBip5bHlNzdZNviYKwMGHJeQ56lk=,iv:91uT1360pYfovsKQG/CIX6j7qWzhZ83ksp6rfWnhTos=,tag:XjYYXi3qtC4/r6VWZfn1/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
