apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:+nLQBCfo6TMtV+W7MFbVjUPtP/FnOUfKQD8+tftc6fIPVcA/ouvZk0QtuyYjcKH/s/GEQkCgrCbLezCMMvO+uHSE4PbUA+8t1zz2,iv:gAwyq7uFJvz7LEI55kMwVFSUeGXwo2yPqPabmakLsL0=,tag:0x6uX46XsA+4Xat0aAJb/g==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRXBaWHhWMGNYNFVQQ0JS
        aWdGVlJaRkNDRWxnY0FVNG1YZ01LSFhjdmgwCllMOXE3eHFFUHFlMVQ4TndUODZr
        b080d0NOam56eFc1bHEvS2tXL0hHd1UKLS0tIFk2cFBFc1ZiZUl1R3RpdEJxMzdF
        UWxURTBWcnV1eEx4Uk01ZVV6dkxlQTAKXJK95WZwCKruQtezM7cF5BzyzUOLpxVS
        XD9feeqvOvI3dguJpW6haDvpCWTmXdRSoi5YBQpZEHws55ZQEiW02w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T07:44:15Z"
  mac: ENC[AES256_GCM,data:e++VtfRWTik6O6shaHq4keVh309sfJeopPBB5dOm0qr2C5CKlc8hAks/0BDqcz9yL54VVu+Fi2Da3PaMh8Hyq1Gpn9/6pWDG5CbMRN+SIA3J42SZLVX318cSYpFYdh2O4KN+C/VE7H4TaUGWgeJdooWqJ/NZAP5yLVGJ5kADXDE=,iv:lNsAz71lGIBdOlCW8TMfBTRvEf5yXk6Ge1YjYr5WIhU=,tag:4zr12xrRA8hoRZOgFRLClA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
