apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:ThANTceFrmtS9dELyaYUmzO5P9ptypPqEAR8pvGXWb+9AFLAteeMtpubcoVwqQu/zbN/6gwQTPB4fpxN2Wq+N4LORHcBcKQwX0C4,iv:6VniHLhNW6FA6xnIkTno4WprRqroDZuWCuUG4lb7j2I=,tag:A3+TbVSB93+EeEEnvAwhWg==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUXJmaFhkSTlUbmsvK2pm
        eXFPRnYxRVhaZktVaTMxeG5GT2ZxV1B6L1gwCnQ3YVNRaGJVWDBUYkRPekdIUC9s
        clZlQnJubzJhUDAyTTJndzdSQXBSK0UKLS0tIGdMemMrYW1BMGFCaFFtOHBJRjdq
        OVhDWC80VzNYWFBUQTNDUktwOFJSdXMKZ+gtpuNcPpK8acxwfs7cXMYQrmkDUHn6
        9wZeqJ8sU0XeHaWYlkumWL3mpg4O7easTJDSsb9AXwV+DceX8fxvEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T11:25:36Z"
  mac: ENC[AES256_GCM,data:A2ee+TsNgw2WLNtg1suiny18PkPCJKAW6Q/iOJFCk052UhwAvf6rjuz7Do5jEedMzOlTWBLsJias9OsuQdJGSGH1VtMvJUUJQaRj2AmfFepH34S2CR66NCE/jCxt6QHtn5/l5/pIM4sehCbwNLySzbwjGA7zME2h2YHS3LYcHRI=,iv:Ne01c/M6PJRr2pMAAjwdtteSvQ3Xo+yse865l7IoLwc=,tag:8l4p8bth2613tGIvUXFp5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
