apiVersion: v1
kind: Secret
metadata:
    name: passbolt-secrets
    namespace: kube-system
stringData:
    password: ENC[AES256_GCM,data:tr2ewxMTuJK/S0JV,iv:xKsPQaO7Sla1wgqsi0hvdF7xzmadCuFis2qgUYvMsHg=,tag:q7hKv9q9E0/OhF4nH5cgew==,type:str]
    privateKey: ENC[AES256_GCM,data:bnAsz7gPsON9Im0LxieXRBCsvJe1bwTnx0GZX6+qlRpbrIuU0UTBxNI3Smz39q0pCAIxV++ixTLU4tbhZnYSYk/lFwS888QzstP+OFNIxquPXFDj6EjKYsVe5IgEuubicFDWQhgEYYITYXBmuBuy2sweA5TuVinIQWVKwH3+PCl7ybv5W9TGdqPLGdWSuQzFP/hv9wcrP5zbY9TcK08OgH8R0OIsldqyZ6DCy8gytdvVCK9gNX7qetg8kqz6Flk11mMMhdP1vosfSsFzEWbJAKnHwbWOP5zIRguf6TvgyYAfanTprzVPoYkpHckiTHSNdrEs62q+mRoldBbCIUV+k6J4wLW57HvfXQA6Ck8K8pN63lHoyfGtY9QjA5gfeEWtXrY4MjuN5Rb8j70pZ8+/b5gdZRNsnkzphH0x+VXVshng81BtlMuPWe6F07BOqVTn8qwgtng+/0lN09d9i0pVDZ1MDS5MTQ9ABzvNrQw2iAbFJyWaYru56eqvzhURhrO0P9KhSINuZHazKe5fvXC31wajxT7+uSRssINhUoL0r1m3OlqNEE7dMm2C+fxAnAoPHmec9lgH8lxFgOTmdT1x9Si9rXS/N5WcrruCtetfMmReCk4zIc7Y/tI4kXYdQgMiDk7H/yRtLLWf0n3CyD6V/4HAFCCud3SKFosVfPvP27URg5GFb0zGy+9K/56mXlQewVO+Jt4ZFQlhkCyeodhJw/sqGnilWv7KhuYODrbnYPBHRKOoOLf9EOyZsPq9p+cUVU7MM8GgM/Iv1UKCf5Xxm5zOzOJlxOkak6+FciMMnEnB228AIbF8HLKDL4Bu12hPOo1lUNHr5Jryu3kyiCmcRGuFzeyWhpIE/31P92DHFZwtgv5QST2LOBb8XTqt+07qzaRF8+CtLc2QbwmVbeDidIsTXAYIwr4dPKo3+R4nBlt68hqhhVcIgoexWicW9Gpn/fJT6INKzGT7aSLMbMw/Opyzmd636BFbpRrC9p3PyA6frEnkzUSuWsEc/iPv1nswXC8IIhmXKoogtQtxmTKqBiJurlvE29L8y3JIgC7C7Jcw7Z6KT6UhXRdioisbEUne8lDXwjPGD1+I9cqOxTJSTD3Iqlxu1LrHuQb0J0GpWaGni7wpj54kbFlc07Xat/73v8YWP4P9GO8NRi+U0fL7P06SRc8QdFRrxFeHx65Jerzd7kEL4cd16VukthUypXS7kJkNlNnyttEmnEP2F2ai1KyuESpc/dIqJ1Vx3uIqoWQEkkBsNQ12m+pR2m5UnxwSJd71IOCwfi5cKfAYGTcmwl5MXulprMsOeM41wN8LBegGzwQn9ekgNy7dj+m7MUU0yrhoVj6ZdHToOd/CJ+PzNQq8QSqAtmV/7Lx0dXBqECJv/6+J/N2jAvqVXtnPV04V,iv:+/qY9BVPLpP1cLjKiGMUmnvUuVyRzYZHW0kGsqZeLIA=,tag:FI2nbgnCGAeLnUWu86R46A==,type:str]
sops:
    age:
        - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSmYrdS8wYndiWklBNmtL
            OWlwZzczZHp2d255VE5lZVp4VTJ2WHBWWGhvCmtKSTN0bWtJQzAzR0EzRE5NV21t
            OE5vRjdKZFFMT25jMFdXdEljeW54aXMKLS0tIGd4M3VBV0d3ZHhTNG1CWmZTVDlK
            WmFpcGdjUnJzUjFDTlZZS3dINzhLcHcK+G+EqHsw6lhw0ndgH2QtZT3VdOQVuC6c
            KkPXmq1Ly/Ao7RVQupnSXv6yo/o1eadRnueTOdeF+I4phziBLT0/nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T22:35:37Z"
    mac: ENC[AES256_GCM,data:9pDRg/xcdyYpLHptXEcCTkBjLmB19gv3igkS1U7cGlVduayGIIBWMFXKDBAAte9AdVd1MNmG30w7+lrzi25r9P7OOVinvT+nldoTY09M87tUuJR9C2yhPjpTsvK89Kq+3oyPIEbtFDtcbnSucrNhufkIJQC0ziQ+2SvzqJu7raI=,iv:B+wSKv2ix8E/2l7kpiEN02wbC9Xnrb/+d8eWqd+onYc=,tag:ArRXdqY7QPNC0wk6ZA0n/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
