apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:C90f9DnETbFnKHzSgm8gtGz8avFBWjT9dFyJ8RZDk87PIckhRt1aWQ==,iv:3wpn+IypL5oewTiOnz6W8TwdPrrWsRQDu/kcyjOvkhs=,tag:wjCnMBGbtWnmc2VKLUjftw==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWWF2Yzc2M2xoT2hKOGpQ
        dWZvTm1hUmFxby9Uc2wwVWEwOW5qTXVBRlNZCjZEdDdqL21FazJnbmZsZ29HL3A5
        aElLcTBmT0lRZ1V5OUY5cnZPZ2did0EKLS0tIFB4KzRwZGJicExEYkYxMmZJcDIy
        QnpMMG1LUFhtM1F2a21hbUVVUTgvclkKOlmi8kEaHqZ5kaUCdTTVx1TZFUrhhXaR
        ZkHax5F4F4IW0W7z6nR80gEwuq4/tRHw8IYSLJingthuKXN9EqfxYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T10:06:43Z"
  mac: ENC[AES256_GCM,data:JtbkzRx/untE7Tx3fY4fVVZOEtscAMw+hSLjNmDi6D3yClvBGLoZlnyabSToL1AjReE9brzUA8UOg1FSuUIuSQV5YZEXAMQkPaThtEhjRrEtIQpJgApNlA8Sxo5L9bt7zsYV7ztrbDBRMTtLbdC9NKIDqi9zVIlKhBjKOTJLsYo=,iv:O3dgC30+H0wxUH+km6D33cLslqzJvpJXNLKH2dkqQ/M=,tag:9oyhI1ft2Qp5kn/qLFQFgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
