---
- name: Install jq on Debian-based systems
  ansible.builtin.apt:
    name: jq
    state: present
  when: ansible_os_family in [ "Ubuntu", "Raspbian", "Debian" ]

- name: Install jq on Red Hat-based systems
  ansible.builtin.yum:
    name: jq
    state: present
  when: ansible_os_family in [ "RedHat", "CentOS", "Rocky" ]

- name: Install jq on OpenSUSE
  ansible.builtin.zypper:
    name: jq
    state: present
  when: ansible_os_family == "Suse"

- name: Install open-iscsi on Debian-based systems
  ansible.builtin.apt:
    name: open-iscsi
    state: present
  when: ansible_os_family in [ "Ubuntu", "Raspbian", "Debian" ]

- name: Install open-iscsi on Red Hat-based systems
  ansible.builtin.yum:
    name: iscsi-initiator-utils
    state: present
  when: ansible_os_family in [ "RedHat", "CentOS", "Rocky" ]

- name: Install open-iscsi on OpenSUSE
  ansible.builtin.zypper:
    name: open-iscsi
    state: present
  when: ansible_os_family == "Suse"

- name: Install NFSv4 client on Debian-based systems
  ansible.builtin.apt:
    name: nfs-common
    state: present
  when: ansible_os_family in [ "Ubuntu", "Raspbian", "Debian" ]

- name: Install NFSv4 client on Red Hat-based systems
  ansible.builtin.yum:
    name: nfs-utils
    state: present
  when: ansible_os_family in [ "RedHat", "CentOS", "Rocky" ]

- name: Install NFSv4 client on OpenSUSE
  ansible.builtin.zypper:
    name: nfs-client
    state: present
  when: ansible_os_family == "Suse"
