tempo:
  storage:
    trace:
      backend: s3
      s3:
        bucket: tempo
        endpoint: s3.aknuk.dev
        insecure: false
        access_key: ${AWS_ACCESS_KEY_ID}
        secret_key: ${AWS_SECRET_ACCESS_KEY}
  extraEnv:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: tempo-s3-creds
          key: aws_access_key_id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: tempo-s3-creds
          key: aws_secret_access_key
  extraArgs:
    - "-config.expand-env=true"

persistence:
  enabled: true
  storageClass: s3
  size: 10Gi
minio:
  enabled: false

