---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.8.200:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.8.200"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "home-lab"
    ipAddress: "192.168.8.2"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/1e17720baa2217bdf64a7caa256011144fce07af5dd12ce18baed735789e7c81
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "d8:5e:d3:0a:e9:75"
        dhcp: false
        addresses:
          - "192.168.8.2/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.8.1"
        mtu: 1500
        vip:
          ip: "192.168.8.200"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

