---
- name: Configure vault node.
  hosts: vault
  gather_facts: true
  become: true

  vars_files:
    - ../config.yml

  tasks:
    - name: Set up Vault.
      block:
        - name: Set up and configure Vault
          include_tasks: tasks/vault.yml
      rescue:
        - name: cleanup vault
          include_tasks: tasks/vault-cleanup.yml
