---
- name: Set up Tailscale configuration.
  hosts: cluster
  gather_facts: true
  become: true

  vars_files:
    - ../config.yml

  tasks:
    - name: Set up Tailscale.
      include_tasks: tasks/tailscale.yml
