apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:FaQha1SbWT7+YSTX,iv:JaPGKj5u+Mce9E+f44e55JHHdhiwGW51lFi/+Jutepk=,tag:hvPDLs6JcdPmP2Jocy4agw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:nTXa+XjjBtwTsCmoxssObdYR5wZrJQ==,iv:uXDi+z9ss43KxdNxsGFofFQoAHoGD9CaRvjsxW4WGtM=,tag:ELFLytwO7CGmliH6kQXNIA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:h84n7kYK8p0noedC56CInoOYOx7K1LrPTbX+cdysExJKHkMY,iv:1VrFF6c4HDXMNwUegVF8h6he6RFf9r8lfhrttjHf3YA=,tag:BXJPiY1+IBZtg4MkEX0oJw==,type:str]
    SECERT_ARGOCD_ADMIN_PASSWORD: ENC[AES256_GCM,data:7HRTHzR56pL05AUl1/1EaJVgAuLizASbjY/ZGZBV6Lcd8oEz0BkD1XaJzCaroO/thSaA6a9uLWbXv0h3,iv:IX2hUJnnLELQ/wW3scy3ipaoZxWQucDFgnPkpZSjPSk=,tag:xa6Mrm9dhLdj1SPlFdkuNQ==,type:str]
    GITHUB_WEBHOOK_TOKEN: ENC[AES256_GCM,data:vWxzkY/mycjw2jpnUD5vI3Qzhqgx1O6eHDZVx5WuKyc=,iv:roVIkW18Fp7zETKJt5ofDv0VKDa0wV2VUF9eS2IgGGc=,tag:PgmFor6RQ5MviA/lyoLqrg==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:NfK/G2TiQQfVkMfU7cQ23WmCjJ+ZY8jRM5h5xXjuj+5LYZYSxLurS/j/sZ5rPbZf2DfQYlK8ZZENFTgeIuc=,iv:S6fXG31N1U9uCbOMsiHLD+cWeWdpvaBr9b7v9eVbJnQ=,tag:zfLHGyDPDsUfhk/h6PzdVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh9qxg0nplvlncvld27lg3h4f3epdsr32vuxswtxn95fyhj04ufsuq9cl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bWhMQldlQm04NjA4ZHVJ
            TXVMNDdXNnYxR2hRQm9EbUdaYlRnRU91SDIwCnV2UURoWDNxSjZ4TWVrTE1yTUhm
            eHBKOWZCVXZQdGdmVDkzZVFrdmdVeGsKLS0tIG5vNC9wQzlOb0ZYTFZiSURueExi
            TEk0MW9UU0kvRE5CbGJjOXI2Y0F4aTgKVi69tkEz0AFN/UwJFvSV/Yrqo61tZErg
            j3eersnKVk6IcgJydmpyjJUHlWKzASU2xwDub+poZo0hQpkXN2fsPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T23:06:48Z"
    mac: ENC[AES256_GCM,data:5BEuU6jTXEJA4L/suZkKcUm11TqNRCaq5WQMAhW+ozaBjcEX84c7jHjRgjj1LeFNid1oi4b4u7XtPMwFZcPt0VwXNEFCF0eZgGKQFU0WTXG1i6MuPUdZQSo3Zlu8JgfZOQRjdFSsxb5RVFTiK7tPQuoQuYMDBe+Jj3vEUI5uAhk=,iv:y83pPJOLgqZc5LOak4eRUEX9mYwRFWp46amcD6RFet8=,tag:4ned9Vmxg0tKqr6MWjVefQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
