apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-access-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:j9hxgxUqBCtq5iZDVNMnD4Y+OqrbUMZE2uQoXqS2nEV3y2ZDIJeR6w693+w9yA8Ad4GqB0m0drkNQP3vD2j2F/7gPmJIhx2Xr0JRoWgqaqUaTYtEY+JqBtMVf4gdXw==,iv:TQbxeV0ipsCapjhtuzIRPYAIP1tkymQu1ZAMAQO4srg=,tag:0LqUcH6Go5p4qjEzqD7vEA==,type:str]
sops:
    age:
        - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSmYrdS8wYndiWklBNmtL
            OWlwZzczZHp2d255VE5lZVp4VTJ2WHBWWGhvCmtKSTN0bWtJQzAzR0EzRE5NV21t
            OE5vRjdKZFFMT25jMFdXdEljeW54aXMKLS0tIGd4M3VBV0d3ZHhTNG1CWmZTVDlK
            WmFpcGdjUnJzUjFDTlZZS3dINzhLcHcK+G+EqHsw6lhw0ndgH2QtZT3VdOQVuC6c
            KkPXmq1Ly/Ao7RVQupnSXv6yo/o1eadRnueTOdeF+I4phziBLT0/nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T15:23:53Z"
    mac: ENC[AES256_GCM,data:UqVnEIiNzzpRAwRMosR7qLtvt+f3l4981LndoGRNjfl9wHA5FyvKEr4JltJLWEXWfc/NdAd1DWZugInUW1b0wgEER1lkLDzhLGXp7/fVzG2e1z/J37xRgvCBl27X0E1EFkWYbauWych/P2JJAPh/Du2zsKKuReTHWMsK79eg5VI=,iv:5I4O3HdrBH6p609pRwDNK7KH20dOIm9/EXnVF8Fdtks=,tag:EmmlkBns3W6BBgKdkz6p9Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
