apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
  namespace: external-secrets
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.eu/api
      identityURL: https://vault.bitwarden.eu/identity
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: external-secrets
      bitwardenServerSDKURL: http://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        key: ca.crt
      organizationID: edd761a7-3202-4f75-ab0c-b31300c6f81d
      projectID: b4232da7-dafd-48bd-b9f7-b31300c7b542
