---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tempo-s3-secret
  namespace: observability
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  target:
    name: tempo-s3-secret
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .s3_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .s3_secret_key }}"
  data:
    - secretKey: s3_access_key
      remoteRef:
        key: PUT_PASSBOLT_UUID_HERE
        property: username
    - secretKey: s3_secret_key
      remoteRef:
        key: PUT_PASSBOLT_UUID_HERE
        property: password
