---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tempo-s3-secret
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: tempo-s3-secret
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .aws_secret_access_key }}"
        access_key: "{{ .aws_access_key_id }}"
        secret_key: "{{ .aws_secret_access_key }}"
  dataFrom:
    - extract:
        key: bc7ddb89-0509-4464-aa2c-b42801206116
