adminPassword: ENC[AES256_GCM,data:o017fg94+nWfBIPV,iv:8ucDu0iLUhQZcno7GA3j3W9I42xS09nz7cb5xFv7CRQ=,tag:tWE8Db/EyZOlWHfJps6WBA==,type:str]
envRenderSecret:
  GF_DATABASE_USER: ENC[AES256_GCM,data:vF95v90=,iv:227N1sjRwaemy2pKFemu1TWyzo9RPkUJQqb6+sT4p58=,tag:T1770wok7g42HbCTo4a73Q==,type:str]
  GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:L7WxmR27n8pWGaAM,iv:pyN12YbusfuR/E5Xhi/qDv/wp4YfYkcVWJFCIn2Qy6c=,tag:5rQzBmz0/pYFzM7cchtdFw==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:4Do5dfWG3aJacTcfRdJVp4RPcdTWKTZW,iv:Mc0lmWh1QpHGdjNMnfhLtiYFUJQpRhYMXsT/Ijk0dHg=,tag:3qWYF4D8SBt2XfdNxqAqww==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:E9+6SOACOKzANhgwwjPMZVz+TeuBPQIqzO/copNQalMsfUYxarGAK5cpSOk=,iv:pUvJh7oQNWSflIF/OZ/pCty2RLicXdr1Er8hpjVC6DY=,tag:2jkpGwT7q3S2u5XosoyPog==,type:str]
  GF_CLICKHOUSE_USERNAME: ENC[AES256_GCM,data:eBhoCiY=,iv:9mAQZ7FUR42/hbbYWRrARd6RM4oOdAsRwfR5ZY9oSG0=,tag:lFFcKPIPi0+eDeUZszsYdA==,type:str]
  GF_CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:68KdHZoqtisnpMvV,iv:9jxNl+R9z25FOAAydhXmhdc1X/4et9N1N8hxs1rRoUk=,tag:hweXst0SaQPLyTBxztIffA==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4M2lHOENPMmZIQXhRNmkz
        YTdLcnROZ25hY0wrb1ZZeXgwZS9VUUp1TndvCjg2dSs1TDE2b21ibWR5OXpwNFJS
        bEdhd2Z6WUJMMG9KcU1ob2o4SjhkQUkKLS0tIGJyZ3dwcVdJQWRHamJTMmN3azV0
        MCt2SWw3NG1vM1FaYXN0eDJtU1UzV28Kj7xNrDORkOVM44U7nfdHrZLkFyF8UhOd
        3MAAynX6JoLhFU630Psp5u986Nam2e2OiOoVUBWB2h1fFAFQemvhIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-01T14:58:46Z"
  mac: ENC[AES256_GCM,data:TQ8BPnmGu9qzCdVJ/dzy/crOKY+DEVu2xzvzFYerXvsrkLyN+o/1c3u2fXIKb7s8XqKYklbnINKpPBbtpS0K0wmvVIATWFThNLYGld1mHcQ0cu7ioE41jCbGDD3fJuyP7zOaqTO8qjBTY3DmFmAUJdogns9Eu+3WUTnKlzDQ7Ig=,iv:nx5GNbLtUZSu+FSlv/mf34RT+yPqK6gugC7BDypJHuI=,tag:QorcHWjcmRpZvtqYWsBTeg==,type:str]
  unencrypted_suffix: _unencrypted
  mac_only_encrypted: true
  version: 3.12.2
