apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-api-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: truenas-api-credentials
    template:
      engineVersion: v2
      data:
      api-key: {{ .ApiKey }}
  dataFrom:
    - extract:
        key: 80db377c-daca-49a8-b74a-b42801215638
