---
# ServiceAccount for the CSI driver
apiVersion: v1
kind: ServiceAccount
metadata:
  name: truenas-csi-controller-sa

---
# ServiceAccount for node plugin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: truenas-csi-node-sa
