apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: signoz-clickhouse-secret
spec:
  refreshInterval: "1h0m0s"
  target:
    name: signoz-clickhouse-secret
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  data:
    - secretKey: password
      remoteRef:
        key: 9d03ad48-2758-44ea-a203-444aa76f2b02
        property: password
