apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: signoz-clickhouse-secret
spec:
  target:
    name: signoz-clickhouse-secret
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  data:
    - secretKey: password
      remoteRef:
        key: clickhouse
        property: password
