mode: daemonset
extraEnvs:
  - name: CLICKHOUSE_USERNAME
    valueFrom:
      secretKeyRef:
        name: opentelemetry-secret
        key: clickhouse-username
  - name: CLICKHOUSE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: opentelemetry-secret
        key: clickhouse-password
config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  exporters:
    clickhouse:
      endpoint: tcp://clickhouse.database.svc.cluster.local:9000
      database: default
      username: ${env:CLICKHOUSE_USERNAME}
      password: ${env:CLICKHOUSE_PASSWORD}
  service:
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [clickhouse]
      logs:
        receivers: [otlp]
        exporters: [clickhouse]
