mimir:
  structuredConfig:
    blocks_storage:
      backend: s3
      storage_prefix: blocks
      s3:
        endpoint: s3.aknuk.dev
        bucket_name: mimir
        insecure: false
        access_key_id: ${AWS_ACCESS_KEY_ID}
        secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    ruler_storage:
      backend: s3
      storage_prefix: ruler
      s3:
        endpoint: s3.aknuk.dev
        bucket_name: mimir
        insecure: false
        access_key_id: ${AWS_ACCESS_KEY_ID}
        secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    alertmanager_storage:
      backend: s3
      storage_prefix: alertmanager
      s3:
        endpoint: s3.aknuk.dev
        bucket_name: mimir
        insecure: false
        access_key_id: ${AWS_ACCESS_KEY_ID}
        secret_access_key: ${AWS_SECRET_ACCESS_KEY}
global:
  extraEnv:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: mimir-s3-creds
          key: aws_access_key_id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: mimir-s3-creds
          key: aws_secret_access_key
minio:
  enabled: false
ingester:
  replicas: 1
  persistentVolume:
    enabled: true
    storageClassName: s3-mimir
  extraArgs:
    config.expand-env: true
store_gateway:
  replicas: 1
  persistentVolume:
    enabled: true
    storageClassName: s3-mimir
  extraArgs:
    config.expand-env: true
compactor:
  persistentVolume:
    enabled: true
    storageClassName: s3-mimir
  extraArgs:
    config.expand-env: true
distributor:
  extraArgs:
    config.expand-env: true
querier:
  extraArgs:
    config.expand-env: true
query_frontend:
  extraArgs:
    config.expand-env: true
query_scheduler:
  extraArgs:
    config.expand-env: true
ruler:
  extraArgs:
    config.expand-env: true
alertmanager:
  extraArgs:
    config.expand-env: true
ruler_querier:
  extraArgs:
    config.expand-env: true
ruler_query_frontend:
  extraArgs:
    config.expand-env: true
ruler_query_scheduler:
  extraArgs:
    config.expand-env: true
