apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-configmap
data:
  config.yaml: ENC[AES256_GCM,data:IZ8fIQRNdhkQ2c93z0xduyFzRrw62RFnzQqzCSKfb5SvcdfFY7BPgWMZgK/c93/eP4mDy52l9uIy/O6zp+jQu88OcInB4I3rwRZoq/4J12GEXZv+lZxd+F6FDK7Qnv/rEUtwZ4C4h5neBtdRhOCDB5HgF7uf4NGieNuSXwX2DismNyWjwfvxGCkciyq3gnO/webIJGJ8IVmU0w0EPi61wMCZ1lnnQT4eZmuauUJYlPAZKfRtZu0/S1S+Gtf2DXzkXBIfhhZQo7U8IasrsUzJfxYXYwrlgR5qCIaV55dT2RquSyuPP1uhyDbVi0MKT+Nij5s=,iv:RKqYExgRHi6uokQfZgv/WGpgMU1GuFI8ucA2/PHLF+o=,tag:H5DGt0m3kG4KcarVkfswdQ==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZOEpxMFF2eGRzb0NSeUUz
        cnlLUU9pbUlacVc3c1dnSHE0RnRPQmdzRURzCkhpN2FIc0R5VFVDK0VzK2xzc3ZC
        RnBjaDA3OUNQSk9rNWpkWU1nTkhvMjgKLS0tIDhjZkMyakhmQmNlc3l1TmhIeTNi
        dFIvZmNLaWtSbXAyUlhuN0JKempvcW8KMHwykf8G6hjXYfSOBa4W34sL8t9MgxsD
        85mm8RVM9FxT6uJggwDFDS3Gtk0UMQ/cNljVc7hJGPmloUrQI/QJDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T21:19:20Z"
  mac: ENC[AES256_GCM,data:rFwGZ3wb3+aqie/pIt5jVZ3Ht1IoJt1RoiHIsolugYn3+kBRY4mmVUjHqF6ziEij2yOouZoQboOzntyPj6B6c/LInptWTJQw154pazD9Rp6goavPe0MnA+w9gk6L2e58glbBf4KEYfL3GOVQpe43pkMsOAm3kgtk8mWeDx+wAZg=,iv:ppzIA1oAAIpecNyTl9ot3Xebe5lSKjQx1sRjERTi4xY=,tag:E8ar5gDON4xuXef+d1mVdw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
