apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-configmap
data:
  config.yaml: ENC[AES256_GCM,data:AnfU3VMgclaA08+ujFWzziDddMZbsVj5eryYnRvefBTOFcHmqbIqoBS4xGddfZu67+9YkUKRpCycx4ElcygSzzdJtxQRKFrYb6aUQQ1sv66s0gAzZROSxsAq15+ZYc2h3LHU0KVDxVQfv53d0UyzsJtTLhzRrOCg1W3DJPA3pMrpmkazgcvrDO2TdrkodgLE2QG5RsLWtG0DpFGFD6YtgM8KyEB1ZAmha7OJ8rmhorNG5jAcnhbwnyrW97neHQRBfGkjZ0EALr2HlPK1pUr9GJ90/Cum1WfoqEucQlHMOhw=,iv:otmrQ/0mQb32wReilubmVqRHU3OAR5C1VAMYjdu6dSc=,tag:irSYyb84J+EUTKb/bKaq3A==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWjFWNHRJOFFhaVZvTVp6
        OFlSNEhIZDVOTzlmZHFOaDAvbTQyRlIvWGpvClM2dmJ4UFpoVXhqRmN2NUxtSlF0
        bEY3alJEZk94cFFlSmU1eE9LdXFUQncKLS0tIGt5UCtua0Vnb09wdks2NXhkWW9Q
        T3p4T0cxcmRpVlRiamZRZ0c5RC9McDAKCURSLoImcyduN90I+WrK1PPl906cxMIk
        SEjVEkyfi+c4wnURopgd33WB9M/MZNGIXr/sth3yCjYbu5TjluInqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T07:44:15Z"
  mac: ENC[AES256_GCM,data:Yxby0rSUjSxyhnQkjape+8YUwW/Q9W2Z/APzxnPhnAZzekiGtaV+Ot8DERfxcy2q31avOHjrcw8iG29ZMZzDi/oST16/rSp0nHl1ZdUq97pcdeG9UpfOuqas/dmb9wUrpiBcPjBMm3YzbcN+MKfXm/5E1ys55rt4IiVrznQdwQQ=,iv:z18lukYptmwAkh848TXmUfq72C9bZFWiPRrTwrBn0iI=,tag:ydn4wmoDciDQXEcBHfO0fg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
