apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-configmap
data:
  config.yaml: ENC[AES256_GCM,data:m06PN1akb/dxerZZoABEdu31XkoJSrqCERYx8+1lC2NKxFRzG0nyyx/BuGBFPICfejfiVRRAOoxFaUxyqGUsrwda7tUYSLZhHqMtvuxZ4EikNBgUgAppsM3Vocpvk+7DyMVmi0hDupKF9rKVPRRAMYBeBVGZNG4hQR0x+Cvfy8n/eg/Xv+afxaUiNbjerO0gXOvJk04YYvpuY6e73PmBs444RnVPnxv2gNOyoxcaZAOuq1fCDkEGVn+MD+rpWkYswAPE3nSFZLRo4qjJ4czJ283MxNuk4guxGScyUf34zn4=,iv:pG4uuYOKBy+ZjW6ZL5zm5bgnv/PTP5kIMl07xBYQrx0=,tag:nj0hRnKseioITQxwCBo+WQ==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSWRVYkQwOEpCdWRSQ3Z5
        NW1oclJ5RTkrMXdhYXk2VGdtSEpCeWlHbXl3ClA4TnZuU0xKUjVQRURidHVmN1M0
        UVh4dyt3Q21PSG5MeXNrL05wSGtxQkUKLS0tIHAzdkpmNWE2eVpIY003VXBySmhQ
        bEo1a01GZDJqQnNOQWUwdEl6bVNXeUEK5U/hAtsDGnUOd00FYtEQ61DAYO0LG2Zm
        1uKfXlNAI/IvDJROapwz0rRvj5nOE4Gm2akeIJZqvKss3QRtbyBHLA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T09:20:55Z"
  mac: ENC[AES256_GCM,data:EBo85zsBMC3PlLQIcbrk2b7mdTtIN1UmGIRDt4Qr+dCoautjCEPTLEuweG+SUpepKKkDHjGgNvK3TpCcm4zIfj4Fejw/MoenWPTVlEacKLfeZNztwQbr+f6Je+PLZ9kfu2ierE9rTO/qDdjuLuzW4x+b+qPybM00nZuKZD4KCF0=,iv:5LtjTPewX7LgROTW6/TGjxHoFxnqUeDMhpfACkxyYII=,tag:qFW6PQ+DKB+o1gH00lNspA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
