apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.aknuk.dev
      recordType: CNAME
      targets:
        - 82a675b2-425d-4816-965e-b81fa9053660.cfargotunnel.com
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRnhzWnpzaFlOWjNmODF6
        TXVoZ2xWNGJCSUlkSWR2bUg5VmxUSXRnd0dVCmdBNUtRYnRvSE9rcncxbXd3MytJ
        V3hWOFlYQVJwckR4aWliUlQ4aGxuS3cKLS0tIG9VSzBmNUZyUmNvVkE0aE9MWlBt
        NzRSellHKzNlKzJ5NVZJK1RVRlE4V1UKV8yl0RC7b1Xrv/AERegtYSG5Ikp5p16n
        9JahH+3itVjqKhXi1Ha33uWumLDLbJjpslbjIfWEHZhLvkz6g3OFxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T11:02:57Z"
  mac: ENC[AES256_GCM,data:Nd/J2vD7P3qyU7dsWvRUrKnc81FATSmKQLpuaX7MTVfB1moDvleFvlAlN2j+LiF0fBYnKkPY7B8VP1mBEQI4SM1AOs09BFP/h1y0mI0asNZ3G5Olpmc0zsIsblEziZKOQnsjVpgm4CESOpU3tVVNzs8UQW14GBQXffoeax0OJ2I=,iv:TZM1MnzoziFJhi3+o+Wa1cYPIVKzB2UqSPyY3Kp6Csk=,tag:fjP7ezDp+bnfIuuBTDKw0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
