apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.${SECRET_DOMAIN}
      recordType: CNAME
      targets:
        - 31b8ad46-ea32-43a3-abe9-d48783f5d628.cfargotunnel.com
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE05Z3RHcWpW
        cnRQUmp5ckovSkdpS0VQNjBIOTAyNTMvTWc2dmpneHZNSmFNcXp0eDYvVSt6S3Nv
        RzA4b0lUQkVERUw3Nk5wS2trbS85TzEyajJxRGQ0K1U5bS9pVFgxT0Q2aEg1ZTRt
        K0dKTTF3ODlWMTZEeGVwTm5kbVRYY0VINjllS3RTOGFiVVowSlQyTEE1Uy9KQUtD
        UGIwLzlDc09mOUlFMTBHUjdKQkpFUzE4U0RnMitsV001NWFMNlRlSDFUdEgvcWEz
        Q0c2aWh0alF6UUl1R2llUk90dTZtdzg1Qm42MXhKSnNOVVo2Q2swVTNOamhtazVS
        Y0dmNXpMTGJ4QktzeFFWRnZ6VmZzMVczMnR0ajBOdlRURld6VVd5UVFuSStpUGxS
        azFyUnZoVTJZbEdXN1BzWWkzRC9MUlZjRzZ4TFNmQWlpcmQ1UW8vL00rd1ZSZkxa
        QUVxbEdLMnhuMU5KVFZ2OUZHcFVlRC9kclJJVmFnUTFGNGl4SHlaOHloRjl3RUdX
        UERySFJTdVZVUUJKNXdGVEU4U002TFM1Z09YNTZadFBtVlZGR3N6M01DQkZ5aG5C
        NlRLZm5kMTY4V3Y1eHE5RFdxSFBuOFJzeVRpRjYrYmRwbWlZRVUyaVBvZXIxNkNU
        dFRUazliOGNTRUx3dmtzZDFtVE9YZG5RT21TcUxZUDk3V2hISEY2N0Rzb1dEQURk
        cFpCbGpoS0J2U1RtY2FiTVFPUG1nVTNiRSs2bVNrTVVsejNPRVhNVTVrc0FpZ3pH
        VUJZY051KzZUaCs5ZVhNQTJBVzBjb0RQaHdkOTZDZHZnS1BHSzVkcVlNc0VwMWF0
        VHBWNXY1TDY2TGlLZEg3OU84WmwvZFY1NDcrNGZIU0M2VHp3SDR6UVc0VmFVczhU
        WW1RbWVQUWVPUXg4UGxaa1pjTUs5YVkrZ1JwajR3RUZmbE5QdVVUQkwvSVVZVmxv
        R3ZFcDNjaDFDc0N5TllHdmxZYXJBM0FjRk9uYi9zNDRNdytHaXpGVVNFT3lqV2Fs
        UVpKd1hBRi9PZk5sQ3FpK1pQNmo3Z3pCbWVDdzlOQXFtRVJkNGhaeHZ0bDRCNmQx
        OVIya3Uvc0xrWURTUHN5NWpSQk5aR3dXSmlpL0QzVDRwa1Jla2dxSEk1OVM5alN1
        VExlQlZBNTlYc0VSNlBPdlk5dTZqcjdaMUwrVkdHTW5OZFY5Mm00eFhKMnNhRGxu
        d2ZvWFVpK3BGQm1GQ0Z3bFFLcVlTUXlUVVVPc1crTVI5MWJjbjhkcTZTeit1NmRU
        cENDbWc4SE9QRWp2TmUwS0hCNmkyeUNEVUpOVUlFV2VYbEFpOVlyb1BiWHdQeWhS
        WGYzMk8zTS9xZGdZV1NRamp3WElreXhVMmR3emtXT3hQdUhvVEgxZnlzNnZmVHpi
        V013dTVOVVdaaHJVQ3d2Vmg4VVlVT3lRalBKSVZVcWV0VCtYdXRnNkJKdExiL3dq
        Nmk3a2VzVGVNZ2tIY3BsTUZPUWRPZFhhODdsR2hQcEJQSHhJa0pYdXJaSzlRaElV
        bU9qcnE4VTJZV1VzcDFYMlB5QnlGSTMrby9BZDdKdmxCcG9yRkFvUDg2YjBjbUtt
        QlFiVTVSelZRcW5qNUJYejNRV2VKd3VRWGFZL044ak8zTnRhbHd3eE01aTZNQ1Bq
        YSszMWh0UDRMZldCNHdpb2VlWVlZWk83blF1ZEpGdVpvV3Jpb2t4eHREU2tnVG5J
        SUl1TmVPejNUYWFNNDhIVnFGbS9DbThiOU5XT2xPVnZCdUtGWmdCQklhTHRjek5k
        bzAra2Z1bVZpUmdnOFRuSE94bytyaEs4Y3Q1NzA4c21TV0tDVjM0aVhnZzlZK0pq
        eU8xMVo1cS83dTU1UjhlWGhmR2RMdS9kcGNTaVNiZTVKZ2VHN2ZCdWl6RFIvd2FR
        U09pK0p5UjFmby9RN1pzR2hlM3Z6MkZlbG9XUzB3cVVXVytxTTM1UFNTTnNQUQo3
        d2FraW5pVHVFU05YMTZXbS9LTklmZGV6a1U1L0E4SXFzQlhKSkFQRjlBCi0tLSBT
        OU95NERTUW0yOXhSUzRlVHU5enlmaXhWcFErMTJTVlQ3d0hFdjg4ZkE4CkYWUN1z
        kkWp8ruhqUGprX2swQEoIJ6OmjmofPTaC6dsq+kj4HTzei99vmng5wXekM8f1UIB
        hPvCYexj5At3bEQ=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1gt53jawqp8al0dmpzf39qxpmhux2g9sqdylryy0h2wqga3e0y4c4vd8f552gsnm6vpzskcpn37j4ma9vrpz2h3z926kxzynkxrysdgug5ykvx4pxvuvwm7zcgk43r3dtwnsj8demqf663j48tdx9qfa8vzd99nzcu2y8u7ej4amrw64qetj4hp776txdya5xgrfyywvp9dtun8rk3jn4y0zk5un4zjeewxegfd9vevx5cqxryxvm8dtg3ppdxgv5vfa0jwvk8l6z3h46f3w9z628sa739ddsuumkdwjg8s3c09wnl293hxz0dca9ttwztgtqhpjnj50sxu2sfxdcc3l6c7e5rw2uqjsq2dmgnmxf3v9y27edvafmgssckv6my0z9hkvzdcdafxv7pynel0xyjfan4ennwgd7j9yvg7x8ueahgjq5rh4eq5u4whzwknz0wgz4ccye2kstjazhttmqmnyezkr9t0mjlgskezy9836vrnxd8f47d228zvrqjf5swpxz7zc6dnp4zumn53w655gdyyg3u0pvtj4a4akvlkgey4x7wczjjhyuka5m7zy99w5r8vcknw5zswutypy35dnc4qz8y97dyqu4nw307xfv5hjpuyjc5wkfrtdy7ae7ws5awhwxyk4625594g8ak3eqztqcc0yyftdeq97ywq7va2zkx72733jvjvd84nmz2raxe389gx35autg0ucqnqjtjz6wmwaz6syf23gna8mtk7pptpc20pp3vef35qvrldhgzumccrs4a2vfaxawddtm6rdytgaxenzztdhr8jmufcduqk44ge9xslnqdpagh7477fv60p5hy5ayg4zum38qf8xz6ddmer7qrt42jwatzwqap6ndzhn5fxs2d4nttr5q57gy7dedlra55znsg9cez4zyy2vctda78n53dplp845re35kr305ua9dy2mngxzmhldz3nqg4jnslfnykd9ftc2pv77t9pm57y5cujdkfdc28dreg3pyyz4vpsp7au4q87efpuv25vkfxsrt57rq04su6smjpuvmypnqdrje6duzxkf0dvmgf45kfpsxqyvsvefd4ayydgxp6hn4huqa4rdmaqxw0a4n8ysp7uqp0e7m26v5ksxxjwantkm3krw4jh02j97yp3j0dv2y5qcgh4xpq7djs5ysgs5c25q56t2r6m2trxfuqmgdfz4jy8ydmpx8fmdpk6ynf97pswsdq6tzm8drjvlv308c30ej2wmk0pf92mf5qfqk348hg00wnx5grqygxjpzqe8j2ejvwvvdufhjqs2fyp4r8x0fqep0g6r7cfn0kpn8e9qyskjqdlhu2ugek0qd3d5vnwt94lv600jy4qhuz587pc4vzquqe66sy7ftwfzz6jnzpc267s6t8naz9cga8psee2gzc2zywjnm5rl489cfns9c59a29qzlkns8wujmg3zvdvkn5xfdlqaqe8qn28sf2x9d8t4xzsdzqk667qq4srf4kcattw5ddgl9n94rrk454y3efwzhsa5dyxsska9qpamj93z6rp7jfw8cgjgzws6a4jnyk8xp5t8ugjsxxquxxcz7pzyjx2u38dcjggqzqczuxrpfmju9ek0243pat2pquj0hmvv2smjgfkvr5mdzn2zvse5hrg3t8v992au2n8gypzdqa2s3p26kjkqjt23g4g525mttu7rgvuavd94rd8l4gu46egp0l3k5rgs467a3tl83gzf3pzn6ynru2jtjsvkt4ag3qqejqd7mfvpv3668w5rrnk5re8lqpd33fyg9ee4np93eql4thvx0kggyyfmvqy9fuckqj9lzgfdyzrgkmq6hvhj277j2qyqh7lrn8ya7v9stp8q65ujuffstktg3xnhah3g0fnqul8k5y9eckc540jc5fyr8k4r80vasq0x0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T21:06:19Z"
  mac: ENC[AES256_GCM,data:4pDsgk1Qkm7y8inNUlukLYoafqt9PEJxy9JELxY9Xxr6xEy/OFc1QP889j0Ld73XItrfHnIZ6YR90hFmq4mlI8ZT+Q78NhZXvxUAKDbseMzlQvs2sEpgQeDXVgMg1h0O6iAxqqTgx3LgD90mp25x5pRxcuhlKzM4KF3ZnYeAVE0=,iv:z06sO7nwSW2xAKlVOD6XnTBfNai0pm23aGTEEvVuRRQ=,tag:Xegn3fJSdqy36AimtoIpdA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
