apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.${SECRET_DOMAIN}
      recordType: CNAME
      targets:
        - fake.cfargotunnel.com
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IENFQUtJRFhn
        dXcrQ0VKMmcwMDU0TE5QVEs0dmp4WksybXNkeVMrYjFwVEM4OStjc2ZTS2tQSSs4
        ME1tdEluenY1SmQwR1hSd1g4VkUrdCsxOWd1ekNNcUFkTmdUdC9nNEprNjBwbERQ
        U0F5TXZLdWJiRGwvR2JBOGRIdEZXMVpaTDIvbHpxYjBWZUxuZ3ZjUnZTa0FGUmpZ
        cDlkZ3hCYkhHNmsyOGNCMXJDM2NoMEZaRllqT3I3ejRDTnBxVXRQeUkrU3Q4ajZQ
        SHoxeE5IeUxpR2NpMDJmSkJpR0VJK1oxWENaWXhtVFVFL1BJL0VVb2liM2tWalVW
        UjA3K0Nqd2tBV2U4OWFiMFZxcU5VbkhCenZ3UVE2WFR6aHl0OFZzYmRMcEJ0c3FZ
        WHliVXRNVnZlTmxYSFpxbmgyamd1UGlqNi95SXNYZ1A1RXA1Y0ZUZjJFN1VqaDZQ
        RWpiODRNY3BXUFphM1phbHF6cms1ZW1EQ0tMQ3RxaVNCN0pSY0drVU1rOWdiUDNT
        TGExc2hzY3lGa1o1OGJCMFRzQkJzWTVkVG42RzJ2My9nTExtajdhczhJdDNGMDRG
        alpXZVhsTWd6SHBOR2lnblVjSUZYdUorSjRaRnZvdmFLYVZlUUZ3aEgwbkJqQlNo
        YkpFalF0N28wTm5RZERweGFoZjFMSUdZSFFINzRmTkRIS0lUSVJiWVYyUEJXaGNL
        TE4zVkdvYmh1ZStQT09QRldOODUwS09ocm9SK3I4Z2UveFlPd2VPZlRiUFZ2TVdL
        eEl3TzN5dmFRNTJVd0xjV1htSDRySjE2L1hzQkJlVnR2UFl5ZHpGdFFKUkltdFBp
        L2tqS0IrZ0FBbWRkV0NldDMyU0VIaEg0djhiRjRmWE40Y2N6aW01L3lDeWtuc2s1
        WWY0WXlBU2c3VHNxdGhIOVJwUDNDY0JITkkzU0tZemVaWDVUSjFBa1ZOazV0V3h5
        eSswQWh6QU5xK1VxVTlJRFR5dXcxbkZsMVlNY3Z6V2g5Zndia0pwUE1BaGV4ekpJ
        OFFHRDZQdS9JcXpyVk1SZXBUTzNsU3d1OXY5STUxVnlPWmVFZ1Q3OXZoQ3JSQ29n
        aTI3UkRKMHdxZXNBU25nQ2VCZFZYdDVLbkJCVGZXeWNRUmFQNTNiNmQxWmJFNlFN
        U3RKSENXV2hZc0FSL3FCYVFLMHFBNVljYWdYc3pTc2hFUG9Kby9ITVg1MDRYL0l5
        MlRFYjdBSEl2UVE4N0k0WmRjajMxTzZKTCtYcnh3K3k5YkNoSHk5Z2VGREFFcm1H
        QkdLanVtQ0hqMUduWHNiTDdLSy9sZi80anJtWSt4QmcvSEpLM3pTTHQ4LzJBNU5p
        MVFoc1U4R29mcUVtdDkwME1HakplZ2dYMzN1bEFYcDNPeW1GQWZlamRxV2ZRU2E0
        Mmk5L1lLL0RyU2ZpZHZQdjZnYzBzazBJdXZ3VmFYenF4cTRDbm1kbWZ5UXRDVmZK
        c2Nvd0RCTmlUcERoVjJUd2NPL1pKRVdNRTNFc01OaitCZE1kdkkxckNUcFNqVDVz
        bCt1aEZnL1NLTnQycDAydGhKMUs0dnZpb2VsU0VIUjF5VEtMdWlkUHJGYWxCcU01
        ZVZ6bk5tSG5ZSmRseldpWk9MSkVidFdNNWh5M1NrRlFBVGwyQ2JTY1h0eVBVS0hx
        QURycktZcTZKRnRva1A4ZmwrdjVQSm9GMXhaL0F6d2xQRmRidXBOblp3V2grQ1lQ
        emY5cXFpUEZtbEk0M3B5U3dKTzBCRzFoSTlKa25YMEFoRTVReDZHaHgzb09pZnFx
        Q2tRUDdwOUhvY3RHTEFISFlZK2NEOFJZQlFjTHIvVHlCRmpKbWhZOUtzVkNQWVc5
        Q0lMRlF6Snk4SzIwRjZtU3IvclJ0UEY0ckZSNlgyS2lsWE5rM0M3VWVPVUw5S0dY
        NkZQT2Uva2tmQWRQUG1YUm1kWER0Vmp0REZITlNZQW52aG0xcVlERVAxN1JJUQoz
        NnNLSkducU5LNlBuZTlRNzFITmp4QjA2RDBMNzNmbDAvN29ualJGb2xZCi0tLSBt
        dXBNZ0JtMXpnTklkVmwyNEw2elRGNlpRREpyOE9MK09CTW5vOXFYbjFBCmbfhlc+
        azluJ22OcmooPGBQlcqOL53xCZyCJbIItUcP7yYzSU8qHdntMiwpHc7L1lRe/uC2
        eONsa9BxtwCfWek=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1gt53jawqp8al0dmpzf39qxpmhux2g9sqdylryy0h2wqga3e0y4c4vd8f552gsnm6vpzskcpn37j4ma9vrpz2h3z926kxzynkxrysdgug5ykvx4pxvuvwm7zcgk43r3dtwnsj8demqf663j48tdx9qfa8vzd99nzcu2y8u7ej4amrw64qetj4hp776txdya5xgrfyywvp9dtun8rk3jn4y0zk5un4zjeewxegfd9vevx5cqxryxvm8dtg3ppdxgv5vfa0jwvk8l6z3h46f3w9z628sa739ddsuumkdwjg8s3c09wnl293hxz0dca9ttwztgtqhpjnj50sxu2sfxdcc3l6c7e5rw2uqjsq2dmgnmxf3v9y27edvafmgssckv6my0z9hkvzdcdafxv7pynel0xyjfan4ennwgd7j9yvg7x8ueahgjq5rh4eq5u4whzwknz0wgz4ccye2kstjazhttmqmnyezkr9t0mjlgskezy9836vrnxd8f47d228zvrqjf5swpxz7zc6dnp4zumn53w655gdyyg3u0pvtj4a4akvlkgey4x7wczjjhyuka5m7zy99w5r8vcknw5zswutypy35dnc4qz8y97dyqu4nw307xfv5hjpuyjc5wkfrtdy7ae7ws5awhwxyk4625594g8ak3eqztqcc0yyftdeq97ywq7va2zkx72733jvjvd84nmz2raxe389gx35autg0ucqnqjtjz6wmwaz6syf23gna8mtk7pptpc20pp3vef35qvrldhgzumccrs4a2vfaxawddtm6rdytgaxenzztdhr8jmufcduqk44ge9xslnqdpagh7477fv60p5hy5ayg4zum38qf8xz6ddmer7qrt42jwatzwqap6ndzhn5fxs2d4nttr5q57gy7dedlra55znsg9cez4zyy2vctda78n53dplp845re35kr305ua9dy2mngxzmhldz3nqg4jnslfnykd9ftc2pv77t9pm57y5cujdkfdc28dreg3pyyz4vpsp7au4q87efpuv25vkfxsrt57rq04su6smjpuvmypnqdrje6duzxkf0dvmgf45kfpsxqyvsvefd4ayydgxp6hn4huqa4rdmaqxw0a4n8ysp7uqp0e7m26v5ksxxjwantkm3krw4jh02j97yp3j0dv2y5qcgh4xpq7djs5ysgs5c25q56t2r6m2trxfuqmgdfz4jy8ydmpx8fmdpk6ynf97pswsdq6tzm8drjvlv308c30ej2wmk0pf92mf5qfqk348hg00wnx5grqygxjpzqe8j2ejvwvvdufhjqs2fyp4r8x0fqep0g6r7cfn0kpn8e9qyskjqdlhu2ugek0qd3d5vnwt94lv600jy4qhuz587pc4vzquqe66sy7ftwfzz6jnzpc267s6t8naz9cga8psee2gzc2zywjnm5rl489cfns9c59a29qzlkns8wujmg3zvdvkn5xfdlqaqe8qn28sf2x9d8t4xzsdzqk667qq4srf4kcattw5ddgl9n94rrk454y3efwzhsa5dyxsska9qpamj93z6rp7jfw8cgjgzws6a4jnyk8xp5t8ugjsxxquxxcz7pzyjx2u38dcjggqzqczuxrpfmju9ek0243pat2pquj0hmvv2smjgfkvr5mdzn2zvse5hrg3t8v992au2n8gypzdqa2s3p26kjkqjt23g4g525mttu7rgvuavd94rd8l4gu46egp0l3k5rgs467a3tl83gzf3pzn6ynru2jtjsvkt4ag3qqejqd7mfvpv3668w5rrnk5re8lqpd33fyg9ee4np93eql4thvx0kggyyfmvqy9fuckqj9lzgfdyzrgkmq6hvhj277j2qyqh7lrn8ya7v9stp8q65ujuffstktg3xnhah3g0fnqul8k5y9eckc540jc5fyr8k4r80vasq0x0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-07T21:12:25Z"
  mac: ENC[AES256_GCM,data:eYWV0p/HJoVSWiutumODNbZfvV/q3taVFjk+luY8RehhNOSyHKkfsxmfukF0L4SPVQklXzMNDMKkaGQWm2EqGF5zMMdkASgTOHWENqvVxfmOLH5vo748WZ15k2hr3H/I5doqPV2jTm3+Cr+S7rLaCCc3sZR9yPUa2iYRek4QIMk=,iv:114N34ZjV2q0qGKurMolOl8+crKQwl6sCnHf6gEewVM=,tag:0SATKlYfoD/L7RhOBBJq5A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
