apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-dnsendpoint
spec:
  refreshInterval: "1h0m0s"
  target:
    name: cloudflare-tunnel-dnsendpoint
    template:
      engineVersion: v2
      templateFrom:
        - literal: |
            apiVersion: externaldns.k8s.io/v1alpha1
            kind: DNSEndpoint
            metadata:
              name: cloudflare-tunnel
            spec:
              endpoints:
                - dnsName: external.{{ (fromJson .cloudflare).Domain }}
                  recordType: CNAME
                  targets:
                    - {{ (fromJson .cloudflare).TunnelID }}.cfargotunnel.com
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  data:
    - secretKey: cloudflare
      remoteRef:
        key: 2663d32c-47b4-4e4c-917d-95cd4bae8fb8
        property: password
