apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-secret
    template:
      data:
        TUNNEL_TOKEN: |
          {{ toJson (dict "a" .AccountTag "t" .TunnelID "s" .TunnelSecret) | b64enc }}
        CF_DOMAIN: "{{ .Domain }}"
        CF_TUNNEL_ID: "{{ .TunnelID }}"
  dataFrom:
    - extract:
        key: 0284a096-ae26-4c1e-8df0-b42800f0837d
