apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-secret
    template:
      data:
        TUNNEL_TOKEN: >-
          {{ dict "a" .AccountTag "t" .TunnelID "s" .TunnelSecret | toJson | b64enc }}
        TUNNEL_DOMAIN: "{{ .Domain }}"
  dataFrom:
    - extract:
        key: cloudflare
