apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:hQTWcvugPm7x/1+3XJNZGZSTmRX3ERAKzisQQ/ZXqZ7J8lFuPt4iaFT7tV9FsSbvuPLgcMlEDIMhIxK4aomqk7y0kGuynY0DBiNuSw9acfo/lEsN2wOeKi9U6HuvkOXY1bxHuZQCxYTk5ruJd8gXGCTozky7YFmAmOPLVvvpDReILbmOca7zFpy2npuVvcOfUSBQRMNOn5GOLvO9frC7zxF6DFqhoGWmtQ6J8QE9TT/DcZpA,iv:gxCN0/NwlSekKhdvRUKysggZUziy0/rFtm6+bLz99lo=,tag:V2Kwn+Xt6AoePjN8/8+dSw==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSHg2RDJMeVZPNHRTdG95
        UjI3TFZ6cm5odDVnZmlVSDRRNjdEOFBPWnprCnNGaTZaaFRId2wzSkhzbGxHVmtz
        cXA0UXVjTGtNbHZzNUlwT1VXbzEzd0EKLS0tIDQwckFkQUlWcEpUVHpFTk1jZktu
        c010U3dDcFArYU9nVXFSN3VaWFdyWmsKuFiryvxXM0fJ5cOVXllNwLAjnGvEr6q4
        N1GOxGd10DKCwfWx4DWNkot3ATIia0Pd0JgTy8+AYQXGZfWpK3GUzQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T11:07:42Z"
  mac: ENC[AES256_GCM,data:rc8SIaf/aVkv9+KFL+kB5Oo5xLy6iNmqE3G6YnD3pp72RgIf3cWNETjWgaKxKEe1TeF8JVUed+4TQdoxOtMOHJ8lp/Vzlcj5SRJAKzhJBHYBgwZoxMJTPuqYCDAygsk7WtYGvpkFIXOjSzi9tyrxGiYsSFvsomZjcMsEEmn7Mhg=,iv:AkvkCJkfXDzuZJdKP1AZpB021jzbu/cGf8ob2fRwlnA=,tag:7lX63YCAS0RS2rU8EyMHYw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
