apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:veo/qOC/r7Tr+Sg6w13FvVAxUjFnnZlLCy8eOJYY4t0N+q+9NPRjaILz7oBgjBPCPZEzVzsn5AwqVA8/hKdzeqcnvZNRl0xYqN4RGlhBJJJBSlieuyxWgAs5976L+O7EOArJoI/LtW3x+5unNyln71peKEoNPxvRr4R3uaNenb5YmKxtdvpltGtWqOn2bBLvsfKexJWs+WqZXTbfJonrSFEfqZV2u3WftZDrexKzCp3qASYs,iv:vLqM7g8LNlZt1iEILiLGR4faOyPfX4U6gyidAaEjTgE=,tag:+K3E60ptTrRI8qZmWHZtqQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGpUYXFnQzZz
        MVljZFBlOCtaLzF3a1RIY0FxajQ2UlM1NVRESVduZ3U5TTRCNVZKOUYyN3hybm9F
        OUlnYnFJVWkzeWZDN3QxTFhsVDZEZVVTRm9JUmVNcjkyRHNacEJFM2c0S1pub2hC
        bVVuL2JJUWJkQkVJM2hGZWREYzdnNHVWaE9Qc2VlUXJvZ3o3NzN3L3hRMVBoMXdT
        ellqWW14dzE5Tlhmc3hkQ0VzQmR2b1Y4c0x4aGFqVXR4SklmU05ua2F2K0tqVHIy
        MkQrRWk5R29pWjdBWXpaUGluRUN6WkZYa3lDTytmVGhGVEl2YVBUMk5XRHBDakNO
        cU1JNG5YKzkvaU8yQXduMTBYbnVUcjR3U1ZubDBLNy80NjZ4bGs0bkxOWHMyMlRy
        Y3dxRWFHNXhMZ0xRZCtXTHhCOWhNMkxHalZTYmJNR3JSYWR0U0l6bmRhdEQ1dGM1
        T3Bob1Uwb3d3T2U4N00rNmZlM2hlSmVUeGNZYm83OGhtT21YTkM5NUl5dlFEcVBL
        U0NQWFZJVWMzMFN3WHFPTytYRzBScnBYaUJqYWE0UkVQTGNYOGdIOXpDcWNzRGRi
        N2dsR2NsQ3paZ21iekE2MXpOQWNLNmpUN1VScFhLL0FRcFNwV29YMWplNGU1TXVi
        cVNGb2VVRjJ2RDJhZERCTlRCMzcwYm92aDVYTVZzS0QzRlNRWjUrLzFJT1hzT3JU
        SS94UHBlOGRLQUhFKzRHWW56QWxLK2VuVytIOTZDWTVLVG95NjJDSis3UGdFblJD
        Y1pFM1V1VHdCcTlpZzNRV1E3NWtnSkxQSXhzMEZ3a0wyL0hBMkVCLzE5cnAyUFUx
        ZFJGbThIMWlFb3ZBUlVDc21RREo5SnVxU3dyd2RsSk1BVGZMT1FvVlJIcXpmMXRM
        QWE3cE42TU4zYjBtL2NYclp5UGZkelNTOUhwR3Z2MGhaZ3VieHRwdjRYVmp0N3Rn
        aWQyOC9jVXpCeUJBb0UycTY1dGFObnd3ZThKdU9PVkZnbXVoZm00Y1gyaGRCUFJn
        MytMZEFOSkdZLzhhdmIzMXlGYUQxc2M5Q3NJQXh0Sjd0cU1GdmFwUDRKbDhHTWF0
        cDlvcjFoeHVVY0hxTXVZU0xCUnRRaVRNcEd6OVlFY0xpUjZEanRCVUlyVUJlcDFh
        TE5DdHcwd3E2RjVzMWRjVmNZNWdzWTQ4L1pIc3ZnU1ZDdEtsQTYvaFVOYzFuc1U5
        dWdjRm14YzdKWHVLSnRKbm1Gd1JPV2tMVzdPMHZUeEk0K3BuVzNmd0lFTnVOVm1h
        alQwNU9lbXhxQWdrbkdZVlRSRmMvdnFnWmVuN3ptRFZnL3NaczE4LzhLZlRnbFdZ
        YVAwM2FCSllGNmgwNTc5QUpnZmNqM25TRkU2MlQyeVJuSWVtazQxNGg1c2VWWEph
        VnhEK3ZsU3VqOHhsTjMrQWtNKzZjbEJwN2pyc241bTVmS1FMcjErdS9UTGNGaVo5
        VmxleldaaklaeXNoaDM4UGFvbkdWNUFBWEY3bDRES2JpcVFvcGdtTVUyVy9kdmRv
        Kzg0TnhPd21LdHZNd1FTTHkzY096eG93bzhUMk1jaWFiSzNNSGpHYkFOS2hZbmJx
        MHAxUUJPd1dReVZBRzJpbDVCSmZDc2k3UmJqWUpuTjRiVE9hVVdDYmNsM3R5TlNC
        SFcrdGZlVnZNNFpYem9MR2wwckZvcUl3NzFlQUhaVSt0ajBEYUtwMDFvZlNPWFRr
        dEF4bThSWktoNm9NYmlOaTRwMW9KWDZycGdxdGJTQm5Vb2JuQjJ3QVRDMy92NzdJ
        WmdTMEszZDJIUUpRRVlxVFF1Q2VXY0tTUW02cjZSL2FRSGRZT1JlbXZiZGMzb3RG
        ZjR3SGxkUVlsNFErMGhINERzNkdLV3JHMk01V2I0TlEyU0gxc1hzMDkrdGtJMUZP
        cURjdjQ4T0ZKeVEwMVNwazdmSTFQWlFkc2NDTi9TMzU3M3BhRmVrakJBclhLdwpv
        bmp5RG1ZQzhtdkhSQ1RwQVBTOFE0bW5yK2srd1RCejhJKzRaK1pqMUtFCi0tLSBt
        SHdUd2NpeE56ZG1keFd0N3g2UjFoeUVUUjAxTW1DOVFvYkkwTWZmbE1ZChnzaTnH
        G/VidtYq7mDGnGhAqtiJhn0myjGw8Qa6iN+vIto1q2OmyciRJqztiv87MBdsKy6E
        gSg1BwMQUgfYmJc=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1gt53jawqp8al0dmpzf39qxpmhux2g9sqdylryy0h2wqga3e0y4c4vd8f552gsnm6vpzskcpn37j4ma9vrpz2h3z926kxzynkxrysdgug5ykvx4pxvuvwm7zcgk43r3dtwnsj8demqf663j48tdx9qfa8vzd99nzcu2y8u7ej4amrw64qetj4hp776txdya5xgrfyywvp9dtun8rk3jn4y0zk5un4zjeewxegfd9vevx5cqxryxvm8dtg3ppdxgv5vfa0jwvk8l6z3h46f3w9z628sa739ddsuumkdwjg8s3c09wnl293hxz0dca9ttwztgtqhpjnj50sxu2sfxdcc3l6c7e5rw2uqjsq2dmgnmxf3v9y27edvafmgssckv6my0z9hkvzdcdafxv7pynel0xyjfan4ennwgd7j9yvg7x8ueahgjq5rh4eq5u4whzwknz0wgz4ccye2kstjazhttmqmnyezkr9t0mjlgskezy9836vrnxd8f47d228zvrqjf5swpxz7zc6dnp4zumn53w655gdyyg3u0pvtj4a4akvlkgey4x7wczjjhyuka5m7zy99w5r8vcknw5zswutypy35dnc4qz8y97dyqu4nw307xfv5hjpuyjc5wkfrtdy7ae7ws5awhwxyk4625594g8ak3eqztqcc0yyftdeq97ywq7va2zkx72733jvjvd84nmz2raxe389gx35autg0ucqnqjtjz6wmwaz6syf23gna8mtk7pptpc20pp3vef35qvrldhgzumccrs4a2vfaxawddtm6rdytgaxenzztdhr8jmufcduqk44ge9xslnqdpagh7477fv60p5hy5ayg4zum38qf8xz6ddmer7qrt42jwatzwqap6ndzhn5fxs2d4nttr5q57gy7dedlra55znsg9cez4zyy2vctda78n53dplp845re35kr305ua9dy2mngxzmhldz3nqg4jnslfnykd9ftc2pv77t9pm57y5cujdkfdc28dreg3pyyz4vpsp7au4q87efpuv25vkfxsrt57rq04su6smjpuvmypnqdrje6duzxkf0dvmgf45kfpsxqyvsvefd4ayydgxp6hn4huqa4rdmaqxw0a4n8ysp7uqp0e7m26v5ksxxjwantkm3krw4jh02j97yp3j0dv2y5qcgh4xpq7djs5ysgs5c25q56t2r6m2trxfuqmgdfz4jy8ydmpx8fmdpk6ynf97pswsdq6tzm8drjvlv308c30ej2wmk0pf92mf5qfqk348hg00wnx5grqygxjpzqe8j2ejvwvvdufhjqs2fyp4r8x0fqep0g6r7cfn0kpn8e9qyskjqdlhu2ugek0qd3d5vnwt94lv600jy4qhuz587pc4vzquqe66sy7ftwfzz6jnzpc267s6t8naz9cga8psee2gzc2zywjnm5rl489cfns9c59a29qzlkns8wujmg3zvdvkn5xfdlqaqe8qn28sf2x9d8t4xzsdzqk667qq4srf4kcattw5ddgl9n94rrk454y3efwzhsa5dyxsska9qpamj93z6rp7jfw8cgjgzws6a4jnyk8xp5t8ugjsxxquxxcz7pzyjx2u38dcjggqzqczuxrpfmju9ek0243pat2pquj0hmvv2smjgfkvr5mdzn2zvse5hrg3t8v992au2n8gypzdqa2s3p26kjkqjt23g4g525mttu7rgvuavd94rd8l4gu46egp0l3k5rgs467a3tl83gzf3pzn6ynru2jtjsvkt4ag3qqejqd7mfvpv3668w5rrnk5re8lqpd33fyg9ee4np93eql4thvx0kggyyfmvqy9fuckqj9lzgfdyzrgkmq6hvhj277j2qyqh7lrn8ya7v9stp8q65ujuffstktg3xnhah3g0fnqul8k5y9eckc540jc5fyr8k4r80vasq0x0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-08T19:17:10Z"
  mac: ENC[AES256_GCM,data:loF3yK+3EIPgduKAU+Wpx70Kg03bu7D0Zj30LCy9QywOczi7tdkcavme+skh4GeIG/DUp2pthun02EwMFmlBLo6ppIpnSnSgotTLskmldr72uyqqSxCdWbak3ZUJ3BoKlGM9JQ3+/qnAWMuC4SEwvR8gFwrujClI0qR2KR1pSq8=,iv:tea3FEFTbXLL5hhhMyZ1Iyu2sE7BqCSgVnNXj35PcQk=,tag:b28F76a7QzD7jEReII34QA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
