apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-secret
spec:
  target:
    name: cloudflare-tunnel-secret
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        key: cloudflare
        property: TunnelSecret
    - secretKey: TUNNEL_DOMAIN
      remoteRef:
        key: cloudflare
        property: domain
