apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:gWFQlAANNoA3f2COOQSBTO7DJqiufbPRA5zxraU+29qktZKFU1x3oxfUm6q5TS519bIVGSpvQ6QRnPeaRC4a/3kMIookaDnt4CoOMJPdetXJ+F4Ac7Sm2JZ8oxqpc+H8uHYn51Bjv4GSKe3tix4PPzaHC0UAhGInelVSd4wZnIYDvIWEpXs2t4ww57jKO5XYsBb83cI6PU8LchttjFSRw38RWzvmFxtikoKNiCZ+3s+QYuTJ,iv:L5iQpnSLC2x3an4qvgvbuVdjVENFaukTo/kmfcVOyFI=,tag:RMDJpqFf+qZTYDssxl2GLQ==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NlhvM3hOaUZIYTA2bnlU
        cnA4OTZkWmN2bUh0RTdEb0srUkVZM2xGbWo0CldFYzBxOHpDRExjUmJWMEZSRUFt
        NHdaek8yQlRNbUkySElZbDE0djkzaG8KLS0tIFhjWCtlZDQ1Zk00VUVqOVpPamFH
        Y0loK0N0c3plY29YVTNQQ2xVOFVnZTQKbkAqrLs24QG4c8vAOzFcE+JNC7cr1CQ7
        NrOdndAyzuhajPExYlBzJnhw1MMsAq3SdsDgMkXsJaa/GZcmkXzn0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T12:25:18Z"
  mac: ENC[AES256_GCM,data:RbaUi93b4YozSZBfZZTH7NS3O2ZKYFJhiQ+pqMuSf4ubA8B/7nKKO8pnHgMOlnH1wiqNN3mgSLiblKQEq0l4Z9qW8tpRoHXdB7Zc4Lrl4yNcNEwaEdcdTTWpq8y6Q6V4kh6uxj8xnJjgUTAnYbjWu4xWw6+YVVSmwufJYG2kHhQ=,iv:9RwISDvqs1Z7BCo9xHftJN7i+SECuCiXFyqkhSdo6Us=,tag:A2h19VnxfqZPcXDINLuigw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
