fullnameOverride: k8s-gateway
domain: aknuk.dev
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    lbipam.cilium.io/ips: 192.168.8.201
  externalTrafficPolicy: Cluster
watchedResources: ["HTTPRoute", "Service"]
