fullnameOverride: k8s-gateway
domain: aknuk.dev
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 192.168.8.201
  externalTrafficPolicy: Cluster
watchedResources:
  - HTTPRoute
  - Service
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQWxlczNBN3VlOHNNZlMz
        Z0JIbk5JUmtwUjU2N3pTMU1BWjNmb1ZtT2tNCnN6WXlvd2VpL2FOa0czWUNiWkdS
        TS9EcXJieDlmR2NNZGFQb2haTENRZncKLS0tIHpuMW5SY1ZEb3ZiMkVjN0hxQjFv
        dTcrZ2ZRNSs3RndWOVN2a25oWTZOWVEKrXNUIwEDWui0LCJAuWBPMxGqIwW3dKEf
        1CJcFA+m0sddOTUkbr9LUBufgf//SORF2H0amPDCDPzVwdw89KDOtA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T19:34:38Z"
  mac: ENC[AES256_GCM,data:Zh6VoK3QFuhGjS9j7pKGniFYwUwTJQ0om7SXoBadrAAPc5ai9ssr3YZ44JnwUwN0e0QF9zMkiUAhAXOFhaWym9pfd5H6/rI/RiuQYzCL5DepGEDneMJ0xHdWvxkVao0zQIKSGNIEvyp6oYMAVPW1l5NxtxsV1DaSdtD3Hsd325c=,iv:dqsRhi2UwoSZrCJS81y7/5FM3GUHeopU5iZJLPD08Ac=,tag:UgDRjE7ucKfYG+RfVYK57w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
