fullnameOverride: k8s-gateway
domain: aknuk.dev
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 192.168.8.201
  externalTrafficPolicy: Cluster
watchedResources:
  - HTTPRoute
  - Service
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOTBMblQvYmRWdS83Mkpj
        S1J5Ky9ZOVo4VDg0ckU2aFo3RkZUUFBoYkdnClFmVldjbVdJNFRldzFZUzcrUmda
        cmwzc0xoN3lacGR1RHZ4Z3k0MW9aVU0KLS0tIFBOTW4vV1hnamtoaldWdUJ2NUVm
        NERFaFdzdHlQZHZQaHUzMGo2VCsrVlEKkaxV44icALDnd3YcLw96d6/kFvLzqbWB
        1GLoUYueoF7gK8+k3Up6YcOA0esz3f5muMweHrSCUbYLDV3YN6YNYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T10:49:38Z"
  mac: ENC[AES256_GCM,data:hSupOqUHUki2x3dp38zyTWDhBrSxUlx8LW68o2dswUZX247sdaiZKY+zXUWHUhFphR2unvbh4cKJ6Nf6JcR1kl3lASi8T+7b09/dcxbWL/C7o5LLelZslvAnPnX3VKBbdPDGAzz96mWZ/HZTnWMbtZTsakvFvRR/33gICk6+Hzs=,iv:GKjMDQ46fq/REwg3N2zIdJuPKeyEbAIIAO0+Zn4xq7c=,tag:Fs5q9n6IFHQdORkzp66rZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
