fullnameOverride: k8s-gateway
domain: aknuk.dev
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 192.168.8.201
  externalTrafficPolicy: Cluster
watchedResources:
  - HTTPRoute
  - Service
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucWhOdThJKzJET0sySUZC
        VSt5aGtnb3FhMy80LzJING1GU255SzVaSEZjCjZHZENQWitzS0ZIT3l3bGx5K2Vl
        KzNOMXF5UkIvdmw4N2pzclE2dWF3WjAKLS0tIGhRMXphVXMyZXBoOFpGWURDcmN4
        WG9ZMDdLQmlIZHNHdWs1UE5DRURRa1UKiCq7z5CBJUVRjb9XG2NvSgFDD4nU9Mmv
        rdrAj2YMNuGSIE6za2xBGPHsUPbDO/VILQR/TjGKEJruIr0al+hfMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T11:21:44Z"
  mac: ENC[AES256_GCM,data:5RSJ4xGYLoqRejsRQlJBRa3NvWj2OALxRFmud80OcwXDO96GXEKVIhgkHPwGB2h6WhvBWVNMBL+vgA1Ju3XwQrkr0EZVZFGCQvos0SAST7WJdGt/5PdQneH+nyCFnjC7V33R9NTkin7/xEfetVE660REkQrG29PlmyzEcceokTE=,iv:jp+HjZl3K7C5z1JXgBd3SdNEb4nfi+cNaJ7G0rKDsgw=,tag:nIA0jPppzWlqIfTEZMHJBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
