apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-nfs-driver-config
  namespace: storage
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  target:
    name: truenas-nfs-driver-config
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: freenas-api-nfs
          httpConnection:
            allowInsecure: true
            apiKey: {{ .apiKey }}
            host: 192.168.8.3
            port: 80
            protocol: http
          instance_id: null
          nfs:
            shareCommentTemplate: '"{{ "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}" }}"'
            shareAlldirs: false
            shareAllowedNetworks:
            - 192.168.8.0/24
            shareHost: 192.168.8.2
            shareMapallGroup: nfs
            shareMapallUser: nfs
          zfs:
            datasetEnableQuotas: true
            datasetEnableReservation: false
            datasetParentName: home-lab/nfs/kubernetes/volumes
            datasetPermissionsGroup: 3002
            datasetPermissionsMode: "0777"
            datasetPermissionsUser: 3002
            detachedSnapshotsDatasetParentName: home-lab/nfs/kubernetes/snapshots
            datasetProperties:
              "org.freenas:description": '"{{ "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}" }}"'
  data:
    - secretKey: apiKey
      remoteRef:
        key: a8000117-2f76-465e-b7db-8a9c2993686c
        property: api_key
