---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimir-s3-secret
  namespace: observability
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: mimir-s3-secret
    template:
      engineVersion: v2
      data:
        access_key: "{{ .aws_access_key_id }}"
        secret_key: "{{ .aws_secret_access_key }}"
  dataFrom:
    - extract:
        key: bc7ddb89-0509-4464-aa2c-b42801206116

