# Default values for AMD GPU Device Plugin
# Usually this runs as a DaemonSet
image:
  repository: rocm/k8s-device-plugin
  tag: 1.31.0.9 # Or specify a specific ROCm version matching your drivers
  pullPolicy: IfNotPresent
