---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-postgres-secret
  namespace: observability
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: grafana-postgres-secret
    template:
      engineVersion: v2
      data:
        # We inject these into Grafana
        GF_DATABASE_TYPE: postgres
        GF_DATABASE_HOST: 192.168.8.3:5432
        GF_DATABASE_NAME: grafana
        GF_DATABASE_USER: "{{ .pg_user }}"
        GF_DATABASE_PASSWORD: "{{ .pg_pass }}"
  data:
    - secretKey: pg_user
      remoteRef:
        key: PUT_PASSBOLT_UUID_HERE
        property: username
    - secretKey: pg_pass
      remoteRef:
        key: PUT_PASSBOLT_UUID_HERE
        property: password

