adminUser: ajaykumar
adminPassword: Friendship@4
sops:
    age:
        - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQ3NqNzZ0eUhibEFJSHNk
            RU5uTzUrV3RPQ3JNMk5SdDNodGs4MzBMUEVRCjhBMUhpOS9XeDl6WlpOd2tkNFg2
            emtwRm1TRHR0bW9EelZvaWFiaGJuazgKLS0tIHBicDRYWEQ4Z2tPUGN4QUZzeHBS
            SWxJRWtyakVrYy8zRkZEN2N5TEhZZ1EK2vg5i+MxDfAUZxwQAd2h/eGd1xOl37LQ
            FDB/CxiNHOw443w0SpM2ZiUeHvgVkHVeiqDQYnNZ6x7twLiMCp68zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T06:16:15Z"
    mac: ENC[AES256_GCM,data:sPluF4u9K/9qJLNFF3u7Xdm+NVXa3tv6sB9j2LZIRnmn7abL+lkYrn89j+xyA3sw/hWQJViDSaJ64rr1Duw89soJFpNsOhxSebaes8WFWY8v4qDsYXjgRAAxLK5zLwCCC/cZuPoE9rmgtX/nQf/JeNlA1m0+Vq04TDEMAqCUWzI=,iv:tMNLYewsZJyjWujS4iS8j5whFV6XWVmygSy3DchZAAw=,tag:Phjl2X8oJXPuWit9ar2ngA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
