adminUser: ENC[AES256_GCM,data:fttvVt92eNtT,iv:Ec7dAxRD/Lk4fFq9MjxCimE8D6chaDvOrcqgn2ufKXA=,tag:vv+2B4TpxHoT1ZyyQ/aXzQ==,type:str]
adminPassword: ENC[AES256_GCM,data:okhdnMYWnmCfrJWn,iv:psJLanXEqwYDw4NE103Ch0Voe70Vu7TeHgdQ2FqF4ro=,tag:/2THu8xddxMutankljdhcQ==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBET05oZTFENi9SMWprR0ox
        ZHR3YTVMK3EramRsbUFzaiszcHJweHcwUnlrCjNHWjZPRHhIMmV0S2h1NEFKdGFq
        amRWdmJXNC9pcnhuc2FwNHlSVmNDdFUKLS0tIEJFclBLNlYrMmtpL1BUdkYzUW5u
        ZGlESjNTY3JUQlJhRE9XZmtyN0RqSjQKEBf6RM1JGF1H36VBu6WQ25dY18iHDzZS
        BZ4XNa8bJQPdiVm+aE1uM+Ct2QXVpB6FKgUB68fAy7AQQWdnspGZBA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T18:54:51Z"
  mac: ENC[AES256_GCM,data:1DKO3f4K1tE/AeeIOJ0W2HyqNHjsJKjqJXMIWuMVd4ACSGC0ZQgz5ugwQf2v1eIxPHCNosv+MCu0NGX8F6eKhZxOYngwQtiWjzccr2l8M9+D0IjSwk+P5tmvW8ak7IEhiu4GPGo+1XhLoYu8BLiJGpFWK0KM6KoiiznNrKl0KcI=,iv:56ouHxkLGYG8TJn3tDzhC5c+XvsBICpJVUbwAiHcw1E=,tag:DSwpyIRcXHg/hMiHTyFpTg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
