apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secret
spec:
  refreshInterval: "1h0m0s"
  target:
    name: renovate-secret
  secretStoreRef:
    name: passbolt
    kind: ClusterSecretStore
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: 4b58f32a-f104-4434-a2b3-b64cd5ee8bc4
        property: password
    - secretKey: RENOVATE_GITHUB_COM_TOKEN
      remoteRef:
        key: 4b58f32a-f104-4434-a2b3-b64cd5ee8bc4
        property: password
