---
- name: Ensure ZFS NFS OpenSsl is installed.
  ansible.builtin.apt:
    name:
      - zfsutils-linux
      - nfs-kernel-server
      - openssl
    state: present

- name: Create MinIO group 
  ansible.builtin.shell: >-
    if ! getent group minio; then
      groupadd minio
    fi
    
- name: Create MinIO user
  ansible.builtin.shell: >-
    if ! getent passwd minio; then
      useradd minio -g minio
    fi

- name: Create directory for Minio data
  ansible.builtin.file:
    path: /{{ storage_zfs_pool_name }}/{{ storage_nfs_share_name }}/minio
    state: directory
    mode: 0755

- name: Change Minio SSL directory Permission
  ansible.builtin.shell: >- 
    chown -R minio:minio /{{ storage_zfs_pool_name }}/{{ storage_nfs_share_name }}/minio

- name: Create Minio configuration directory
  ansible.builtin.file:
    path: /etc/minio
    state: directory
    mode: 0755

- name: Create Minio SSL directory
  ansible.builtin.file:
    path: /etc/minio/ssl
    state: directory
    mode: 0755

- name: Create Minio policy directory
  ansible.builtin.file:
    path: /etc/minio/policy
    state: directory
    mode: 0755

- name: Determine system architecture
  ansible.builtin.shell: dpkg --print-architecture
  register: arch      
    
- name: Download Minio server binary
  ansible.builtin.get_url:
    url: https://dl.min.io/server/minio/release/linux-{{ arch.stdout }}/minio
    dest: /usr/local/bin/minio
    mode: 0755

- name: Download Minio client binary
  ansible.builtin.get_url:
    url: https://dl.min.io/client/mc/release/linux-{{ arch.stdout }}/mc
    dest: /usr/local/bin/mc
    mode: 0755

- name: Download Minio client binary
  ansible.builtin.get_url:
    url: https://github.com/minio/certgen/releases/latest/download/certgen-linux-{{ arch.stdout }}
    dest: /usr/local/bin/certgen
    mode: 0755

- name: Create TLS cert for minio
  ansible.builtin.shell: >- 
    certgen -host \
      "localhost,{{ cloudflare_domain }},*.{{ cloudflare_domain }},{{ minio_domain }}, \
      127.0.0.1, \
      {{ network.eth0.ipv4_subnet_prefix }}.{{ hostvars[inventory_hostname]['ip_host_octet'] }}, \
      {{ network.wlan0.ipv4_subnet_prefix }}.{{ hostvars[inventory_hostname]['ip_host_octet'] }}, \
      {{ network.tailscale.ipv4_subnet_prefix }}.{{ hostvars[inventory_hostname]['ip_host_octet'] }}" 

- name: Copy generated TLS certificates to /etc/minio/ssl
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/minio/ssl/{{ item }}"
    remote_src: yes
    mode: 0644
  with_items: "{{ minio_certs }}"

- name: Configure Minio server
  ansible.builtin.template:
    src: minio.conf.j2
    dest: /etc/minio/minio.conf
    mode: 0755

- name: Service Minio server
  ansible.builtin.template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
    mode: 0755

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable Minio service
  ansible.builtin.systemd:
    name: minio
    enabled: yes

- name: Start Minio service
  ansible.builtin.systemd:
    name: minio
    state: started

- name: Set minio alias
  ansible.builtin.shell: >- 
    mc alias set {{ minio_cert_org_unit }} {{ minio_url }} {{ minio_admin }} {{ minio_password }} --insecure

- name: Create minio buckets
  ansible.builtin.shell: >- 
    mc stat {{ minio_cert_org_unit }}/{{ item.bucket }} --insecure || mc mb {{ minio_cert_org_unit }}/{{ item.bucket }} --insecure
  loop: "{{ minio_config }}"

- name: Create minio users
  ansible.builtin.shell: >- 
    mc admin user add {{ minio_cert_org_unit }} {{ item.user }} {{ item.password }} --insecure
  loop: "{{ minio_config }}"

- name: Copy minio user policy
  template:
    src: "user_policy.json.j2"
    dest: "/etc/minio/policy/{{ item.user }}.json"
    mode: 0644 
  loop: "{{ minio_config }}"

- name: Create minio users
  ansible.builtin.shell: >- 
    mc admin policy create {{ minio_cert_org_unit }} {{ item.user }} /etc/minio/policy/{{ item.user }}.json --insecure
  loop: "{{ minio_config }}"

