apiVersion: v1
kind: PersistentVolume
metadata:
  name: opencost-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: ru.yandex.s3.csi
    volumeHandle: opencost-bucket
    controllerPublishSecretRef:
      name: csi-s3-secret
      namespace: storage
    nodePublishSecretRef:
      name: csi-s3-secret
      namespace: storage
    nodeStageSecretRef:
      name: csi-s3-secret
      namespace: storage
    volumeAttributes:
      bucket: opencost
      mounter: geesefs
      options: "--memory-limit 1000 --dir-mode 0777 --file-mode 0666"
  storageClassName: s3
  claimRef:
    name: opencost-pvc
    namespace: observability
