apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  hostnames:
    - argo.aknuk.dev
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYWx5TVpOa2NDV1NpNlMx
        SCt3eUZhZ3lTOXMvK2FCMklPZlNEbkxlajJJCjdYRno1ZmRLeXFsbTQ0NHpaeHpK
        YkhVcFVKdnV5SGhXU01VY3o3U29IRjAKLS0tIHBoWUVBSXZFUEVjNEw1NG4yOHpF
        MTJJTmtxT08vMXY5b1UxVTVKUWtMMGcKhaPDCOxufws0+8hyJFIx/06VKwJu63za
        0Iz0mODnEYacz8+WpDEZe3a/jYDZCjMelJfeI+brfXF2YIumKldpog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T19:38:31Z"
  mac: ENC[AES256_GCM,data:/IsmxB9PGgGeoutnh1jD0BX9N00ShjZTy8KdB/CAl0u3jBSSDaGpA3i/QjHT+Yq9zDqwMn4DOmOZv5j4ad0tVbg0FYFaU3knDMGEEsh8dt1E/4T9NlECsRl61sXA414tfYIPsVEi9I60dbz9CObbFSnSQcDR21JFMqbp24AOk+s=,iv:6f4E3yXOPzZLrpQT3AU7DaW+OD/NTBEXGnESM+pFmks=,tag:EtX14GB65GBADP79/95z3w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
