apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: passbolt
spec:
  provider:
    passbolt:
      host: https://passbolt.aknuk.dev
      auth:
        passwordSecretRef:
          name: passbolt-secrets
          key: password
          namespace: kube-system
        privateKeySecretRef:
          name: passbolt-secrets
          key: privateKey
          namespace: kube-system
