apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: passbolt
spec:
  provider:
    passbolt:
      auth:
        passwordSecretRef:
          name: passbolt-creds
          key: password
          namespace: kube-system
        privateKeySecretRef:
          name: passbolt-creds
          key: privateKey
          namespace: kube-system
      host: https://passbolt.aknuk.dev
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RlRhUngwSnlQdGMwNDkx
        Q2xBRmJtdTRGTktKZUFEOXNXOFpHYmJnd1ZBCkZ3MTJFTlh4VFRpbG5hV0FNdU5i
        Rmo4T2dsRmN4TDBhRFljQy9HZlZ6cW8KLS0tIHBHaEpnaGE1REx2WElqdU1naThT
        U0RabDBZbzM0cTExQVU3RFk2NlRsUXcKKTGYANa8CO222BEmnojELCesn1ZS25e/
        2CjO3Q3qdoHukPZkvzFj1awT4BuHOBVfiKChQ08FEmiIXpgULNJK7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-01T13:02:08Z"
  mac: ENC[AES256_GCM,data:itlb5C6S12X36VjdF59AVwSndESubSh5YxcuEd2Liji+L1BlFZXLr/aZslUsZYQrxOy268SDDDvOnyQL9D5x/oOQW8Dbvf6vYRf9nqlFDJKff0S11WjVvRWqIRC2gZ/OEdGOWXIqG+iyW4656/6TeU3YLXSBqKhqoGZ5K2qc8gY=,iv:dyqVZ2BWdFvzjnXu7//lk6eUOiYTCXd+ErsO3ReTyLc=,tag:keyPjv2uodzAK25PQwSuwQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
