apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: passbolt
spec:
  provider:
    passbolt:
      host: https://passbolt.aknuk.dev
      auth:
        passwordSecretRef:
          key: password
          name: passbolt-secrets
        privateKeySecretRef:
          key: privateKey
          name: passbolt-secrets
