apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Ut5ayGF1CDddyGSUTMMnqY0/Or0rhS8Ezlg4gY8PJs6LYia9G7RRBQ==,iv:oJr8XpaCuoZOUB9dzOZhIRT3jS9ywp91PanjlXOFhBI=,tag:IBiRm5AAR2N57kO6ecEFLg==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITTlxeHZweGJ4cXFFK3Z3
        MUl1TnJ6Z09hRmJrUU5oeWhZMURJZnl1OFVFCkk2djJaZmFHWmFuTHVNaktFNWo4
        K2tyaGJHTkl0V0p4UjExUGRhcDI3SVUKLS0tIE5TZDNiM1JZeTF1T3Z3dG1zdG9o
        c2J5UXhad09zNDhLY2ZJV3RtdURuSkEK2JLE/PxwfBTJ+ncnpIjFoDLXrWhCfWAR
        lqYoeQ4DWsaeiizAiezj2YWNMeNTPkX3MzIlbSs5e14oztrAvTF6Fg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T19:34:38Z"
  mac: ENC[AES256_GCM,data:laE5ucGJvNY7TzcVxbuGrQSf/QcBtAOmY/CoCMJKWqi3ktlFu1cFVCOPvPBVNr8u7es4GjQLsCz2poIY8kIoxwIYAsjmwqRDWoDqfpGc7iukIq5eb5D3A8caQvILty0zWiPnEX8okQ0LH8mIyprSzTRVW/Aenq8VwLHciKFytOg=,iv:OA+PmbXk+m1sGUQtyoViZCOhQuxtSf5GoxyB7ZvhLlM=,tag:kib43jAq+GuAsh1yyOU12Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
