apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:sbKG6qAO8bEUKBmqY+vBqEAle8xe7mXBoMZmjdF8sZcsssLJm1ZqoQ==,iv:vFnUB8hd3RA4pGX2IPsSm5Jti/P5G0BG2AN63AebEG4=,tag:xVBJRD3Fd8RFyd1/6TfKww==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWnJpZW9uKzUveUhUZGhs
        K1dERnVQWmhvdERmOE5sOTkrS1FxbzJIb0RzCnlJRjRRSWUxOUxWOWNZZytvclMy
        S0lNWlpGVUNsVTNWN001Ym9OUitiUUEKLS0tIFZ6NkhJV3lsZVVER2R5UnBBaXk0
        VDNGQVM2WVFQWGpwMm1oUW9uQ0FzVXcKapGDdZTt2w8YHaI+OLaNrJ43zY2NZrvg
        tWV4/ZpzHU6zMlNthcYsH0KAIfSN8YVQ7yE7aYbt6AjLfsqEiBxqXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T12:25:18Z"
  mac: ENC[AES256_GCM,data:JTnAQBgywOtuxbZ9NO4EqW0lsdxQHXCAdFVgGbHQuGdqh6AgWkS+k4128O8yfyOiYpscR93TdvYkwCWDybsnt8/+B66V1a8i0wGammE1F45/34L4abwkFPFSixyVEijr2voHwbjXKbd+fDyFWAtqddxdDcrOtdGLsqGk0B7r6q4=,iv:PUAKQAZ6RltNwyVwRXkPc2yflbibt1fQnijk9+XzCnk=,tag:edsasKintVTsa7W7ZqHoXA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
