apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:mRVpUs32huy+dZrNQvGXSUgjnEjsO3+CxUdl6jYxmXb+WUPqn9xuhg==,iv:+oO6bk9HQdKvxxjrrmlHXWgBuTzMxFOM0T8AUUUklcc=,tag:h1WBCCf3X7Wm47SadS1Lzg==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAra1RFWGI1MzFJQzlaWUtn
        V1U5SkN5RDN5c255K0pSZjBlTVVaREdBK0VFCkdzZTM2eWt3MGs5TnNVTHluNFNU
        dm9HRTY5aHZTYmJCc2kyQXhGbnphTGMKLS0tIDMxL3pzd1dzYjIzNGRxVXFVQnpP
        MVNqajJ0RnYvbC80UDhzVXcyQUpIdlkKI1iVyjL/n1qIYuBqYwQk5tU0c77lghR8
        wENLVIdP0eLoQ/fd6P4wS+5bd9S5V1hDlGKWB+n/pxgBhbczix9/ow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T07:44:15Z"
  mac: ENC[AES256_GCM,data:Z2o0wQGRfbvyKDvQ/msnzyDEwa4NeMClC3Xod1SHoGKhTguxyjSvYRNnO8xHsJ5gW5r8HQ13Xh0EAiRBXrEmrCcveCqWEWVcdD3awlk3CPNnN0GybqWX71fV52Q3kGKQPcBZnNWQbml9c1KRBWDmBY6KDhJIvKD3sQ0CLEShcFg=,iv:+0Q+Wd8h01W0fCKgvgSTfGfE97nVpI//1IwPCrZ2wqI=,tag:3FiCxUCRYI/j777lFMyFTw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
